// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsentPrivacyPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsentPrivacyPolicyArgs Empty = new ConsentPrivacyPolicyArgs();

    @Import(name="url", required=true)
    private Output<String> url;

    public Output<String> url() {
        return this.url;
    }

    @Import(name="version")
    private @Nullable Output<String> version;

    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private ConsentPrivacyPolicyArgs() {}

    private ConsentPrivacyPolicyArgs(ConsentPrivacyPolicyArgs $) {
        this.url = $.url;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsentPrivacyPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsentPrivacyPolicyArgs $;

        public Builder() {
            $ = new ConsentPrivacyPolicyArgs();
        }

        public Builder(ConsentPrivacyPolicyArgs defaults) {
            $ = new ConsentPrivacyPolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        public Builder version(String version) {
            return version(Output.of(version));
        }

        public ConsentPrivacyPolicyArgs build() {
            if ($.url == null) {
                throw new MissingRequiredPropertyException("ConsentPrivacyPolicyArgs", "url");
            }
            return $;
        }
    }

}
