// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsentSubjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsentSubjectArgs Empty = new ConsentSubjectArgs();

    @Import(name="anonymousId")
    private @Nullable Output<String> anonymousId;

    public Optional<Output<String>> anonymousId() {
        return Optional.ofNullable(this.anonymousId);
    }

    @Import(name="verifiedId")
    private @Nullable Output<String> verifiedId;

    public Optional<Output<String>> verifiedId() {
        return Optional.ofNullable(this.verifiedId);
    }

    private ConsentSubjectArgs() {}

    private ConsentSubjectArgs(ConsentSubjectArgs $) {
        this.anonymousId = $.anonymousId;
        this.verifiedId = $.verifiedId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsentSubjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsentSubjectArgs $;

        public Builder() {
            $ = new ConsentSubjectArgs();
        }

        public Builder(ConsentSubjectArgs defaults) {
            $ = new ConsentSubjectArgs(Objects.requireNonNull(defaults));
        }

        public Builder anonymousId(@Nullable Output<String> anonymousId) {
            $.anonymousId = anonymousId;
            return this;
        }

        public Builder anonymousId(String anonymousId) {
            return anonymousId(Output.of(anonymousId));
        }

        public Builder verifiedId(@Nullable Output<String> verifiedId) {
            $.verifiedId = verifiedId;
            return this;
        }

        public Builder verifiedId(String verifiedId) {
            return verifiedId(Output.of(verifiedId));
        }

        public ConsentSubjectArgs build() {
            return $;
        }
    }

}
