// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsentActionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsentActionArgs Empty = new ConsentActionArgs();

    @Import(name="action", required=true)
    private Output<String> action;

    public Output<String> action() {
        return this.action;
    }

    @Import(name="jurisdiction")
    private @Nullable Output<String> jurisdiction;

    public Optional<Output<String>> jurisdiction() {
        return Optional.ofNullable(this.jurisdiction);
    }

    @Import(name="target", required=true)
    private Output<String> target;

    public Output<String> target() {
        return this.target;
    }

    @Import(name="vendor", required=true)
    private Output<String> vendor;

    public Output<String> vendor() {
        return this.vendor;
    }

    private ConsentActionArgs() {}

    private ConsentActionArgs(ConsentActionArgs $) {
        this.action = $.action;
        this.jurisdiction = $.jurisdiction;
        this.target = $.target;
        this.vendor = $.vendor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsentActionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsentActionArgs $;

        public Builder() {
            $ = new ConsentActionArgs();
        }

        public Builder(ConsentActionArgs defaults) {
            $ = new ConsentActionArgs(Objects.requireNonNull(defaults));
        }

        public Builder action(Output<String> action) {
            $.action = action;
            return this;
        }

        public Builder action(String action) {
            return action(Output.of(action));
        }

        public Builder jurisdiction(@Nullable Output<String> jurisdiction) {
            $.jurisdiction = jurisdiction;
            return this;
        }

        public Builder jurisdiction(String jurisdiction) {
            return jurisdiction(Output.of(jurisdiction));
        }

        public Builder target(Output<String> target) {
            $.target = target;
            return this;
        }

        public Builder target(String target) {
            return target(Output.of(target));
        }

        public Builder vendor(Output<String> vendor) {
            $.vendor = vendor;
            return this;
        }

        public Builder vendor(String vendor) {
            return vendor(Output.of(vendor));
        }

        public ConsentActionArgs build() {
            if ($.action == null) {
                throw new MissingRequiredPropertyException("ConsentActionArgs", "action");
            }
            if ($.target == null) {
                throw new MissingRequiredPropertyException("ConsentActionArgs", "target");
            }
            if ($.vendor == null) {
                throw new MissingRequiredPropertyException("ConsentActionArgs", "vendor");
            }
            return $;
        }
    }

}
