// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCollectionArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCollectionArgs Empty = new GetCollectionArgs();

    @Import(name="collectionId", required=true)
    private Output<String> collectionId;

    public Output<String> collectionId() {
        return this.collectionId;
    }

    private GetCollectionArgs() {}

    private GetCollectionArgs(GetCollectionArgs $) {
        this.collectionId = $.collectionId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCollectionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCollectionArgs $;

        public Builder() {
            $ = new GetCollectionArgs();
        }

        public Builder(GetCollectionArgs defaults) {
            $ = new GetCollectionArgs(Objects.requireNonNull(defaults));
        }

        public Builder collectionId(Output<String> collectionId) {
            $.collectionId = collectionId;
            return this;
        }

        public Builder collectionId(String collectionId) {
            return collectionId(Output.of(collectionId));
        }

        public GetCollectionArgs build() {
            if ($.collectionId == null) {
                throw new MissingRequiredPropertyException("GetCollectionArgs", "collectionId");
            }
            return $;
        }
    }

}
