// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;




public final class GetConfigPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConfigPlainArgs Empty = new GetConfigPlainArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetConfigPlainArgs $;

        public Builder() {
            $ = new GetConfigPlainArgs();
        }
        public GetConfigPlainArgs build() {
            return $;
        }
    }

}
