// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentAuditLogPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentAuditLogPlainArgs Empty = new GetCookieConsentAuditLogPlainArgs();

    /**
     * Only return events performed by this user email (case insensitive).
     *
     */
    @Import(name="actor")
    private @Nullable String actor;

    /**
     * @return Only return events performed by this user email (case insensitive).
     *
     */
    public Optional<String> actor() {
        return Optional.ofNullable(this.actor);
    }

    /**
     * Only return change events of this type: text_customization, style, iab, setting, or rule.
     *
     */
    @Import(name="changeType")
    private @Nullable String changeType;

    /**
     * @return Only return change events of this type: text_customization, style, iab, setting, or rule.
     *
     */
    public Optional<String> changeType() {
        return Optional.ofNullable(this.changeType);
    }

    /**
     * Only return events for these configuration IDs.
     *
     */
    @Import(name="configIds")
    private @Nullable List<String> configIds;

    /**
     * @return Only return events for these configuration IDs.
     *
     */
    public Optional<List<String>> configIds() {
        return Optional.ofNullable(this.configIds);
    }

    /**
     * Only return events strictly before this UTC ISO 8601 timestamp.
     *
     */
    @Import(name="endDate")
    private @Nullable String endDate;

    /**
     * @return Only return events strictly before this UTC ISO 8601 timestamp.
     *
     */
    public Optional<String> endDate() {
        return Optional.ofNullable(this.endDate);
    }

    /**
     * Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
     *
     */
    @Import(name="eventIds")
    private @Nullable List<String> eventIds;

    /**
     * @return Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
     *
     */
    public Optional<List<String>> eventIds() {
        return Optional.ofNullable(this.eventIds);
    }

    /**
     * Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
     *
     */
    @Import(name="eventTypes")
    private @Nullable List<String> eventTypes;

    /**
     * @return Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
     *
     */
    public Optional<List<String>> eventTypes() {
        return Optional.ofNullable(this.eventTypes);
    }

    /**
     * Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
     *
     */
    @Import(name="maxResults")
    private @Nullable Integer maxResults;

    /**
     * @return Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
     *
     */
    public Optional<Integer> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Only return events at or after this UTC ISO 8601 timestamp.
     *
     */
    @Import(name="startDate")
    private @Nullable String startDate;

    /**
     * @return Only return events at or after this UTC ISO 8601 timestamp.
     *
     */
    public Optional<String> startDate() {
        return Optional.ofNullable(this.startDate);
    }

    private GetCookieConsentAuditLogPlainArgs() {}

    private GetCookieConsentAuditLogPlainArgs(GetCookieConsentAuditLogPlainArgs $) {
        this.actor = $.actor;
        this.changeType = $.changeType;
        this.configIds = $.configIds;
        this.endDate = $.endDate;
        this.eventIds = $.eventIds;
        this.eventTypes = $.eventTypes;
        this.maxResults = $.maxResults;
        this.startDate = $.startDate;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentAuditLogPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentAuditLogPlainArgs $;

        public Builder() {
            $ = new GetCookieConsentAuditLogPlainArgs();
        }

        public Builder(GetCookieConsentAuditLogPlainArgs defaults) {
            $ = new GetCookieConsentAuditLogPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actor Only return events performed by this user email (case insensitive).
         *
         * @return builder
         *
         */
        public Builder actor(@Nullable String actor) {
            $.actor = actor;
            return this;
        }

        /**
         * @param changeType Only return change events of this type: text_customization, style, iab, setting, or rule.
         *
         * @return builder
         *
         */
        public Builder changeType(@Nullable String changeType) {
            $.changeType = changeType;
            return this;
        }

        /**
         * @param configIds Only return events for these configuration IDs.
         *
         * @return builder
         *
         */
        public Builder configIds(@Nullable List<String> configIds) {
            $.configIds = configIds;
            return this;
        }

        /**
         * @param configIds Only return events for these configuration IDs.
         *
         * @return builder
         *
         */
        public Builder configIds(String... configIds) {
            return configIds(List.of(configIds));
        }

        /**
         * @param endDate Only return events strictly before this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder endDate(@Nullable String endDate) {
            $.endDate = endDate;
            return this;
        }

        /**
         * @param eventIds Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
         *
         * @return builder
         *
         */
        public Builder eventIds(@Nullable List<String> eventIds) {
            $.eventIds = eventIds;
            return this;
        }

        /**
         * @param eventIds Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
         *
         * @return builder
         *
         */
        public Builder eventIds(String... eventIds) {
            return eventIds(List.of(eventIds));
        }

        /**
         * @param eventTypes Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
         *
         * @return builder
         *
         */
        public Builder eventTypes(@Nullable List<String> eventTypes) {
            $.eventTypes = eventTypes;
            return this;
        }

        /**
         * @param eventTypes Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
         *
         * @return builder
         *
         */
        public Builder eventTypes(String... eventTypes) {
            return eventTypes(List.of(eventTypes));
        }

        /**
         * @param maxResults Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
         *
         * @return builder
         *
         */
        public Builder maxResults(@Nullable Integer maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param startDate Only return events at or after this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder startDate(@Nullable String startDate) {
            $.startDate = startDate;
            return this;
        }

        public GetCookieConsentAuditLogPlainArgs build() {
            return $;
        }
    }

}
