// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCollectionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCollectionsArgs Empty = new GetCollectionsArgs();

    @Import(name="jurisdiction")
    private @Nullable Output<String> jurisdiction;

    public Optional<Output<String>> jurisdiction() {
        return Optional.ofNullable(this.jurisdiction);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private GetCollectionsArgs() {}

    private GetCollectionsArgs(GetCollectionsArgs $) {
        this.jurisdiction = $.jurisdiction;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCollectionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCollectionsArgs $;

        public Builder() {
            $ = new GetCollectionsArgs();
        }

        public Builder(GetCollectionsArgs defaults) {
            $ = new GetCollectionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder jurisdiction(@Nullable Output<String> jurisdiction) {
            $.jurisdiction = jurisdiction;
            return this;
        }

        public Builder jurisdiction(String jurisdiction) {
            return jurisdiction(Output.of(jurisdiction));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public GetCollectionsArgs build() {
            return $;
        }
    }

}
