// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentDiscoveriesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentDiscoveriesArgs Empty = new GetCookieConsentDiscoveriesArgs();

    /**
     * The Osano Cookie Consent config ID whose discoveries are listed.
     *
     */
    @Import(name="configId", required=true)
    private Output<String> configId;

    /**
     * @return The Osano Cookie Consent config ID whose discoveries are listed.
     *
     */
    public Output<String> configId() {
        return this.configId;
    }

    /**
     * The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
     *
     */
    @Import(name="storeType")
    private @Nullable Output<String> storeType;

    /**
     * @return The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
     *
     */
    public Optional<Output<String>> storeType() {
        return Optional.ofNullable(this.storeType);
    }

    private GetCookieConsentDiscoveriesArgs() {}

    private GetCookieConsentDiscoveriesArgs(GetCookieConsentDiscoveriesArgs $) {
        this.configId = $.configId;
        this.storeType = $.storeType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentDiscoveriesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentDiscoveriesArgs $;

        public Builder() {
            $ = new GetCookieConsentDiscoveriesArgs();
        }

        public Builder(GetCookieConsentDiscoveriesArgs defaults) {
            $ = new GetCookieConsentDiscoveriesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configId The Osano Cookie Consent config ID whose discoveries are listed.
         *
         * @return builder
         *
         */
        public Builder configId(Output<String> configId) {
            $.configId = configId;
            return this;
        }

        /**
         * @param configId The Osano Cookie Consent config ID whose discoveries are listed.
         *
         * @return builder
         *
         */
        public Builder configId(String configId) {
            return configId(Output.of(configId));
        }

        /**
         * @param storeType The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
         *
         * @return builder
         *
         */
        public Builder storeType(@Nullable Output<String> storeType) {
            $.storeType = storeType;
            return this;
        }

        /**
         * @param storeType The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
         *
         * @return builder
         *
         */
        public Builder storeType(String storeType) {
            return storeType(Output.of(storeType));
        }

        public GetCookieConsentDiscoveriesArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetCookieConsentDiscoveriesArgs", "configId");
            }
            return $;
        }
    }

}
