// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetConsentProfileArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConsentProfileArgs Empty = new GetConsentProfileArgs();

    @Import(name="configId", required=true)
    private Output<String> configId;

    public Output<String> configId() {
        return this.configId;
    }

    @Import(name="hashedSubjectId", required=true)
    private Output<String> hashedSubjectId;

    public Output<String> hashedSubjectId() {
        return this.hashedSubjectId;
    }

    private GetConsentProfileArgs() {}

    private GetConsentProfileArgs(GetConsentProfileArgs $) {
        this.configId = $.configId;
        this.hashedSubjectId = $.hashedSubjectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConsentProfileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConsentProfileArgs $;

        public Builder() {
            $ = new GetConsentProfileArgs();
        }

        public Builder(GetConsentProfileArgs defaults) {
            $ = new GetConsentProfileArgs(Objects.requireNonNull(defaults));
        }

        public Builder configId(Output<String> configId) {
            $.configId = configId;
            return this;
        }

        public Builder configId(String configId) {
            return configId(Output.of(configId));
        }

        public Builder hashedSubjectId(Output<String> hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        public Builder hashedSubjectId(String hashedSubjectId) {
            return hashedSubjectId(Output.of(hashedSubjectId));
        }

        public GetConsentProfileArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfileArgs", "configId");
            }
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfileArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
