// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetConsentProfilePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConsentProfilePlainArgs Empty = new GetConsentProfilePlainArgs();

    @Import(name="configId", required=true)
    private String configId;

    public String configId() {
        return this.configId;
    }

    @Import(name="hashedSubjectId", required=true)
    private String hashedSubjectId;

    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }

    private GetConsentProfilePlainArgs() {}

    private GetConsentProfilePlainArgs(GetConsentProfilePlainArgs $) {
        this.configId = $.configId;
        this.hashedSubjectId = $.hashedSubjectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConsentProfilePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConsentProfilePlainArgs $;

        public Builder() {
            $ = new GetConsentProfilePlainArgs();
        }

        public Builder(GetConsentProfilePlainArgs defaults) {
            $ = new GetConsentProfilePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder configId(String configId) {
            $.configId = configId;
            return this;
        }

        public Builder hashedSubjectId(String hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        public GetConsentProfilePlainArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfilePlainArgs", "configId");
            }
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfilePlainArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
