// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentAuditLogArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentAuditLogArgs Empty = new GetCookieConsentAuditLogArgs();

    /**
     * Only return events performed by this user email (case insensitive).
     *
     */
    @Import(name="actor")
    private @Nullable Output<String> actor;

    /**
     * @return Only return events performed by this user email (case insensitive).
     *
     */
    public Optional<Output<String>> actor() {
        return Optional.ofNullable(this.actor);
    }

    /**
     * Only return change events of this type: text_customization, style, iab, setting, or rule.
     *
     */
    @Import(name="changeType")
    private @Nullable Output<String> changeType;

    /**
     * @return Only return change events of this type: text_customization, style, iab, setting, or rule.
     *
     */
    public Optional<Output<String>> changeType() {
        return Optional.ofNullable(this.changeType);
    }

    /**
     * Only return events for these configuration IDs.
     *
     */
    @Import(name="configIds")
    private @Nullable Output<List<String>> configIds;

    /**
     * @return Only return events for these configuration IDs.
     *
     */
    public Optional<Output<List<String>>> configIds() {
        return Optional.ofNullable(this.configIds);
    }

    /**
     * Only return events strictly before this UTC ISO 8601 timestamp.
     *
     */
    @Import(name="endDate")
    private @Nullable Output<String> endDate;

    /**
     * @return Only return events strictly before this UTC ISO 8601 timestamp.
     *
     */
    public Optional<Output<String>> endDate() {
        return Optional.ofNullable(this.endDate);
    }

    /**
     * Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
     *
     */
    @Import(name="eventIds")
    private @Nullable Output<List<String>> eventIds;

    /**
     * @return Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
     *
     */
    public Optional<Output<List<String>>> eventIds() {
        return Optional.ofNullable(this.eventIds);
    }

    /**
     * Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
     *
     */
    @Import(name="eventTypes")
    private @Nullable Output<List<String>> eventTypes;

    /**
     * @return Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
     *
     */
    public Optional<Output<List<String>>> eventTypes() {
        return Optional.ofNullable(this.eventTypes);
    }

    /**
     * Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
     *
     */
    @Import(name="maxResults")
    private @Nullable Output<Integer> maxResults;

    /**
     * @return Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
     *
     */
    public Optional<Output<Integer>> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Only return events at or after this UTC ISO 8601 timestamp.
     *
     */
    @Import(name="startDate")
    private @Nullable Output<String> startDate;

    /**
     * @return Only return events at or after this UTC ISO 8601 timestamp.
     *
     */
    public Optional<Output<String>> startDate() {
        return Optional.ofNullable(this.startDate);
    }

    private GetCookieConsentAuditLogArgs() {}

    private GetCookieConsentAuditLogArgs(GetCookieConsentAuditLogArgs $) {
        this.actor = $.actor;
        this.changeType = $.changeType;
        this.configIds = $.configIds;
        this.endDate = $.endDate;
        this.eventIds = $.eventIds;
        this.eventTypes = $.eventTypes;
        this.maxResults = $.maxResults;
        this.startDate = $.startDate;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentAuditLogArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentAuditLogArgs $;

        public Builder() {
            $ = new GetCookieConsentAuditLogArgs();
        }

        public Builder(GetCookieConsentAuditLogArgs defaults) {
            $ = new GetCookieConsentAuditLogArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actor Only return events performed by this user email (case insensitive).
         *
         * @return builder
         *
         */
        public Builder actor(@Nullable Output<String> actor) {
            $.actor = actor;
            return this;
        }

        /**
         * @param actor Only return events performed by this user email (case insensitive).
         *
         * @return builder
         *
         */
        public Builder actor(String actor) {
            return actor(Output.of(actor));
        }

        /**
         * @param changeType Only return change events of this type: text_customization, style, iab, setting, or rule.
         *
         * @return builder
         *
         */
        public Builder changeType(@Nullable Output<String> changeType) {
            $.changeType = changeType;
            return this;
        }

        /**
         * @param changeType Only return change events of this type: text_customization, style, iab, setting, or rule.
         *
         * @return builder
         *
         */
        public Builder changeType(String changeType) {
            return changeType(Output.of(changeType));
        }

        /**
         * @param configIds Only return events for these configuration IDs.
         *
         * @return builder
         *
         */
        public Builder configIds(@Nullable Output<List<String>> configIds) {
            $.configIds = configIds;
            return this;
        }

        /**
         * @param configIds Only return events for these configuration IDs.
         *
         * @return builder
         *
         */
        public Builder configIds(List<String> configIds) {
            return configIds(Output.of(configIds));
        }

        /**
         * @param configIds Only return events for these configuration IDs.
         *
         * @return builder
         *
         */
        public Builder configIds(String... configIds) {
            return configIds(List.of(configIds));
        }

        /**
         * @param endDate Only return events strictly before this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder endDate(@Nullable Output<String> endDate) {
            $.endDate = endDate;
            return this;
        }

        /**
         * @param endDate Only return events strictly before this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder endDate(String endDate) {
            return endDate(Output.of(endDate));
        }

        /**
         * @param eventIds Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
         *
         * @return builder
         *
         */
        public Builder eventIds(@Nullable Output<List<String>> eventIds) {
            $.eventIds = eventIds;
            return this;
        }

        /**
         * @param eventIds Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
         *
         * @return builder
         *
         */
        public Builder eventIds(List<String> eventIds) {
            return eventIds(Output.of(eventIds));
        }

        /**
         * @param eventIds Only return these audit event IDs, such as the changeIds of a cmp.configPublished event.
         *
         * @return builder
         *
         */
        public Builder eventIds(String... eventIds) {
            return eventIds(List.of(eventIds));
        }

        /**
         * @param eventTypes Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
         *
         * @return builder
         *
         */
        public Builder eventTypes(@Nullable Output<List<String>> eventTypes) {
            $.eventTypes = eventTypes;
            return this;
        }

        /**
         * @param eventTypes Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
         *
         * @return builder
         *
         */
        public Builder eventTypes(List<String> eventTypes) {
            return eventTypes(Output.of(eventTypes));
        }

        /**
         * @param eventTypes Only return these event types, for example cmp.configPublished, cmp.configUpdated, cmp.ruleCreated, or cmp.ruleUpdated.
         *
         * @return builder
         *
         */
        public Builder eventTypes(String... eventTypes) {
            return eventTypes(List.of(eventTypes));
        }

        /**
         * @param maxResults Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
         *
         * @return builder
         *
         */
        public Builder maxResults(@Nullable Output<Integer> maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param maxResults Stop after this many events (most recent first). Defaults to 200; set 0 to return every matching event.
         *
         * @return builder
         *
         */
        public Builder maxResults(Integer maxResults) {
            return maxResults(Output.of(maxResults));
        }

        /**
         * @param startDate Only return events at or after this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder startDate(@Nullable Output<String> startDate) {
            $.startDate = startDate;
            return this;
        }

        /**
         * @param startDate Only return events at or after this UTC ISO 8601 timestamp.
         *
         * @return builder
         *
         */
        public Builder startDate(String startDate) {
            return startDate(Output.of(startDate));
        }

        public GetCookieConsentAuditLogArgs build() {
            return $;
        }
    }

}
