// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCollectionPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCollectionPlainArgs Empty = new GetCollectionPlainArgs();

    @Import(name="collectionId", required=true)
    private String collectionId;

    public String collectionId() {
        return this.collectionId;
    }

    private GetCollectionPlainArgs() {}

    private GetCollectionPlainArgs(GetCollectionPlainArgs $) {
        this.collectionId = $.collectionId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCollectionPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCollectionPlainArgs $;

        public Builder() {
            $ = new GetCollectionPlainArgs();
        }

        public Builder(GetCollectionPlainArgs defaults) {
            $ = new GetCollectionPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder collectionId(String collectionId) {
            $.collectionId = collectionId;
            return this;
        }

        public GetCollectionPlainArgs build() {
            if ($.collectionId == null) {
                throw new MissingRequiredPropertyException("GetCollectionPlainArgs", "collectionId");
            }
            return $;
        }
    }

}
