// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentRulesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentRulesPlainArgs Empty = new GetCookieConsentRulesPlainArgs();

    /**
     * Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, or PERSONALIZATION.
     *
     */
    @Import(name="classification")
    private @Nullable String classification;

    /**
     * @return Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, or PERSONALIZATION.
     *
     */
    public Optional<String> classification() {
        return Optional.ofNullable(this.classification);
    }

    /**
     * The Osano Cookie Consent config ID whose rules are listed.
     *
     */
    @Import(name="configId", required=true)
    private String configId;

    /**
     * @return The Osano Cookie Consent config ID whose rules are listed.
     *
     */
    public String configId() {
        return this.configId;
    }

    /**
     * Only return rules of this storage type: cookies, scripts, iframes, or localStorage.
     *
     */
    @Import(name="storeType")
    private @Nullable String storeType;

    /**
     * @return Only return rules of this storage type: cookies, scripts, iframes, or localStorage.
     *
     */
    public Optional<String> storeType() {
        return Optional.ofNullable(this.storeType);
    }

    private GetCookieConsentRulesPlainArgs() {}

    private GetCookieConsentRulesPlainArgs(GetCookieConsentRulesPlainArgs $) {
        this.classification = $.classification;
        this.configId = $.configId;
        this.storeType = $.storeType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentRulesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentRulesPlainArgs $;

        public Builder() {
            $ = new GetCookieConsentRulesPlainArgs();
        }

        public Builder(GetCookieConsentRulesPlainArgs defaults) {
            $ = new GetCookieConsentRulesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param classification Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, or PERSONALIZATION.
         *
         * @return builder
         *
         */
        public Builder classification(@Nullable String classification) {
            $.classification = classification;
            return this;
        }

        /**
         * @param configId The Osano Cookie Consent config ID whose rules are listed.
         *
         * @return builder
         *
         */
        public Builder configId(String configId) {
            $.configId = configId;
            return this;
        }

        /**
         * @param storeType Only return rules of this storage type: cookies, scripts, iframes, or localStorage.
         *
         * @return builder
         *
         */
        public Builder storeType(@Nullable String storeType) {
            $.storeType = storeType;
            return this;
        }

        public GetCookieConsentRulesPlainArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetCookieConsentRulesPlainArgs", "configId");
            }
            return $;
        }
    }

}
