// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentConfigsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentConfigsArgs Empty = new GetCookieConsentConfigsArgs();

    /**
     * Filter by domains. Use Punycode for non-ASCII domains.
     *
     */
    @Import(name="domains")
    private @Nullable Output<List<String>> domains;

    /**
     * @return Filter by domains. Use Punycode for non-ASCII domains.
     *
     */
    public Optional<Output<List<String>>> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
     *
     */
    @Import(name="domainsMatch")
    private @Nullable Output<String> domainsMatch;

    /**
     * @return How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
     *
     */
    public Optional<Output<String>> domainsMatch() {
        return Optional.ofNullable(this.domainsMatch);
    }

    /**
     * Stop after this many configurations. Unset or 0 returns every matching configuration.
     *
     */
    @Import(name="maxResults")
    private @Nullable Output<Integer> maxResults;

    /**
     * @return Stop after this many configurations. Unset or 0 returns every matching configuration.
     *
     */
    public Optional<Output<Integer>> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Filter by compliance mode: debug, permissive, or production.
     *
     */
    @Import(name="mode")
    private @Nullable Output<String> mode;

    /**
     * @return Filter by compliance mode: debug, permissive, or production.
     *
     */
    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    /**
     * Filter by configuration name (case insensitive, partial matches allowed).
     *
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Filter by configuration name (case insensitive, partial matches allowed).
     *
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Filter by organization IDs (UUIDs).
     *
     */
    @Import(name="orgIds")
    private @Nullable Output<List<String>> orgIds;

    /**
     * @return Filter by organization IDs (UUIDs).
     *
     */
    public Optional<Output<List<String>>> orgIds() {
        return Optional.ofNullable(this.orgIds);
    }

    /**
     * How orgIds filters: any (default), all, or not, as for domainsMatch.
     *
     */
    @Import(name="orgIdsMatch")
    private @Nullable Output<String> orgIdsMatch;

    /**
     * @return How orgIds filters: any (default), all, or not, as for domainsMatch.
     *
     */
    public Optional<Output<String>> orgIdsMatch() {
        return Optional.ofNullable(this.orgIdsMatch);
    }

    /**
     * Filter by publish status: unpublished, in-progress, published, outdated, or error.
     *
     */
    @Import(name="publishStatus")
    private @Nullable Output<String> publishStatus;

    /**
     * @return Filter by publish status: unpublished, in-progress, published, outdated, or error.
     *
     */
    public Optional<Output<String>> publishStatus() {
        return Optional.ofNullable(this.publishStatus);
    }

    /**
     * Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
     *
     */
    @Import(name="sortBy")
    private @Nullable Output<String> sortBy;

    /**
     * @return Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
     *
     */
    public Optional<Output<String>> sortBy() {
        return Optional.ofNullable(this.sortBy);
    }

    /**
     * Filter by whether discovery recording is stopped.
     *
     */
    @Import(name="tattleRecordStopped")
    private @Nullable Output<Boolean> tattleRecordStopped;

    /**
     * @return Filter by whether discovery recording is stopped.
     *
     */
    public Optional<Output<Boolean>> tattleRecordStopped() {
        return Optional.ofNullable(this.tattleRecordStopped);
    }

    private GetCookieConsentConfigsArgs() {}

    private GetCookieConsentConfigsArgs(GetCookieConsentConfigsArgs $) {
        this.domains = $.domains;
        this.domainsMatch = $.domainsMatch;
        this.maxResults = $.maxResults;
        this.mode = $.mode;
        this.name = $.name;
        this.orgIds = $.orgIds;
        this.orgIdsMatch = $.orgIdsMatch;
        this.publishStatus = $.publishStatus;
        this.sortBy = $.sortBy;
        this.tattleRecordStopped = $.tattleRecordStopped;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentConfigsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentConfigsArgs $;

        public Builder() {
            $ = new GetCookieConsentConfigsArgs();
        }

        public Builder(GetCookieConsentConfigsArgs defaults) {
            $ = new GetCookieConsentConfigsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domains Filter by domains. Use Punycode for non-ASCII domains.
         *
         * @return builder
         *
         */
        public Builder domains(@Nullable Output<List<String>> domains) {
            $.domains = domains;
            return this;
        }

        /**
         * @param domains Filter by domains. Use Punycode for non-ASCII domains.
         *
         * @return builder
         *
         */
        public Builder domains(List<String> domains) {
            return domains(Output.of(domains));
        }

        /**
         * @param domains Filter by domains. Use Punycode for non-ASCII domains.
         *
         * @return builder
         *
         */
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }

        /**
         * @param domainsMatch How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
         *
         * @return builder
         *
         */
        public Builder domainsMatch(@Nullable Output<String> domainsMatch) {
            $.domainsMatch = domainsMatch;
            return this;
        }

        /**
         * @param domainsMatch How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
         *
         * @return builder
         *
         */
        public Builder domainsMatch(String domainsMatch) {
            return domainsMatch(Output.of(domainsMatch));
        }

        /**
         * @param maxResults Stop after this many configurations. Unset or 0 returns every matching configuration.
         *
         * @return builder
         *
         */
        public Builder maxResults(@Nullable Output<Integer> maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param maxResults Stop after this many configurations. Unset or 0 returns every matching configuration.
         *
         * @return builder
         *
         */
        public Builder maxResults(Integer maxResults) {
            return maxResults(Output.of(maxResults));
        }

        /**
         * @param mode Filter by compliance mode: debug, permissive, or production.
         *
         * @return builder
         *
         */
        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode Filter by compliance mode: debug, permissive, or production.
         *
         * @return builder
         *
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        /**
         * @param name Filter by configuration name (case insensitive, partial matches allowed).
         *
         * @return builder
         *
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Filter by configuration name (case insensitive, partial matches allowed).
         *
         * @return builder
         *
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param orgIds Filter by organization IDs (UUIDs).
         *
         * @return builder
         *
         */
        public Builder orgIds(@Nullable Output<List<String>> orgIds) {
            $.orgIds = orgIds;
            return this;
        }

        /**
         * @param orgIds Filter by organization IDs (UUIDs).
         *
         * @return builder
         *
         */
        public Builder orgIds(List<String> orgIds) {
            return orgIds(Output.of(orgIds));
        }

        /**
         * @param orgIds Filter by organization IDs (UUIDs).
         *
         * @return builder
         *
         */
        public Builder orgIds(String... orgIds) {
            return orgIds(List.of(orgIds));
        }

        /**
         * @param orgIdsMatch How orgIds filters: any (default), all, or not, as for domainsMatch.
         *
         * @return builder
         *
         */
        public Builder orgIdsMatch(@Nullable Output<String> orgIdsMatch) {
            $.orgIdsMatch = orgIdsMatch;
            return this;
        }

        /**
         * @param orgIdsMatch How orgIds filters: any (default), all, or not, as for domainsMatch.
         *
         * @return builder
         *
         */
        public Builder orgIdsMatch(String orgIdsMatch) {
            return orgIdsMatch(Output.of(orgIdsMatch));
        }

        /**
         * @param publishStatus Filter by publish status: unpublished, in-progress, published, outdated, or error.
         *
         * @return builder
         *
         */
        public Builder publishStatus(@Nullable Output<String> publishStatus) {
            $.publishStatus = publishStatus;
            return this;
        }

        /**
         * @param publishStatus Filter by publish status: unpublished, in-progress, published, outdated, or error.
         *
         * @return builder
         *
         */
        public Builder publishStatus(String publishStatus) {
            return publishStatus(Output.of(publishStatus));
        }

        /**
         * @param sortBy Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
         *
         * @return builder
         *
         */
        public Builder sortBy(@Nullable Output<String> sortBy) {
            $.sortBy = sortBy;
            return this;
        }

        /**
         * @param sortBy Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
         *
         * @return builder
         *
         */
        public Builder sortBy(String sortBy) {
            return sortBy(Output.of(sortBy));
        }

        /**
         * @param tattleRecordStopped Filter by whether discovery recording is stopped.
         *
         * @return builder
         *
         */
        public Builder tattleRecordStopped(@Nullable Output<Boolean> tattleRecordStopped) {
            $.tattleRecordStopped = tattleRecordStopped;
            return this;
        }

        /**
         * @param tattleRecordStopped Filter by whether discovery recording is stopped.
         *
         * @return builder
         *
         */
        public Builder tattleRecordStopped(Boolean tattleRecordStopped) {
            return tattleRecordStopped(Output.of(tattleRecordStopped));
        }

        public GetCookieConsentConfigsArgs build() {
            return $;
        }
    }

}
