// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetConsentProfileArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConsentProfileArgs Empty = new GetConsentProfileArgs();

    /**
     * The consent configuration ID the profile belongs to.
     *
     */
    @Import(name="configId", required=true)
    private Output<String> configId;

    /**
     * @return The consent configuration ID the profile belongs to.
     *
     */
    public Output<String> configId() {
        return this.configId;
    }

    /**
     * Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address, which in a pipeline is the CI runner&#39;s.
     *
     */
    @Import(name="countryCodeOverride")
    private @Nullable Output<String> countryCodeOverride;

    /**
     * @return Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address, which in a pipeline is the CI runner&#39;s.
     *
     */
    public Optional<Output<String>> countryCodeOverride() {
        return Optional.ofNullable(this.countryCodeOverride);
    }

    /**
     * The hashed subject identifier whose consent profile is returned.
     *
     */
    @Import(name="hashedSubjectId", required=true)
    private Output<String> hashedSubjectId;

    /**
     * @return The hashed subject identifier whose consent profile is returned.
     *
     */
    public Output<String> hashedSubjectId() {
        return this.hashedSubjectId;
    }

    /**
     * Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
     *
     */
    @Import(name="regionCodeOverride")
    private @Nullable Output<String> regionCodeOverride;

    /**
     * @return Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
     *
     */
    public Optional<Output<String>> regionCodeOverride() {
        return Optional.ofNullable(this.regionCodeOverride);
    }

    private GetConsentProfileArgs() {}

    private GetConsentProfileArgs(GetConsentProfileArgs $) {
        this.configId = $.configId;
        this.countryCodeOverride = $.countryCodeOverride;
        this.hashedSubjectId = $.hashedSubjectId;
        this.regionCodeOverride = $.regionCodeOverride;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConsentProfileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConsentProfileArgs $;

        public Builder() {
            $ = new GetConsentProfileArgs();
        }

        public Builder(GetConsentProfileArgs defaults) {
            $ = new GetConsentProfileArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configId The consent configuration ID the profile belongs to.
         *
         * @return builder
         *
         */
        public Builder configId(Output<String> configId) {
            $.configId = configId;
            return this;
        }

        /**
         * @param configId The consent configuration ID the profile belongs to.
         *
         * @return builder
         *
         */
        public Builder configId(String configId) {
            return configId(Output.of(configId));
        }

        /**
         * @param countryCodeOverride Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address, which in a pipeline is the CI runner&#39;s.
         *
         * @return builder
         *
         */
        public Builder countryCodeOverride(@Nullable Output<String> countryCodeOverride) {
            $.countryCodeOverride = countryCodeOverride;
            return this;
        }

        /**
         * @param countryCodeOverride Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address, which in a pipeline is the CI runner&#39;s.
         *
         * @return builder
         *
         */
        public Builder countryCodeOverride(String countryCodeOverride) {
            return countryCodeOverride(Output.of(countryCodeOverride));
        }

        /**
         * @param hashedSubjectId The hashed subject identifier whose consent profile is returned.
         *
         * @return builder
         *
         */
        public Builder hashedSubjectId(Output<String> hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        /**
         * @param hashedSubjectId The hashed subject identifier whose consent profile is returned.
         *
         * @return builder
         *
         */
        public Builder hashedSubjectId(String hashedSubjectId) {
            return hashedSubjectId(Output.of(hashedSubjectId));
        }

        /**
         * @param regionCodeOverride Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
         *
         * @return builder
         *
         */
        public Builder regionCodeOverride(@Nullable Output<String> regionCodeOverride) {
            $.regionCodeOverride = regionCodeOverride;
            return this;
        }

        /**
         * @param regionCodeOverride Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
         *
         * @return builder
         *
         */
        public Builder regionCodeOverride(String regionCodeOverride) {
            return regionCodeOverride(Output.of(regionCodeOverride));
        }

        public GetConsentProfileArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfileArgs", "configId");
            }
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("GetConsentProfileArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
