// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCollectionsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCollectionsPlainArgs Empty = new GetCollectionsPlainArgs();

    /**
     * Optional jurisdiction filter. When unset, Osano resolves the jurisdiction from the caller&#39;s IP address.
     *
     */
    @Import(name="jurisdiction")
    private @Nullable String jurisdiction;

    /**
     * @return Optional jurisdiction filter. When unset, Osano resolves the jurisdiction from the caller&#39;s IP address.
     *
     */
    public Optional<String> jurisdiction() {
        return Optional.ofNullable(this.jurisdiction);
    }

    /**
     * Optional collection type: published (default) or draft.
     *
     */
    @Import(name="type")
    private @Nullable String type;

    /**
     * @return Optional collection type: published (default) or draft.
     *
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    private GetCollectionsPlainArgs() {}

    private GetCollectionsPlainArgs(GetCollectionsPlainArgs $) {
        this.jurisdiction = $.jurisdiction;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCollectionsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCollectionsPlainArgs $;

        public Builder() {
            $ = new GetCollectionsPlainArgs();
        }

        public Builder(GetCollectionsPlainArgs defaults) {
            $ = new GetCollectionsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param jurisdiction Optional jurisdiction filter. When unset, Osano resolves the jurisdiction from the caller&#39;s IP address.
         *
         * @return builder
         *
         */
        public Builder jurisdiction(@Nullable String jurisdiction) {
            $.jurisdiction = jurisdiction;
            return this;
        }

        /**
         * @param type Optional collection type: published (default) or draft.
         *
         * @return builder
         *
         */
        public Builder type(@Nullable String type) {
            $.type = type;
            return this;
        }

        public GetCollectionsPlainArgs build() {
            return $;
        }
    }

}
