// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCookieConsentConfigPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentConfigPlainArgs Empty = new GetCookieConsentConfigPlainArgs();

    /**
     * The Osano Cookie Consent config ID (UUID) to read.
     *
     */
    @Import(name="configId", required=true)
    private String configId;

    /**
     * @return The Osano Cookie Consent config ID (UUID) to read.
     *
     */
    public String configId() {
        return this.configId;
    }

    private GetCookieConsentConfigPlainArgs() {}

    private GetCookieConsentConfigPlainArgs(GetCookieConsentConfigPlainArgs $) {
        this.configId = $.configId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentConfigPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentConfigPlainArgs $;

        public Builder() {
            $ = new GetCookieConsentConfigPlainArgs();
        }

        public Builder(GetCookieConsentConfigPlainArgs defaults) {
            $ = new GetCookieConsentConfigPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configId The Osano Cookie Consent config ID (UUID) to read.
         *
         * @return builder
         *
         */
        public Builder configId(String configId) {
            $.configId = configId;
            return this;
        }

        public GetCookieConsentConfigPlainArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetCookieConsentConfigPlainArgs", "configId");
            }
            return $;
        }
    }

}
