// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentConfigsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentConfigsPlainArgs Empty = new GetCookieConsentConfigsPlainArgs();

    /**
     * Filter by domains. Use Punycode for non-ASCII domains.
     *
     */
    @Import(name="domains")
    private @Nullable List<String> domains;

    /**
     * @return Filter by domains. Use Punycode for non-ASCII domains.
     *
     */
    public Optional<List<String>> domains() {
        return Optional.ofNullable(this.domains);
    }

    /**
     * How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
     *
     */
    @Import(name="domainsMatch")
    private @Nullable String domainsMatch;

    /**
     * @return How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
     *
     */
    public Optional<String> domainsMatch() {
        return Optional.ofNullable(this.domainsMatch);
    }

    /**
     * Stop after this many configurations. Unset or 0 returns every matching configuration.
     *
     */
    @Import(name="maxResults")
    private @Nullable Integer maxResults;

    /**
     * @return Stop after this many configurations. Unset or 0 returns every matching configuration.
     *
     */
    public Optional<Integer> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Filter by compliance mode: debug, permissive, or production.
     *
     */
    @Import(name="mode")
    private @Nullable String mode;

    /**
     * @return Filter by compliance mode: debug, permissive, or production.
     *
     */
    public Optional<String> mode() {
        return Optional.ofNullable(this.mode);
    }

    /**
     * Filter by configuration name (case insensitive, partial matches allowed).
     *
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return Filter by configuration name (case insensitive, partial matches allowed).
     *
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Filter by organization IDs (UUIDs).
     *
     */
    @Import(name="orgIds")
    private @Nullable List<String> orgIds;

    /**
     * @return Filter by organization IDs (UUIDs).
     *
     */
    public Optional<List<String>> orgIds() {
        return Optional.ofNullable(this.orgIds);
    }

    /**
     * How orgIds filters: any (default), all, or not, as for domainsMatch.
     *
     */
    @Import(name="orgIdsMatch")
    private @Nullable String orgIdsMatch;

    /**
     * @return How orgIds filters: any (default), all, or not, as for domainsMatch.
     *
     */
    public Optional<String> orgIdsMatch() {
        return Optional.ofNullable(this.orgIdsMatch);
    }

    /**
     * Filter by publish status: unpublished, in-progress, published, outdated, or error.
     *
     */
    @Import(name="publishStatus")
    private @Nullable String publishStatus;

    /**
     * @return Filter by publish status: unpublished, in-progress, published, outdated, or error.
     *
     */
    public Optional<String> publishStatus() {
        return Optional.ofNullable(this.publishStatus);
    }

    /**
     * Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
     *
     */
    @Import(name="sortBy")
    private @Nullable String sortBy;

    /**
     * @return Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
     *
     */
    public Optional<String> sortBy() {
        return Optional.ofNullable(this.sortBy);
    }

    /**
     * Filter by whether discovery recording is stopped.
     *
     */
    @Import(name="tattleRecordStopped")
    private @Nullable Boolean tattleRecordStopped;

    /**
     * @return Filter by whether discovery recording is stopped.
     *
     */
    public Optional<Boolean> tattleRecordStopped() {
        return Optional.ofNullable(this.tattleRecordStopped);
    }

    private GetCookieConsentConfigsPlainArgs() {}

    private GetCookieConsentConfigsPlainArgs(GetCookieConsentConfigsPlainArgs $) {
        this.domains = $.domains;
        this.domainsMatch = $.domainsMatch;
        this.maxResults = $.maxResults;
        this.mode = $.mode;
        this.name = $.name;
        this.orgIds = $.orgIds;
        this.orgIdsMatch = $.orgIdsMatch;
        this.publishStatus = $.publishStatus;
        this.sortBy = $.sortBy;
        this.tattleRecordStopped = $.tattleRecordStopped;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentConfigsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentConfigsPlainArgs $;

        public Builder() {
            $ = new GetCookieConsentConfigsPlainArgs();
        }

        public Builder(GetCookieConsentConfigsPlainArgs defaults) {
            $ = new GetCookieConsentConfigsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domains Filter by domains. Use Punycode for non-ASCII domains.
         *
         * @return builder
         *
         */
        public Builder domains(@Nullable List<String> domains) {
            $.domains = domains;
            return this;
        }

        /**
         * @param domains Filter by domains. Use Punycode for non-ASCII domains.
         *
         * @return builder
         *
         */
        public Builder domains(String... domains) {
            return domains(List.of(domains));
        }

        /**
         * @param domainsMatch How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
         *
         * @return builder
         *
         */
        public Builder domainsMatch(@Nullable String domainsMatch) {
            $.domainsMatch = domainsMatch;
            return this;
        }

        /**
         * @param maxResults Stop after this many configurations. Unset or 0 returns every matching configuration.
         *
         * @return builder
         *
         */
        public Builder maxResults(@Nullable Integer maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param mode Filter by compliance mode: debug, permissive, or production.
         *
         * @return builder
         *
         */
        public Builder mode(@Nullable String mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param name Filter by configuration name (case insensitive, partial matches allowed).
         *
         * @return builder
         *
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        /**
         * @param orgIds Filter by organization IDs (UUIDs).
         *
         * @return builder
         *
         */
        public Builder orgIds(@Nullable List<String> orgIds) {
            $.orgIds = orgIds;
            return this;
        }

        /**
         * @param orgIds Filter by organization IDs (UUIDs).
         *
         * @return builder
         *
         */
        public Builder orgIds(String... orgIds) {
            return orgIds(List.of(orgIds));
        }

        /**
         * @param orgIdsMatch How orgIds filters: any (default), all, or not, as for domainsMatch.
         *
         * @return builder
         *
         */
        public Builder orgIdsMatch(@Nullable String orgIdsMatch) {
            $.orgIdsMatch = orgIdsMatch;
            return this;
        }

        /**
         * @param publishStatus Filter by publish status: unpublished, in-progress, published, outdated, or error.
         *
         * @return builder
         *
         */
        public Builder publishStatus(@Nullable String publishStatus) {
            $.publishStatus = publishStatus;
            return this;
        }

        /**
         * @param sortBy Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
         *
         * @return builder
         *
         */
        public Builder sortBy(@Nullable String sortBy) {
            $.sortBy = sortBy;
            return this;
        }

        /**
         * @param tattleRecordStopped Filter by whether discovery recording is stopped.
         *
         * @return builder
         *
         */
        public Builder tattleRecordStopped(@Nullable Boolean tattleRecordStopped) {
            $.tattleRecordStopped = tattleRecordStopped;
            return this;
        }

        public GetCookieConsentConfigsPlainArgs build() {
            return $;
        }
    }

}
