// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSubjectArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSubjectArgs Empty = new GetSubjectArgs();

    @Import(name="referenceType")
    private @Nullable Output<String> referenceType;

    public Optional<Output<String>> referenceType() {
        return Optional.ofNullable(this.referenceType);
    }

    @Import(name="subjectRef", required=true)
    private Output<String> subjectRef;

    public Output<String> subjectRef() {
        return this.subjectRef;
    }

    private GetSubjectArgs() {}

    private GetSubjectArgs(GetSubjectArgs $) {
        this.referenceType = $.referenceType;
        this.subjectRef = $.subjectRef;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSubjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSubjectArgs $;

        public Builder() {
            $ = new GetSubjectArgs();
        }

        public Builder(GetSubjectArgs defaults) {
            $ = new GetSubjectArgs(Objects.requireNonNull(defaults));
        }

        public Builder referenceType(@Nullable Output<String> referenceType) {
            $.referenceType = referenceType;
            return this;
        }

        public Builder referenceType(String referenceType) {
            return referenceType(Output.of(referenceType));
        }

        public Builder subjectRef(Output<String> subjectRef) {
            $.subjectRef = subjectRef;
            return this;
        }

        public Builder subjectRef(String subjectRef) {
            return subjectRef(Output.of(subjectRef));
        }

        public GetSubjectArgs build() {
            if ($.subjectRef == null) {
                throw new MissingRequiredPropertyException("GetSubjectArgs", "subjectRef");
            }
            return $;
        }
    }

}
