// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetUnifiedConsentArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUnifiedConsentArgs Empty = new GetUnifiedConsentArgs();

    @Import(name="referenceType")
    private @Nullable Output<String> referenceType;

    public Optional<Output<String>> referenceType() {
        return Optional.ofNullable(this.referenceType);
    }

    @Import(name="subjectRef", required=true)
    private Output<String> subjectRef;

    public Output<String> subjectRef() {
        return this.subjectRef;
    }

    private GetUnifiedConsentArgs() {}

    private GetUnifiedConsentArgs(GetUnifiedConsentArgs $) {
        this.referenceType = $.referenceType;
        this.subjectRef = $.subjectRef;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUnifiedConsentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUnifiedConsentArgs $;

        public Builder() {
            $ = new GetUnifiedConsentArgs();
        }

        public Builder(GetUnifiedConsentArgs defaults) {
            $ = new GetUnifiedConsentArgs(Objects.requireNonNull(defaults));
        }

        public Builder referenceType(@Nullable Output<String> referenceType) {
            $.referenceType = referenceType;
            return this;
        }

        public Builder referenceType(String referenceType) {
            return referenceType(Output.of(referenceType));
        }

        public Builder subjectRef(Output<String> subjectRef) {
            $.subjectRef = subjectRef;
            return this;
        }

        public Builder subjectRef(String subjectRef) {
            return subjectRef(Output.of(subjectRef));
        }

        public GetUnifiedConsentArgs build() {
            if ($.subjectRef == null) {
                throw new MissingRequiredPropertyException("GetUnifiedConsentArgs", "subjectRef");
            }
            return $;
        }
    }

}
