// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SendSubjectCodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final SendSubjectCodePlainArgs Empty = new SendSubjectCodePlainArgs();

    @Import(name="email")
    private @Nullable String email;

    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="hashedSubjectId", required=true)
    private String hashedSubjectId;

    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }

    @Import(name="phone")
    private @Nullable String phone;

    public Optional<String> phone() {
        return Optional.ofNullable(this.phone);
    }

    private SendSubjectCodePlainArgs() {}

    private SendSubjectCodePlainArgs(SendSubjectCodePlainArgs $) {
        this.email = $.email;
        this.hashedSubjectId = $.hashedSubjectId;
        this.phone = $.phone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SendSubjectCodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SendSubjectCodePlainArgs $;

        public Builder() {
            $ = new SendSubjectCodePlainArgs();
        }

        public Builder(SendSubjectCodePlainArgs defaults) {
            $ = new SendSubjectCodePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(@Nullable String email) {
            $.email = email;
            return this;
        }

        public Builder hashedSubjectId(String hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        public Builder phone(@Nullable String phone) {
            $.phone = phone;
            return this;
        }

        public SendSubjectCodePlainArgs build() {
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("SendSubjectCodePlainArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
