// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SendSubjectCodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final SendSubjectCodePlainArgs Empty = new SendSubjectCodePlainArgs();

    /**
     * Email address to send the code to. Set exactly one of email or phone.
     *
     */
    @Import(name="email")
    private @Nullable String email;

    /**
     * @return Email address to send the code to. Set exactly one of email or phone.
     *
     */
    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * Optional hashed subject identifier, sent only when set. Osano&#39;s current API identifies the subject by email or phone.
     *
     */
    @Import(name="hashedSubjectId")
    private @Nullable String hashedSubjectId;

    /**
     * @return Optional hashed subject identifier, sent only when set. Osano&#39;s current API identifies the subject by email or phone.
     *
     */
    public Optional<String> hashedSubjectId() {
        return Optional.ofNullable(this.hashedSubjectId);
    }

    /**
     * Phone number to send the code to by SMS. Set exactly one of email or phone.
     *
     */
    @Import(name="phone")
    private @Nullable String phone;

    /**
     * @return Phone number to send the code to by SMS. Set exactly one of email or phone.
     *
     */
    public Optional<String> phone() {
        return Optional.ofNullable(this.phone);
    }

    private SendSubjectCodePlainArgs() {}

    private SendSubjectCodePlainArgs(SendSubjectCodePlainArgs $) {
        this.email = $.email;
        this.hashedSubjectId = $.hashedSubjectId;
        this.phone = $.phone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SendSubjectCodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SendSubjectCodePlainArgs $;

        public Builder() {
            $ = new SendSubjectCodePlainArgs();
        }

        public Builder(SendSubjectCodePlainArgs defaults) {
            $ = new SendSubjectCodePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param email Email address to send the code to. Set exactly one of email or phone.
         *
         * @return builder
         *
         */
        public Builder email(@Nullable String email) {
            $.email = email;
            return this;
        }

        /**
         * @param hashedSubjectId Optional hashed subject identifier, sent only when set. Osano&#39;s current API identifies the subject by email or phone.
         *
         * @return builder
         *
         */
        public Builder hashedSubjectId(@Nullable String hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        /**
         * @param phone Phone number to send the code to by SMS. Set exactly one of email or phone.
         *
         * @return builder
         *
         */
        public Builder phone(@Nullable String phone) {
            $.phone = phone;
            return this;
        }

        public SendSubjectCodePlainArgs build() {
            return $;
        }
    }

}
