// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VerifySubjectCodePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final VerifySubjectCodePlainArgs Empty = new VerifySubjectCodePlainArgs();

    /**
     * The one-time verification code the subject received.
     *
     */
    @Import(name="code", required=true)
    private String code;

    /**
     * @return The one-time verification code the subject received.
     *
     */
    public String code() {
        return this.code;
    }

    /**
     * Email address the code was sent to. Set exactly one of email or phone.
     *
     */
    @Import(name="email")
    private @Nullable String email;

    /**
     * @return Email address the code was sent to. Set exactly one of email or phone.
     *
     */
    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * The hashed subject identifier being verified.
     *
     */
    @Import(name="hashedSubjectId", required=true)
    private String hashedSubjectId;

    /**
     * @return The hashed subject identifier being verified.
     *
     */
    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }

    /**
     * Phone number the code was sent to. Set exactly one of email or phone.
     *
     */
    @Import(name="phone")
    private @Nullable String phone;

    /**
     * @return Phone number the code was sent to. Set exactly one of email or phone.
     *
     */
    public Optional<String> phone() {
        return Optional.ofNullable(this.phone);
    }

    private VerifySubjectCodePlainArgs() {}

    private VerifySubjectCodePlainArgs(VerifySubjectCodePlainArgs $) {
        this.code = $.code;
        this.email = $.email;
        this.hashedSubjectId = $.hashedSubjectId;
        this.phone = $.phone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VerifySubjectCodePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VerifySubjectCodePlainArgs $;

        public Builder() {
            $ = new VerifySubjectCodePlainArgs();
        }

        public Builder(VerifySubjectCodePlainArgs defaults) {
            $ = new VerifySubjectCodePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param code The one-time verification code the subject received.
         *
         * @return builder
         *
         */
        public Builder code(String code) {
            $.code = code;
            return this;
        }

        /**
         * @param email Email address the code was sent to. Set exactly one of email or phone.
         *
         * @return builder
         *
         */
        public Builder email(@Nullable String email) {
            $.email = email;
            return this;
        }

        /**
         * @param hashedSubjectId The hashed subject identifier being verified.
         *
         * @return builder
         *
         */
        public Builder hashedSubjectId(String hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        /**
         * @param phone Phone number the code was sent to. Set exactly one of email or phone.
         *
         * @return builder
         *
         */
        public Builder phone(@Nullable String phone) {
            $.phone = phone;
            return this;
        }

        public VerifySubjectCodePlainArgs build() {
            if ($.code == null) {
                throw new MissingRequiredPropertyException("VerifySubjectCodePlainArgs", "code");
            }
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("VerifySubjectCodePlainArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
