// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VerifySubjectCodeArgs extends com.pulumi.resources.InvokeArgs {

    public static final VerifySubjectCodeArgs Empty = new VerifySubjectCodeArgs();

    @Import(name="code", required=true)
    private Output<String> code;

    public Output<String> code() {
        return this.code;
    }

    @Import(name="email")
    private @Nullable Output<String> email;

    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="hashedSubjectId", required=true)
    private Output<String> hashedSubjectId;

    public Output<String> hashedSubjectId() {
        return this.hashedSubjectId;
    }

    @Import(name="phone")
    private @Nullable Output<String> phone;

    public Optional<Output<String>> phone() {
        return Optional.ofNullable(this.phone);
    }

    private VerifySubjectCodeArgs() {}

    private VerifySubjectCodeArgs(VerifySubjectCodeArgs $) {
        this.code = $.code;
        this.email = $.email;
        this.hashedSubjectId = $.hashedSubjectId;
        this.phone = $.phone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VerifySubjectCodeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VerifySubjectCodeArgs $;

        public Builder() {
            $ = new VerifySubjectCodeArgs();
        }

        public Builder(VerifySubjectCodeArgs defaults) {
            $ = new VerifySubjectCodeArgs(Objects.requireNonNull(defaults));
        }

        public Builder code(Output<String> code) {
            $.code = code;
            return this;
        }

        public Builder code(String code) {
            return code(Output.of(code));
        }

        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder hashedSubjectId(Output<String> hashedSubjectId) {
            $.hashedSubjectId = hashedSubjectId;
            return this;
        }

        public Builder hashedSubjectId(String hashedSubjectId) {
            return hashedSubjectId(Output.of(hashedSubjectId));
        }

        public Builder phone(@Nullable Output<String> phone) {
            $.phone = phone;
            return this;
        }

        public Builder phone(String phone) {
            return phone(Output.of(phone));
        }

        public VerifySubjectCodeArgs build() {
            if ($.code == null) {
                throw new MissingRequiredPropertyException("VerifySubjectCodeArgs", "code");
            }
            if ($.hashedSubjectId == null) {
                throw new MissingRequiredPropertyException("VerifySubjectCodeArgs", "hashedSubjectId");
            }
            return $;
        }
    }

}
