# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .check_consent import *
from .consent import *
from .cookie_consent_config import *
from .cookie_consent_publication import *
from .cookie_consent_rule import *
from .get_collection import *
from .get_collections import *
from .get_config import *
from .get_consent_profile import *
from .get_subject import *
from .get_unified_consent import *
from .provider import *
from .send_subject_code import *
from .verify_subject_code import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_osano.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_osano.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "osano",
  "mod": "index",
  "fqn": "pulumi_osano",
  "classes": {
   "osano:index:Consent": "Consent",
   "osano:index:CookieConsentConfig": "CookieConsentConfig",
   "osano:index:CookieConsentPublication": "CookieConsentPublication",
   "osano:index:CookieConsentRule": "CookieConsentRule"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "osano",
  "token": "pulumi:providers:osano",
  "fqn": "pulumi_osano",
  "class": "Provider"
 }
]
"""
)
