# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ConsentArgs', 'Consent']

@pulumi.input_type
class ConsentArgs:
    def __init__(__self__, *,
                 actions: pulumi.Input[Sequence[pulumi.Input['ConsentActionArgs']]],
                 subject: pulumi.Input['ConsentSubjectArgs'],
                 attributes: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 compliance: Optional[pulumi.Input['ConsentComplianceArgs']] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Consent resource.
        :param pulumi.Input[Sequence[pulumi.Input['ConsentActionArgs']]] actions: Consent actions referencing privacy protocols (target) within a configuration (vendor).
        :param pulumi.Input['ConsentSubjectArgs'] subject: Subject identifiers used for the consent (verifiedId or anonymousId).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] attributes: Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
        :param pulumi.Input[_builtins.str] jurisdiction: Optional jurisdiction override matching one of the configuration's jurisdictions.
        :param pulumi.Input[_builtins.str] origin: Origin metadata for the consent, typically 'api' or 'gpc'.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Custom tags that Osano associates with the consent record.
        """
        pulumi.set(__self__, "actions", actions)
        pulumi.set(__self__, "subject", subject)
        if attributes is not None:
            pulumi.set(__self__, "attributes", attributes)
        if compliance is not None:
            pulumi.set(__self__, "compliance", compliance)
        if jurisdiction is not None:
            pulumi.set(__self__, "jurisdiction", jurisdiction)
        if origin is not None:
            pulumi.set(__self__, "origin", origin)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> pulumi.Input[Sequence[pulumi.Input['ConsentActionArgs']]]:
        """
        Consent actions referencing privacy protocols (target) within a configuration (vendor).
        """
        return pulumi.get(self, "actions")

    @actions.setter
    def actions(self, value: pulumi.Input[Sequence[pulumi.Input['ConsentActionArgs']]]):
        pulumi.set(self, "actions", value)

    @_builtins.property
    @pulumi.getter
    def subject(self) -> pulumi.Input['ConsentSubjectArgs']:
        """
        Subject identifiers used for the consent (verifiedId or anonymousId).
        """
        return pulumi.get(self, "subject")

    @subject.setter
    def subject(self, value: pulumi.Input['ConsentSubjectArgs']):
        pulumi.set(self, "subject", value)

    @_builtins.property
    @pulumi.getter
    def attributes(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
        """
        return pulumi.get(self, "attributes")

    @attributes.setter
    def attributes(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "attributes", value)

    @_builtins.property
    @pulumi.getter
    def compliance(self) -> Optional[pulumi.Input['ConsentComplianceArgs']]:
        return pulumi.get(self, "compliance")

    @compliance.setter
    def compliance(self, value: Optional[pulumi.Input['ConsentComplianceArgs']]):
        pulumi.set(self, "compliance", value)

    @_builtins.property
    @pulumi.getter
    def jurisdiction(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional jurisdiction override matching one of the configuration's jurisdictions.
        """
        return pulumi.get(self, "jurisdiction")

    @jurisdiction.setter
    def jurisdiction(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jurisdiction", value)

    @_builtins.property
    @pulumi.getter
    def origin(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Origin metadata for the consent, typically 'api' or 'gpc'.
        """
        return pulumi.get(self, "origin")

    @origin.setter
    def origin(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "origin", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Custom tags that Osano associates with the consent record.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("osano:index:Consent")
class Consent(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ConsentActionArgs', 'ConsentActionArgsDict']]]]] = None,
                 attributes: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 compliance: Optional[pulumi.Input[Union['ConsentComplianceArgs', 'ConsentComplianceArgsDict']]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[Union['ConsentSubjectArgs', 'ConsentSubjectArgsDict']]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Creates unified consent decisions within Osano for a given subject.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ConsentActionArgs', 'ConsentActionArgsDict']]]] actions: Consent actions referencing privacy protocols (target) within a configuration (vendor).
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] attributes: Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
        :param pulumi.Input[_builtins.str] jurisdiction: Optional jurisdiction override matching one of the configuration's jurisdictions.
        :param pulumi.Input[_builtins.str] origin: Origin metadata for the consent, typically 'api' or 'gpc'.
        :param pulumi.Input[Union['ConsentSubjectArgs', 'ConsentSubjectArgsDict']] subject: Subject identifiers used for the consent (verifiedId or anonymousId).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Custom tags that Osano associates with the consent record.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConsentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates unified consent decisions within Osano for a given subject.

        :param str resource_name: The name of the resource.
        :param ConsentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConsentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ConsentActionArgs', 'ConsentActionArgsDict']]]]] = None,
                 attributes: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 compliance: Optional[pulumi.Input[Union['ConsentComplianceArgs', 'ConsentComplianceArgsDict']]] = None,
                 jurisdiction: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[Union['ConsentSubjectArgs', 'ConsentSubjectArgsDict']]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConsentArgs.__new__(ConsentArgs)

            if actions is None and not opts.urn:
                raise TypeError("Missing required property 'actions'")
            __props__.__dict__["actions"] = actions
            __props__.__dict__["attributes"] = attributes
            __props__.__dict__["compliance"] = compliance
            __props__.__dict__["jurisdiction"] = jurisdiction
            __props__.__dict__["origin"] = origin
            if subject is None and not opts.urn:
                raise TypeError("Missing required property 'subject'")
            __props__.__dict__["subject"] = subject
            __props__.__dict__["tags"] = tags
            __props__.__dict__["consent_id"] = None
            __props__.__dict__["last_synced"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["actions[*]", "attributes.*", "compliance", "jurisdiction", "origin", "subject", "tags[*]"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Consent, __self__).__init__(
            'osano:index:Consent',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Consent':
        """
        Get an existing Consent resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ConsentArgs.__new__(ConsentArgs)

        __props__.__dict__["actions"] = None
        __props__.__dict__["attributes"] = None
        __props__.__dict__["compliance"] = None
        __props__.__dict__["consent_id"] = None
        __props__.__dict__["jurisdiction"] = None
        __props__.__dict__["last_synced"] = None
        __props__.__dict__["origin"] = None
        __props__.__dict__["subject"] = None
        __props__.__dict__["tags"] = None
        return Consent(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> pulumi.Output[Sequence['outputs.ConsentAction']]:
        """
        Consent actions referencing privacy protocols (target) within a configuration (vendor).
        """
        return pulumi.get(self, "actions")

    @_builtins.property
    @pulumi.getter
    def attributes(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
        """
        return pulumi.get(self, "attributes")

    @_builtins.property
    @pulumi.getter
    def compliance(self) -> pulumi.Output[Optional['outputs.ConsentCompliance']]:
        return pulumi.get(self, "compliance")

    @_builtins.property
    @pulumi.getter(name="consentId")
    def consent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Synthetic identifier used by Pulumi to track consent submissions.
        """
        return pulumi.get(self, "consent_id")

    @_builtins.property
    @pulumi.getter
    def jurisdiction(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional jurisdiction override matching one of the configuration's jurisdictions.
        """
        return pulumi.get(self, "jurisdiction")

    @_builtins.property
    @pulumi.getter(name="lastSynced")
    def last_synced(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of the last refresh from the Osano API (RFC3339).
        """
        return pulumi.get(self, "last_synced")

    @_builtins.property
    @pulumi.getter
    def origin(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Origin metadata for the consent, typically 'api' or 'gpc'.
        """
        return pulumi.get(self, "origin")

    @_builtins.property
    @pulumi.getter
    def subject(self) -> pulumi.Output['outputs.ConsentSubject']:
        """
        Subject identifiers used for the consent (verifiedId or anonymousId).
        """
        return pulumi.get(self, "subject")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Custom tags that Osano associates with the consent record.
        """
        return pulumi.get(self, "tags")
