# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CookieConsentPublicationArgs', 'CookieConsentPublication']

@pulumi.input_type
class CookieConsentPublicationArgs:
    def __init__(__self__, *,
                 change_token: pulumi.Input[_builtins.str],
                 config_id: pulumi.Input[_builtins.str],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 keep_unclassified_tattles: Optional[pulumi.Input[_builtins.bool]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a CookieConsentPublication resource.
        :param pulumi.Input[_builtins.str] change_token: A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
        :param pulumi.Input[_builtins.str] config_id: The Osano Cookie Consent config ID to publish. This is also the import ID.
        :param pulumi.Input[_builtins.str] description: Optional description sent with the publication request.
        :param pulumi.Input[_builtins.bool] keep_unclassified_tattles: Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
        :param pulumi.Input[_builtins.str] webhook_url: Optional absolute HTTP or HTTPS URL notified by Osano after publication.
        """
        pulumi.set(__self__, "change_token", change_token)
        pulumi.set(__self__, "config_id", config_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if keep_unclassified_tattles is None:
            keep_unclassified_tattles = True
        if keep_unclassified_tattles is not None:
            pulumi.set(__self__, "keep_unclassified_tattles", keep_unclassified_tattles)
        if webhook_url is not None:
            pulumi.set(__self__, "webhook_url", webhook_url)

    @_builtins.property
    @pulumi.getter(name="changeToken")
    def change_token(self) -> pulumi.Input[_builtins.str]:
        """
        A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
        """
        return pulumi.get(self, "change_token")

    @change_token.setter
    def change_token(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "change_token", value)

    @_builtins.property
    @pulumi.getter(name="configId")
    def config_id(self) -> pulumi.Input[_builtins.str]:
        """
        The Osano Cookie Consent config ID to publish. This is also the import ID.
        """
        return pulumi.get(self, "config_id")

    @config_id.setter
    def config_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "config_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional description sent with the publication request.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="keepUnclassifiedTattles")
    def keep_unclassified_tattles(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
        """
        return pulumi.get(self, "keep_unclassified_tattles")

    @keep_unclassified_tattles.setter
    def keep_unclassified_tattles(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "keep_unclassified_tattles", value)

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional absolute HTTP or HTTPS URL notified by Osano after publication.
        """
        return pulumi.get(self, "webhook_url")

    @webhook_url.setter
    def webhook_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "webhook_url", value)


@pulumi.type_token("osano:index:CookieConsentPublication")
class CookieConsentPublication(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 change_token: Optional[pulumi.Input[_builtins.str]] = None,
                 config_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 keep_unclassified_tattles: Optional[pulumi.Input[_builtins.bool]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Publishes an Osano Cookie Consent configuration, waits for completion, and returns its hosted CMP script. Import with the Osano config ID; deleting this resource only removes Pulumi state and does not unpublish the config.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] change_token: A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
        :param pulumi.Input[_builtins.str] config_id: The Osano Cookie Consent config ID to publish. This is also the import ID.
        :param pulumi.Input[_builtins.str] description: Optional description sent with the publication request.
        :param pulumi.Input[_builtins.bool] keep_unclassified_tattles: Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
        :param pulumi.Input[_builtins.str] webhook_url: Optional absolute HTTP or HTTPS URL notified by Osano after publication.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CookieConsentPublicationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Publishes an Osano Cookie Consent configuration, waits for completion, and returns its hosted CMP script. Import with the Osano config ID; deleting this resource only removes Pulumi state and does not unpublish the config.

        :param str resource_name: The name of the resource.
        :param CookieConsentPublicationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CookieConsentPublicationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 change_token: Optional[pulumi.Input[_builtins.str]] = None,
                 config_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 keep_unclassified_tattles: Optional[pulumi.Input[_builtins.bool]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CookieConsentPublicationArgs.__new__(CookieConsentPublicationArgs)

            if change_token is None and not opts.urn:
                raise TypeError("Missing required property 'change_token'")
            __props__.__dict__["change_token"] = change_token
            if config_id is None and not opts.urn:
                raise TypeError("Missing required property 'config_id'")
            __props__.__dict__["config_id"] = config_id
            __props__.__dict__["description"] = description
            if keep_unclassified_tattles is None:
                keep_unclassified_tattles = True
            __props__.__dict__["keep_unclassified_tattles"] = keep_unclassified_tattles
            __props__.__dict__["webhook_url"] = webhook_url
            __props__.__dict__["customer_id"] = None
            __props__.__dict__["last_published"] = None
            __props__.__dict__["publish_status"] = None
            __props__.__dict__["published_revision"] = None
            __props__.__dict__["script_src"] = None
            __props__.__dict__["script_tag"] = None
        super(CookieConsentPublication, __self__).__init__(
            'osano:index:CookieConsentPublication',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'CookieConsentPublication':
        """
        Get an existing CookieConsentPublication resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = CookieConsentPublicationArgs.__new__(CookieConsentPublicationArgs)

        __props__.__dict__["change_token"] = None
        __props__.__dict__["config_id"] = None
        __props__.__dict__["customer_id"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["keep_unclassified_tattles"] = None
        __props__.__dict__["last_published"] = None
        __props__.__dict__["publish_status"] = None
        __props__.__dict__["published_revision"] = None
        __props__.__dict__["script_src"] = None
        __props__.__dict__["script_tag"] = None
        __props__.__dict__["webhook_url"] = None
        return CookieConsentPublication(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="changeToken")
    def change_token(self) -> pulumi.Output[_builtins.str]:
        """
        A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
        """
        return pulumi.get(self, "change_token")

    @_builtins.property
    @pulumi.getter(name="configId")
    def config_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Osano Cookie Consent config ID to publish. This is also the import ID.
        """
        return pulumi.get(self, "config_id")

    @_builtins.property
    @pulumi.getter(name="customerId")
    def customer_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Osano customer ID that owns the published configuration.
        """
        return pulumi.get(self, "customer_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional description sent with the publication request.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="keepUnclassifiedTattles")
    def keep_unclassified_tattles(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
        """
        return pulumi.get(self, "keep_unclassified_tattles")

    @_builtins.property
    @pulumi.getter(name="lastPublished")
    def last_published(self) -> pulumi.Output[_builtins.int]:
        """
        Unix timestamp of the completed Osano publication.
        """
        return pulumi.get(self, "last_published")

    @_builtins.property
    @pulumi.getter(name="publishStatus")
    def publish_status(self) -> pulumi.Output[_builtins.str]:
        """
        The publication status returned by Osano after completion.
        """
        return pulumi.get(self, "publish_status")

    @_builtins.property
    @pulumi.getter(name="publishedRevision")
    def published_revision(self) -> pulumi.Output[_builtins.int]:
        """
        The configuration revision most recently published by Osano.
        """
        return pulumi.get(self, "published_revision")

    @_builtins.property
    @pulumi.getter(name="scriptSrc")
    def script_src(self) -> pulumi.Output[_builtins.str]:
        """
        The public hosted Osano CMP JavaScript URL for this customer and config.
        """
        return pulumi.get(self, "script_src")

    @_builtins.property
    @pulumi.getter(name="scriptTag")
    def script_tag(self) -> pulumi.Output[_builtins.str]:
        """
        The complete public CMP script tag to place first in the site head, without async or defer attributes.
        """
        return pulumi.get(self, "script_tag")

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional absolute HTTP or HTTPS URL notified by Osano after publication.
        """
        return pulumi.get(self, "webhook_url")
