# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCookieConsentDiscoveriesResult',
    'AwaitableGetCookieConsentDiscoveriesResult',
    'get_cookie_consent_discoveries',
    'get_cookie_consent_discoveries_output',
]

@pulumi.output_type
class GetCookieConsentDiscoveriesResult:
    def __init__(__self__, config_id=None, discoveries=None, store_type=None):
        if config_id and not isinstance(config_id, str):
            raise TypeError("Expected argument 'config_id' to be a str")
        pulumi.set(__self__, "config_id", config_id)
        if discoveries and not isinstance(discoveries, list):
            raise TypeError("Expected argument 'discoveries' to be a list")
        pulumi.set(__self__, "discoveries", discoveries)
        if store_type and not isinstance(store_type, str):
            raise TypeError("Expected argument 'store_type' to be a str")
        pulumi.set(__self__, "store_type", store_type)

    @_builtins.property
    @pulumi.getter(name="configId")
    def config_id(self) -> _builtins.str:
        """
        The config ID that was queried.
        """
        return pulumi.get(self, "config_id")

    @_builtins.property
    @pulumi.getter
    def discoveries(self) -> Sequence['outputs.CookieConsentDiscovery']:
        """
        The discoveries Osano reports for the configuration and storage type.
        """
        return pulumi.get(self, "discoveries")

    @_builtins.property
    @pulumi.getter(name="storeType")
    def store_type(self) -> _builtins.str:
        """
        The storage type that was listed.
        """
        return pulumi.get(self, "store_type")


class AwaitableGetCookieConsentDiscoveriesResult(GetCookieConsentDiscoveriesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCookieConsentDiscoveriesResult(
            config_id=self.config_id,
            discoveries=self.discoveries,
            store_type=self.store_type)


def get_cookie_consent_discoveries(config_id: Optional[_builtins.str] = None,
                                   store_type: Optional[_builtins.str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCookieConsentDiscoveriesResult:
    """
    Lists the cookies, scripts, iframes, or localStorage keys that osano.js or URL scans discovered for a configuration. Use it to review what still needs a rule before switching a configuration to production mode, which blocks everything unclassified.

    :param _builtins.str config_id: The Osano Cookie Consent config ID whose discoveries are listed.
    :param _builtins.str store_type: The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
    """
    __args__ = dict()
    __args__['configId'] = config_id
    __args__['storeType'] = store_type
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('osano:index:getCookieConsentDiscoveries', __args__, opts=opts, typ=GetCookieConsentDiscoveriesResult).value

    return AwaitableGetCookieConsentDiscoveriesResult(
        config_id=pulumi.get(__ret__, 'config_id'),
        discoveries=pulumi.get(__ret__, 'discoveries'),
        store_type=pulumi.get(__ret__, 'store_type'))
def get_cookie_consent_discoveries_output(config_id: pulumi.Input[Optional[_builtins.str]] = None,
                                          store_type: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCookieConsentDiscoveriesResult]:
    """
    Lists the cookies, scripts, iframes, or localStorage keys that osano.js or URL scans discovered for a configuration. Use it to review what still needs a rule before switching a configuration to production mode, which blocks everything unclassified.

    :param _builtins.str config_id: The Osano Cookie Consent config ID whose discoveries are listed.
    :param _builtins.str store_type: The storage type to list: cookies (default, as in the Osano API), scripts, iframes, or localStorage.
    """
    __args__ = dict()
    __args__['configId'] = config_id
    __args__['storeType'] = store_type
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('osano:index:getCookieConsentDiscoveries', __args__, opts=opts, typ=GetCookieConsentDiscoveriesResult)
    return __ret__.apply(lambda __response__: GetCookieConsentDiscoveriesResult(
        config_id=pulumi.get(__response__, 'config_id'),
        discoveries=pulumi.get(__response__, 'discoveries'),
        store_type=pulumi.get(__response__, 'store_type')))
