# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSessionResult',
    'AwaitableGetSessionResult',
    'get_session',
    'get_session_output',
]

@pulumi.output_type
class GetSessionResult:
    def __init__(__self__, exists=None, profile=None, verified_id=None):
        if exists and not isinstance(exists, bool):
            raise TypeError("Expected argument 'exists' to be a bool")
        pulumi.set(__self__, "exists", exists)
        if profile and not isinstance(profile, dict):
            raise TypeError("Expected argument 'profile' to be a dict")
        pulumi.set(__self__, "profile", profile)
        if verified_id and not isinstance(verified_id, str):
            raise TypeError("Expected argument 'verified_id' to be a str")
        pulumi.set(__self__, "verified_id", verified_id)

    @_builtins.property
    @pulumi.getter
    def exists(self) -> _builtins.bool:
        """
        Whether Osano recognized the session.
        """
        return pulumi.get(self, "exists")

    @_builtins.property
    @pulumi.getter
    def profile(self) -> Mapping[str, Any]:
        """
        The session's profile (email, firstName, lastName). Secret, because it is personal data.
        """
        return pulumi.get(self, "profile")

    @_builtins.property
    @pulumi.getter(name="verifiedId")
    def verified_id(self) -> _builtins.str:
        """
        The verified ID of the session's subject.
        """
        return pulumi.get(self, "verified_id")


class AwaitableGetSessionResult(GetSessionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSessionResult(
            exists=self.exists,
            profile=self.profile,
            verified_id=self.verified_id)


def get_session(session_id: Optional[_builtins.str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSessionResult:
    """
    Resolves a Unified Consent session ID to its subject's verified ID and profile, using the Unified Consent API key.

    :param _builtins.str session_id: The session ID to resolve.
    """
    __args__ = dict()
    __args__['sessionId'] = session_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('osano:index:getSession', __args__, opts=opts, typ=GetSessionResult).value

    return AwaitableGetSessionResult(
        exists=pulumi.get(__ret__, 'exists'),
        profile=pulumi.get(__ret__, 'profile'),
        verified_id=pulumi.get(__ret__, 'verified_id'))
def get_session_output(session_id: pulumi.Input[Optional[_builtins.str]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSessionResult]:
    """
    Resolves a Unified Consent session ID to its subject's verified ID and profile, using the Unified Consent API key.

    :param _builtins.str session_id: The session ID to resolve.
    """
    __args__ = dict()
    __args__['sessionId'] = session_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('osano:index:getSession', __args__, opts=opts, typ=GetSessionResult)
    return __ret__.apply(lambda __response__: GetSessionResult(
        exists=pulumi.get(__response__, 'exists'),
        profile=pulumi.get(__response__, 'profile'),
        verified_id=pulumi.get(__response__, 'verified_id')))
