# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetCollectionsResult',
    'AwaitableGetCollectionsResult',
    'get_collections',
    'get_collections_output',
]

@pulumi.output_type
class GetCollectionsResult:
    def __init__(__self__, collection=None, jurisdictions=None):
        if collection and not isinstance(collection, dict):
            raise TypeError("Expected argument 'collection' to be a dict")
        pulumi.set(__self__, "collection", collection)
        if jurisdictions and not isinstance(jurisdictions, list):
            raise TypeError("Expected argument 'jurisdictions' to be a list")
        pulumi.set(__self__, "jurisdictions", jurisdictions)

    @_builtins.property
    @pulumi.getter
    def collection(self) -> Mapping[str, Any]:
        return pulumi.get(self, "collection")

    @_builtins.property
    @pulumi.getter
    def jurisdictions(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "jurisdictions")


class AwaitableGetCollectionsResult(GetCollectionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCollectionsResult(
            collection=self.collection,
            jurisdictions=self.jurisdictions)


def get_collections(jurisdiction: Optional[_builtins.str] = None,
                    type: Optional[_builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCollectionsResult:
    """
    Retrieves the aggregated privacy protocol collections for an optional jurisdiction and version (published/draft).
    """
    __args__ = dict()
    __args__['jurisdiction'] = jurisdiction
    __args__['type'] = type
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('osano:index:getCollections', __args__, opts=opts, typ=GetCollectionsResult).value

    return AwaitableGetCollectionsResult(
        collection=pulumi.get(__ret__, 'collection'),
        jurisdictions=pulumi.get(__ret__, 'jurisdictions'))
def get_collections_output(jurisdiction: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                           type: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCollectionsResult]:
    """
    Retrieves the aggregated privacy protocol collections for an optional jurisdiction and version (published/draft).
    """
    __args__ = dict()
    __args__['jurisdiction'] = jurisdiction
    __args__['type'] = type
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('osano:index:getCollections', __args__, opts=opts, typ=GetCollectionsResult)
    return __ret__.apply(lambda __response__: GetCollectionsResult(
        collection=pulumi.get(__response__, 'collection'),
        jurisdictions=pulumi.get(__response__, 'jurisdictions')))
