# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'VerifySubjectCodeResult',
    'AwaitableVerifySubjectCodeResult',
    'verify_subject_code',
    'verify_subject_code_output',
]

@pulumi.output_type
class VerifySubjectCodeResult:
    def __init__(__self__, channel=None, destination=None, hashed_subject_id=None, profile=None, verified=None):
        if channel and not isinstance(channel, str):
            raise TypeError("Expected argument 'channel' to be a str")
        pulumi.set(__self__, "channel", channel)
        if destination and not isinstance(destination, str):
            raise TypeError("Expected argument 'destination' to be a str")
        pulumi.set(__self__, "destination", destination)
        if hashed_subject_id and not isinstance(hashed_subject_id, str):
            raise TypeError("Expected argument 'hashed_subject_id' to be a str")
        pulumi.set(__self__, "hashed_subject_id", hashed_subject_id)
        if profile and not isinstance(profile, dict):
            raise TypeError("Expected argument 'profile' to be a dict")
        pulumi.set(__self__, "profile", profile)
        if verified and not isinstance(verified, bool):
            raise TypeError("Expected argument 'verified' to be a bool")
        pulumi.set(__self__, "verified", verified)

    @_builtins.property
    @pulumi.getter
    def channel(self) -> _builtins.str:
        return pulumi.get(self, "channel")

    @_builtins.property
    @pulumi.getter
    def destination(self) -> _builtins.str:
        return pulumi.get(self, "destination")

    @_builtins.property
    @pulumi.getter(name="hashedSubjectId")
    def hashed_subject_id(self) -> _builtins.str:
        return pulumi.get(self, "hashed_subject_id")

    @_builtins.property
    @pulumi.getter
    def profile(self) -> Mapping[str, Any]:
        return pulumi.get(self, "profile")

    @_builtins.property
    @pulumi.getter
    def verified(self) -> _builtins.bool:
        return pulumi.get(self, "verified")


class AwaitableVerifySubjectCodeResult(VerifySubjectCodeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return VerifySubjectCodeResult(
            channel=self.channel,
            destination=self.destination,
            hashed_subject_id=self.hashed_subject_id,
            profile=self.profile,
            verified=self.verified)


def verify_subject_code(code: Optional[_builtins.str] = None,
                        email: Optional[_builtins.str] = None,
                        hashed_subject_id: Optional[_builtins.str] = None,
                        phone: Optional[_builtins.str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableVerifySubjectCodeResult:
    """
    Verifies a subject profile using the code sent via email or SMS.
    """
    __args__ = dict()
    __args__['code'] = code
    __args__['email'] = email
    __args__['hashedSubjectId'] = hashed_subject_id
    __args__['phone'] = phone
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('osano:index:verifySubjectCode', __args__, opts=opts, typ=VerifySubjectCodeResult).value

    return AwaitableVerifySubjectCodeResult(
        channel=pulumi.get(__ret__, 'channel'),
        destination=pulumi.get(__ret__, 'destination'),
        hashed_subject_id=pulumi.get(__ret__, 'hashed_subject_id'),
        profile=pulumi.get(__ret__, 'profile'),
        verified=pulumi.get(__ret__, 'verified'))
def verify_subject_code_output(code: Optional[pulumi.Input[_builtins.str]] = None,
                               email: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               hashed_subject_id: Optional[pulumi.Input[_builtins.str]] = None,
                               phone: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[VerifySubjectCodeResult]:
    """
    Verifies a subject profile using the code sent via email or SMS.
    """
    __args__ = dict()
    __args__['code'] = code
    __args__['email'] = email
    __args__['hashedSubjectId'] = hashed_subject_id
    __args__['phone'] = phone
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('osano:index:verifySubjectCode', __args__, opts=opts, typ=VerifySubjectCodeResult)
    return __ret__.apply(lambda __response__: VerifySubjectCodeResult(
        channel=pulumi.get(__response__, 'channel'),
        destination=pulumi.get(__response__, 'destination'),
        hashed_subject_id=pulumi.get(__response__, 'hashed_subject_id'),
        profile=pulumi.get(__response__, 'profile'),
        verified=pulumi.get(__response__, 'verified')))
