template: native
provider: pulumi-osano
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/jflavan/pulumi-osano/provider.Version
parallel: 3
sdkModuleDir: sdk/go/osano
esc:
    enabled: true
    environment: imports/github-secrets
# For some reason this is required. If it's omitted all of the env keys get duplicated.
envOverride:
    FOO: BAR
