// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Inputs
{

    public sealed class ConsentPrivacyPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        [Input("version")]
        public Input<string>? Version { get; set; }

        public ConsentPrivacyPolicyArgs()
        {
        }
        public static new ConsentPrivacyPolicyArgs Empty => new ConsentPrivacyPolicyArgs();
    }
}
