// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Inputs
{

    public sealed class ConsentComplianceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// 1 if the Global Privacy Control signal is enabled, 0 otherwise.
        /// </summary>
        [Input("gpc")]
        public Input<int>? Gpc { get; set; }

        /// <summary>
        /// The privacy policy in effect when the consent was given.
        /// </summary>
        [Input("privacyPolicy")]
        public Input<Inputs.ConsentPrivacyPolicyArgs>? PrivacyPolicy { get; set; }

        public ConsentComplianceArgs()
        {
        }
        public static new ConsentComplianceArgs Empty => new ConsentComplianceArgs();
    }
}
