# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 customer_base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 osano_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_base_url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] customer_base_url: Override base URL for the Customer REST API (default: https://api.osano.com).
        :param pulumi.Input[_builtins.str] osano_api_key: Osano API key for the Customer REST API (x-osano-api-key).
        :param pulumi.Input[_builtins.str] uc_api_key: Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
        :param pulumi.Input[_builtins.str] uc_base_url: Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
        """
        if customer_base_url is not None:
            pulumi.set(__self__, "customer_base_url", customer_base_url)
        if osano_api_key is not None:
            pulumi.set(__self__, "osano_api_key", osano_api_key)
        if uc_api_key is not None:
            pulumi.set(__self__, "uc_api_key", uc_api_key)
        if uc_base_url is not None:
            pulumi.set(__self__, "uc_base_url", uc_base_url)

    @_builtins.property
    @pulumi.getter(name="customerBaseUrl")
    def customer_base_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Override base URL for the Customer REST API (default: https://api.osano.com).
        """
        return pulumi.get(self, "customer_base_url")

    @customer_base_url.setter
    def customer_base_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "customer_base_url", value)

    @_builtins.property
    @pulumi.getter(name="osanoApiKey")
    def osano_api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Osano API key for the Customer REST API (x-osano-api-key).
        """
        return pulumi.get(self, "osano_api_key")

    @osano_api_key.setter
    def osano_api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "osano_api_key", value)

    @_builtins.property
    @pulumi.getter(name="ucApiKey")
    def uc_api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
        """
        return pulumi.get(self, "uc_api_key")

    @uc_api_key.setter
    def uc_api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uc_api_key", value)

    @_builtins.property
    @pulumi.getter(name="ucBaseUrl")
    def uc_base_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
        """
        return pulumi.get(self, "uc_base_url")

    @uc_base_url.setter
    def uc_base_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uc_base_url", value)


@pulumi.type_token("pulumi:providers:osano")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 customer_base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 osano_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Osano resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] customer_base_url: Override base URL for the Customer REST API (default: https://api.osano.com).
        :param pulumi.Input[_builtins.str] osano_api_key: Osano API key for the Customer REST API (x-osano-api-key).
        :param pulumi.Input[_builtins.str] uc_api_key: Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
        :param pulumi.Input[_builtins.str] uc_base_url: Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Osano resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 customer_base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 osano_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 uc_base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["customer_base_url"] = customer_base_url
            __props__.__dict__["osano_api_key"] = None if osano_api_key is None else pulumi.Output.secret(osano_api_key)
            __props__.__dict__["uc_api_key"] = None if uc_api_key is None else pulumi.Output.secret(uc_api_key)
            __props__.__dict__["uc_base_url"] = uc_base_url
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["osanoApiKey", "ucApiKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'osano',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter(name="customerBaseUrl")
    def customer_base_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Override base URL for the Customer REST API (default: https://api.osano.com).
        """
        return pulumi.get(self, "customer_base_url")

    @_builtins.property
    @pulumi.getter(name="osanoApiKey")
    def osano_api_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Osano API key for the Customer REST API (x-osano-api-key).
        """
        return pulumi.get(self, "osano_api_key")

    @_builtins.property
    @pulumi.getter(name="ucApiKey")
    def uc_api_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
        """
        return pulumi.get(self, "uc_api_key")

    @_builtins.property
    @pulumi.getter(name="ucBaseUrl")
    def uc_base_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
        """
        return pulumi.get(self, "uc_base_url")

