// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
func GetApiBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:apiBaseUrl")
}

// Override base URL for the Customer REST API (default: https://api.osano.com).
func GetCustomerBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:customerBaseUrl")
}

// Osano API key used for subject profile routes (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
func GetOsanoApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:osanoApiKey")
}

// HTTP request timeout in seconds for Osano API calls (default 60).
func GetRequestTimeoutSeconds(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "osano:requestTimeoutSeconds")
}

// Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
//
// Deprecated: use unifiedConsentApiKey instead
func GetUcApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:ucApiKey")
}

// Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
//
// Deprecated: use apiBaseUrl instead
func GetUcBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:ucBaseUrl")
}

// Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
func GetUnifiedConsentApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:unifiedConsentApiKey")
}
