[project]
  name = "osano_osano"
  description = "Pulumi provider for managing Osano via the Osano APIs (Customer REST API and Unified Consent Core API). "
  dependencies = ["parver>=0.2.1", "pulumi>=3.165.0,<4.0.0", "semver>=2.8.1", "typing-extensions>=4.11,<5; python_version < \"3.11\""]
  readme = "README.md"
  requires-python = ">=3.9"
  version = "0.0.1+dev"
  [project.urls]
    Homepage = "https://developers.osano.com/"
    Repository = "https://github.com/highfiveghost/pulumi-osano"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      osano_osano = ["py.typed", "pulumi-plugin.json"]
