// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    [OutputType]
    public sealed class ConsentAction
    {
        public readonly string Action;
        public readonly string? Jurisdiction;
        public readonly string Target;
        public readonly string Vendor;

        [OutputConstructor]
        private ConsentAction(
            string action,

            string? jurisdiction,

            string target,

            string vendor)
        {
            Action = action;
            Jurisdiction = jurisdiction;
            Target = target;
            Vendor = vendor;
        }
    }
}
