// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    [OutputType]
    public sealed class ConsentCompliance
    {
        /// <summary>
        /// 1 if the Global Privacy Control signal is enabled, 0 otherwise.
        /// </summary>
        public readonly int? Gpc;
        /// <summary>
        /// The privacy policy in effect when the consent was given.
        /// </summary>
        public readonly Outputs.ConsentPrivacyPolicy? PrivacyPolicy;

        [OutputConstructor]
        private ConsentCompliance(
            int? gpc,

            Outputs.ConsentPrivacyPolicy? privacyPolicy)
        {
            Gpc = gpc;
            PrivacyPolicy = privacyPolicy;
        }
    }
}
