// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    [OutputType]
    public sealed class CookieConsentRuleDetails
    {
        /// <summary>
        /// The rule classification.
        /// </summary>
        public readonly string Classification;
        /// <summary>
        /// The configuration the rule belongs to.
        /// </summary>
        public readonly string ConfigId;
        /// <summary>
        /// When the rule was created (ISO 8601).
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// The cookie description, if set (cookies only).
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Whether the rule is disclosed.
        /// </summary>
        public readonly bool Disclosure;
        /// <summary>
        /// The cookie expiry description, if set (cookies only).
        /// </summary>
        public readonly string? Expiry;
        /// <summary>
        /// The rule pattern.
        /// </summary>
        public readonly string Rule;
        /// <summary>
        /// The server-assigned integer rule ID. Import a rule with &lt;configId&gt;/&lt;ruleId&gt;.
        /// </summary>
        public readonly int RuleId;
        /// <summary>
        /// The matching mode, if set.
        /// </summary>
        public readonly string? RuleType;
        /// <summary>
        /// The storage type: cookies, scripts, iframes, or localStorage. Osano's raw type is passed through when it is not one of these.
        /// </summary>
        public readonly string StoreType;
        /// <summary>
        /// The disclosure title, if set.
        /// </summary>
        public readonly string? Title;
        /// <summary>
        /// When the rule was last updated (ISO 8601).
        /// </summary>
        public readonly string Updated;
        /// <summary>
        /// The Osano vendor ID, if set.
        /// </summary>
        public readonly string? VendorId;
        /// <summary>
        /// The vendor name, if set.
        /// </summary>
        public readonly string? VendorName;

        [OutputConstructor]
        private CookieConsentRuleDetails(
            string classification,

            string configId,

            string created,

            string? description,

            bool disclosure,

            string? expiry,

            string rule,

            int ruleId,

            string? ruleType,

            string storeType,

            string? title,

            string updated,

            string? vendorId,

            string? vendorName)
        {
            Classification = classification;
            ConfigId = configId;
            Created = created;
            Description = description;
            Disclosure = disclosure;
            Expiry = expiry;
            Rule = rule;
            RuleId = ruleId;
            RuleType = ruleType;
            StoreType = storeType;
            Title = title;
            Updated = updated;
            VendorId = vendorId;
            VendorName = vendorName;
        }
    }
}
