// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    [OutputType]
    public sealed class CookieConsentConfigDetails
    {
        /// <summary>
        /// The Osano config ID (UUID).
        /// </summary>
        public readonly string ConfigId;
        /// <summary>
        /// The CMP configuration object as Osano reports it, including server defaults.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Configuration;
        /// <summary>
        /// Unix timestamp when Osano created the configuration.
        /// </summary>
        public readonly int Created;
        /// <summary>
        /// The Osano customer ID that owns the configuration.
        /// </summary>
        public readonly string CustomerId;
        /// <summary>
        /// Domains permitted to host the configuration.
        /// </summary>
        public readonly ImmutableArray<string> Domains;
        /// <summary>
        /// Unix timestamp when Osano last published the configuration (0 if never).
        /// </summary>
        public readonly int LastPublished;
        /// <summary>
        /// Compliance mode: debug, permissive, or production.
        /// </summary>
        public readonly string Mode;
        /// <summary>
        /// The configuration name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Organization IDs associated with the configuration.
        /// </summary>
        public readonly ImmutableArray<string> OrgIds;
        /// <summary>
        /// Osano publication status: unpublished, in-progress, published, outdated (changed since the last publish), or error.
        /// </summary>
        public readonly string PublishStatus;
        /// <summary>
        /// Revision number most recently published by Osano.
        /// </summary>
        public readonly int PublishedRevision;
        /// <summary>
        /// The public hosted CMP JavaScript URL, https://cmp.osano.com/{customerId}/{configId}/osano.js. It serves the most recently published revision.
        /// </summary>
        public readonly string ScriptSrc;
        /// <summary>
        /// The complete public CMP script tag to place first in the site head, without async or defer attributes.
        /// </summary>
        public readonly string ScriptTag;
        /// <summary>
        /// Whether Osano stopped recording discoveries (tattles) for the configuration.
        /// </summary>
        public readonly bool TattleRecordStopped;
        /// <summary>
        /// Unix timestamp when Osano last updated the configuration.
        /// </summary>
        public readonly int Updated;

        [OutputConstructor]
        private CookieConsentConfigDetails(
            string configId,

            ImmutableDictionary<string, object> configuration,

            int created,

            string customerId,

            ImmutableArray<string> domains,

            int lastPublished,

            string mode,

            string name,

            ImmutableArray<string> orgIds,

            string publishStatus,

            int publishedRevision,

            string scriptSrc,

            string scriptTag,

            bool tattleRecordStopped,

            int updated)
        {
            ConfigId = configId;
            Configuration = configuration;
            Created = created;
            CustomerId = customerId;
            Domains = domains;
            LastPublished = lastPublished;
            Mode = mode;
            Name = name;
            OrgIds = orgIds;
            PublishStatus = publishStatus;
            PublishedRevision = publishedRevision;
            ScriptSrc = scriptSrc;
            ScriptTag = scriptTag;
            TattleRecordStopped = tattleRecordStopped;
            Updated = updated;
        }
    }
}
