// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    [OutputType]
    public sealed class CookieConsentAuditEvent
    {
        /// <summary>
        /// The email of the user who performed the action, when known.
        /// </summary>
        public readonly string? Actor;
        /// <summary>
        /// The machine-readable event type, such as cmp.configPublished.
        /// </summary>
        public readonly string EventType;
        /// <summary>
        /// The audit event ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Event-specific details, such as changed fields and before/after values.
        /// </summary>
        public readonly ImmutableDictionary<string, object>? Metadata;
        /// <summary>
        /// The Osano module, currently always CMP.
        /// </summary>
        public readonly string Module;
        /// <summary>
        /// The resources the event acted on.
        /// </summary>
        public readonly ImmutableArray<Outputs.CookieConsentAuditResource> Resources;
        /// <summary>
        /// When the event occurred (UTC ISO 8601).
        /// </summary>
        public readonly string Timestamp;

        [OutputConstructor]
        private CookieConsentAuditEvent(
            string? actor,

            string eventType,

            string id,

            ImmutableDictionary<string, object>? metadata,

            string module,

            ImmutableArray<Outputs.CookieConsentAuditResource> resources,

            string timestamp)
        {
            Actor = actor;
            EventType = eventType;
            Id = id;
            Metadata = metadata;
            Module = module;
            Resources = resources;
            Timestamp = timestamp;
        }
    }
}
