// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jflavan.pulumi.osano.ConsentArgs;
import io.github.jflavan.pulumi.osano.Utilities;
import io.github.jflavan.pulumi.osano.outputs.ConsentAction;
import io.github.jflavan.pulumi.osano.outputs.ConsentCompliance;
import io.github.jflavan.pulumi.osano.outputs.ConsentSubject;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Creates unified consent decisions within Osano for a given subject.
 *
 */
@ResourceType(type="osano:index:Consent")
public class Consent extends com.pulumi.resources.CustomResource {
    /**
     * Consent actions referencing privacy protocols (target) within a configuration (vendor).
     *
     */
    @Export(name="actions", refs={List.class,ConsentAction.class}, tree="[0,1]")
    private Output<List<ConsentAction>> actions;

    /**
     * @return Consent actions referencing privacy protocols (target) within a configuration (vendor).
     *
     */
    public Output<List<ConsentAction>> actions() {
        return this.actions;
    }
    /**
     * Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
     *
     */
    @Export(name="attributes", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> attributes;

    /**
     * @return Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
     *
     */
    public Output<Optional<Map<String,String>>> attributes() {
        return Codegen.optional(this.attributes);
    }
    @Export(name="compliance", refs={ConsentCompliance.class}, tree="[0]")
    private Output</* @Nullable */ ConsentCompliance> compliance;

    public Output<Optional<ConsentCompliance>> compliance() {
        return Codegen.optional(this.compliance);
    }
    /**
     * Synthetic identifier used by Pulumi to track consent submissions.
     *
     */
    @Export(name="consentId", refs={String.class}, tree="[0]")
    private Output<String> consentId;

    /**
     * @return Synthetic identifier used by Pulumi to track consent submissions.
     *
     */
    public Output<String> consentId() {
        return this.consentId;
    }
    /**
     * Optional jurisdiction override matching one of the configuration&#39;s jurisdictions.
     *
     */
    @Export(name="jurisdiction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> jurisdiction;

    /**
     * @return Optional jurisdiction override matching one of the configuration&#39;s jurisdictions.
     *
     */
    public Output<Optional<String>> jurisdiction() {
        return Codegen.optional(this.jurisdiction);
    }
    /**
     * Timestamp of the last refresh from the Osano API (RFC3339).
     *
     */
    @Export(name="lastSynced", refs={String.class}, tree="[0]")
    private Output<String> lastSynced;

    /**
     * @return Timestamp of the last refresh from the Osano API (RFC3339).
     *
     */
    public Output<String> lastSynced() {
        return this.lastSynced;
    }
    /**
     * Origin metadata for the consent, typically &#39;api&#39; or &#39;gpc&#39;.
     *
     */
    @Export(name="origin", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> origin;

    /**
     * @return Origin metadata for the consent, typically &#39;api&#39; or &#39;gpc&#39;.
     *
     */
    public Output<Optional<String>> origin() {
        return Codegen.optional(this.origin);
    }
    /**
     * Subject identifiers used for the consent (verifiedId or anonymousId).
     *
     */
    @Export(name="subject", refs={ConsentSubject.class}, tree="[0]")
    private Output<ConsentSubject> subject;

    /**
     * @return Subject identifiers used for the consent (verifiedId or anonymousId).
     *
     */
    public Output<ConsentSubject> subject() {
        return this.subject;
    }
    /**
     * Custom tags that Osano associates with the consent record.
     *
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return Custom tags that Osano associates with the consent record.
     *
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Consent(java.lang.String name) {
        this(name, ConsentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Consent(java.lang.String name, ConsentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Consent(java.lang.String name, ConsentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano:index:Consent", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Consent(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano:index:Consent", name, null, makeResourceOptions(options, id), false);
    }

    private static ConsentArgs makeArgs(ConsentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ConsentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/jflavan/pulumi-osano")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Consent get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Consent(name, id, options);
    }
}
