// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jflavan.pulumi.osano.inputs.ConsentActionArgs;
import io.github.jflavan.pulumi.osano.inputs.ConsentComplianceArgs;
import io.github.jflavan.pulumi.osano.inputs.ConsentSubjectArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsentArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsentArgs Empty = new ConsentArgs();

    /**
     * Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
     *
     */
    @Import(name="actions")
    private @Nullable Output<List<ConsentActionArgs>> actions;

    /**
     * @return Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
     *
     */
    public Optional<Output<List<ConsentActionArgs>>> actions() {
        return Optional.ofNullable(this.actions);
    }

    /**
     * Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
     *
     */
    @Import(name="attributes")
    private @Nullable Output<Map<String,String>> attributes;

    /**
     * @return Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
     *
     */
    public Optional<Output<Map<String,String>>> attributes() {
        return Optional.ofNullable(this.attributes);
    }

    /**
     * Optional compliance metadata such as the privacy policy version and GPC signal.
     *
     */
    @Import(name="compliance")
    private @Nullable Output<ConsentComplianceArgs> compliance;

    /**
     * @return Optional compliance metadata such as the privacy policy version and GPC signal.
     *
     */
    public Optional<Output<ConsentComplianceArgs>> compliance() {
        return Optional.ofNullable(this.compliance);
    }

    /**
     * Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
     *
     */
    @Import(name="countryCodeOverride")
    private @Nullable Output<String> countryCodeOverride;

    /**
     * @return Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
     *
     */
    public Optional<Output<String>> countryCodeOverride() {
        return Optional.ofNullable(this.countryCodeOverride);
    }

    /**
     * Optional jurisdiction, which must be one of the configuration&#39;s jurisdictions (see getCollections).
     *
     */
    @Import(name="jurisdiction")
    private @Nullable Output<String> jurisdiction;

    /**
     * @return Optional jurisdiction, which must be one of the configuration&#39;s jurisdictions (see getCollections).
     *
     */
    public Optional<Output<String>> jurisdiction() {
        return Optional.ofNullable(this.jurisdiction);
    }

    /**
     * Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano&#39;s GPC endpoint, which derives the actions.
     *
     */
    @Import(name="origin")
    private @Nullable Output<String> origin;

    /**
     * @return Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano&#39;s GPC endpoint, which derives the actions.
     *
     */
    public Optional<Output<String>> origin() {
        return Optional.ofNullable(this.origin);
    }

    /**
     * Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
     *
     */
    @Import(name="regionCodeOverride")
    private @Nullable Output<String> regionCodeOverride;

    /**
     * @return Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
     *
     */
    public Optional<Output<String>> regionCodeOverride() {
        return Optional.ofNullable(this.regionCodeOverride);
    }

    /**
     * Optional session token returned when the subject&#39;s profile was created.
     *
     */
    @Import(name="sessionToken")
    private @Nullable Output<String> sessionToken;

    /**
     * @return Optional session token returned when the subject&#39;s profile was created.
     *
     */
    public Optional<Output<String>> sessionToken() {
        return Optional.ofNullable(this.sessionToken);
    }

    /**
     * Subject identifiers used for the consent (verifiedId or anonymousId).
     *
     */
    @Import(name="subject", required=true)
    private Output<ConsentSubjectArgs> subject;

    /**
     * @return Subject identifiers used for the consent (verifiedId or anonymousId).
     *
     */
    public Output<ConsentSubjectArgs> subject() {
        return this.subject;
    }

    /**
     * Custom tags that Osano associates with the consent record.
     *
     */
    @Import(name="tags")
    private @Nullable Output<List<String>> tags;

    /**
     * @return Custom tags that Osano associates with the consent record.
     *
     */
    public Optional<Output<List<String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private ConsentArgs() {}

    private ConsentArgs(ConsentArgs $) {
        this.actions = $.actions;
        this.attributes = $.attributes;
        this.compliance = $.compliance;
        this.countryCodeOverride = $.countryCodeOverride;
        this.jurisdiction = $.jurisdiction;
        this.origin = $.origin;
        this.regionCodeOverride = $.regionCodeOverride;
        this.sessionToken = $.sessionToken;
        this.subject = $.subject;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsentArgs $;

        public Builder() {
            $ = new ConsentArgs();
        }

        public Builder(ConsentArgs defaults) {
            $ = new ConsentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
         *
         * @return builder
         *
         */
        public Builder actions(@Nullable Output<List<ConsentActionArgs>> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
         *
         * @return builder
         *
         */
        public Builder actions(List<ConsentActionArgs> actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param actions Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
         *
         * @return builder
         *
         */
        public Builder actions(ConsentActionArgs... actions) {
            return actions(List.of(actions));
        }

        /**
         * @param attributes Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
         *
         * @return builder
         *
         */
        public Builder attributes(@Nullable Output<Map<String,String>> attributes) {
            $.attributes = attributes;
            return this;
        }

        /**
         * @param attributes Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
         *
         * @return builder
         *
         */
        public Builder attributes(Map<String,String> attributes) {
            return attributes(Output.of(attributes));
        }

        /**
         * @param compliance Optional compliance metadata such as the privacy policy version and GPC signal.
         *
         * @return builder
         *
         */
        public Builder compliance(@Nullable Output<ConsentComplianceArgs> compliance) {
            $.compliance = compliance;
            return this;
        }

        /**
         * @param compliance Optional compliance metadata such as the privacy policy version and GPC signal.
         *
         * @return builder
         *
         */
        public Builder compliance(ConsentComplianceArgs compliance) {
            return compliance(Output.of(compliance));
        }

        /**
         * @param countryCodeOverride Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
         *
         * @return builder
         *
         */
        public Builder countryCodeOverride(@Nullable Output<String> countryCodeOverride) {
            $.countryCodeOverride = countryCodeOverride;
            return this;
        }

        /**
         * @param countryCodeOverride Optional ISO 3166-1 country code Osano uses instead of resolving the caller&#39;s IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
         *
         * @return builder
         *
         */
        public Builder countryCodeOverride(String countryCodeOverride) {
            return countryCodeOverride(Output.of(countryCodeOverride));
        }

        /**
         * @param jurisdiction Optional jurisdiction, which must be one of the configuration&#39;s jurisdictions (see getCollections).
         *
         * @return builder
         *
         */
        public Builder jurisdiction(@Nullable Output<String> jurisdiction) {
            $.jurisdiction = jurisdiction;
            return this;
        }

        /**
         * @param jurisdiction Optional jurisdiction, which must be one of the configuration&#39;s jurisdictions (see getCollections).
         *
         * @return builder
         *
         */
        public Builder jurisdiction(String jurisdiction) {
            return jurisdiction(Output.of(jurisdiction));
        }

        /**
         * @param origin Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano&#39;s GPC endpoint, which derives the actions.
         *
         * @return builder
         *
         */
        public Builder origin(@Nullable Output<String> origin) {
            $.origin = origin;
            return this;
        }

        /**
         * @param origin Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano&#39;s GPC endpoint, which derives the actions.
         *
         * @return builder
         *
         */
        public Builder origin(String origin) {
            return origin(Output.of(origin));
        }

        /**
         * @param regionCodeOverride Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
         *
         * @return builder
         *
         */
        public Builder regionCodeOverride(@Nullable Output<String> regionCodeOverride) {
            $.regionCodeOverride = regionCodeOverride;
            return this;
        }

        /**
         * @param regionCodeOverride Optional ISO 3166-2 region code Osano uses instead of resolving the caller&#39;s IP address.
         *
         * @return builder
         *
         */
        public Builder regionCodeOverride(String regionCodeOverride) {
            return regionCodeOverride(Output.of(regionCodeOverride));
        }

        /**
         * @param sessionToken Optional session token returned when the subject&#39;s profile was created.
         *
         * @return builder
         *
         */
        public Builder sessionToken(@Nullable Output<String> sessionToken) {
            $.sessionToken = sessionToken;
            return this;
        }

        /**
         * @param sessionToken Optional session token returned when the subject&#39;s profile was created.
         *
         * @return builder
         *
         */
        public Builder sessionToken(String sessionToken) {
            return sessionToken(Output.of(sessionToken));
        }

        /**
         * @param subject Subject identifiers used for the consent (verifiedId or anonymousId).
         *
         * @return builder
         *
         */
        public Builder subject(Output<ConsentSubjectArgs> subject) {
            $.subject = subject;
            return this;
        }

        /**
         * @param subject Subject identifiers used for the consent (verifiedId or anonymousId).
         *
         * @return builder
         *
         */
        public Builder subject(ConsentSubjectArgs subject) {
            return subject(Output.of(subject));
        }

        /**
         * @param tags Custom tags that Osano associates with the consent record.
         *
         * @return builder
         *
         */
        public Builder tags(@Nullable Output<List<String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Custom tags that Osano associates with the consent record.
         *
         * @return builder
         *
         */
        public Builder tags(List<String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags Custom tags that Osano associates with the consent record.
         *
         * @return builder
         *
         */
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }

        public ConsentArgs build() {
            if ($.subject == null) {
                throw new MissingRequiredPropertyException("ConsentArgs", "subject");
            }
            return $;
        }
    }

}
