// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jflavan.pulumi.osano.CookieConsentRuleArgs;
import io.github.jflavan.pulumi.osano.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages an Osano Cookie Consent (CMP) rule within a configuration.
 *
 */
@ResourceType(type="osano:index:CookieConsentRule")
public class CookieConsentRule extends com.pulumi.resources.CustomResource {
    /**
     * Classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, or PERSONALIZATION.
     *
     */
    @Export(name="classification", refs={String.class}, tree="[0]")
    private Output<String> classification;

    /**
     * @return Classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, or PERSONALIZATION.
     *
     */
    public Output<String> classification() {
        return this.classification;
    }
    /**
     * The configId of the Cookie Consent Configuration this rule belongs to.
     *
     */
    @Export(name="configId", refs={String.class}, tree="[0]")
    private Output<String> configId;

    /**
     * @return The configId of the Cookie Consent Configuration this rule belongs to.
     *
     */
    public Output<String> configId() {
        return this.configId;
    }
    /**
     * Timestamp when the rule was created.
     *
     */
    @Export(name="created", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> created;

    /**
     * @return Timestamp when the rule was created.
     *
     */
    public Output<Optional<String>> created() {
        return Codegen.optional(this.created);
    }
    /**
     * Whether the rule should be disclosed. Defaults to false.
     *
     */
    @Export(name="disclosure", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> disclosure;

    /**
     * @return Whether the rule should be disclosed. Defaults to false.
     *
     */
    public Output<Optional<Boolean>> disclosure() {
        return Codegen.optional(this.disclosure);
    }
    /**
     * The rule pattern (e.g. a cookie name pattern). Min 3, max 1000 characters.
     *
     */
    @Export(name="rule", refs={String.class}, tree="[0]")
    private Output<String> rule;

    /**
     * @return The rule pattern (e.g. a cookie name pattern). Min 3, max 1000 characters.
     *
     */
    public Output<String> rule() {
        return this.rule;
    }
    /**
     * The server-assigned integer rule ID.
     *
     */
    @Export(name="ruleId", refs={Integer.class}, tree="[0]")
    private Output<Integer> ruleId;

    /**
     * @return The server-assigned integer rule ID.
     *
     */
    public Output<Integer> ruleId() {
        return this.ruleId;
    }
    /**
     * The storage type category: cookies, scripts, iframes, or localStorage.
     *
     */
    @Export(name="storeType", refs={String.class}, tree="[0]")
    private Output<String> storeType;

    /**
     * @return The storage type category: cookies, scripts, iframes, or localStorage.
     *
     */
    public Output<String> storeType() {
        return this.storeType;
    }
    /**
     * Optional title for the rule, used in consent disclosure.
     *
     */
    @Export(name="title", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> title;

    /**
     * @return Optional title for the rule, used in consent disclosure.
     *
     */
    public Output<Optional<String>> title() {
        return Codegen.optional(this.title);
    }
    /**
     * Timestamp when the rule was last updated.
     *
     */
    @Export(name="updated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> updated;

    /**
     * @return Timestamp when the rule was last updated.
     *
     */
    public Output<Optional<String>> updated() {
        return Codegen.optional(this.updated);
    }
    /**
     * Optional vendor name for the rule.
     *
     */
    @Export(name="vendorName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> vendorName;

    /**
     * @return Optional vendor name for the rule.
     *
     */
    public Output<Optional<String>> vendorName() {
        return Codegen.optional(this.vendorName);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CookieConsentRule(java.lang.String name) {
        this(name, CookieConsentRuleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CookieConsentRule(java.lang.String name, CookieConsentRuleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CookieConsentRule(java.lang.String name, CookieConsentRuleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano:index:CookieConsentRule", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private CookieConsentRule(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano:index:CookieConsentRule", name, null, makeResourceOptions(options, id), false);
    }

    private static CookieConsentRuleArgs makeArgs(CookieConsentRuleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CookieConsentRuleArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/jflavan/pulumi-osano")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CookieConsentRule get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CookieConsentRule(name, id, options);
    }
}
