// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jflavan.pulumi.osano.ProviderArgs;
import io.github.jflavan.pulumi.osano.Utilities;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="pulumi:providers:osano")
public class Provider extends com.pulumi.resources.ProviderResource {
    /**
     * Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
     *
     */
    @Export(name="apiBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> apiBaseUrl;

    /**
     * @return Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
     *
     */
    public Output<Optional<String>> apiBaseUrl() {
        return Codegen.optional(this.apiBaseUrl);
    }
    /**
     * Override base URL for the Customer REST API (default: https://api.osano.com).
     *
     */
    @Export(name="customerBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> customerBaseUrl;

    /**
     * @return Override base URL for the Customer REST API (default: https://api.osano.com).
     *
     */
    public Output<Optional<String>> customerBaseUrl() {
        return Codegen.optional(this.customerBaseUrl);
    }
    /**
     * Osano API key used for subject profile routes and Customer REST API/CMP operations (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
     *
     */
    @Export(name="osanoApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> osanoApiKey;

    /**
     * @return Osano API key used for subject profile routes and Customer REST API/CMP operations (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
     *
     */
    public Output<Optional<String>> osanoApiKey() {
        return Codegen.optional(this.osanoApiKey);
    }
    /**
     * Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
     *
     * @deprecated
     * use unifiedConsentApiKey instead
     *
     */
    @Deprecated /* use unifiedConsentApiKey instead */
    @Export(name="ucApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ucApiKey;

    /**
     * @return Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
     *
     */
    public Output<Optional<String>> ucApiKey() {
        return Codegen.optional(this.ucApiKey);
    }
    /**
     * Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
     *
     * @deprecated
     * use apiBaseUrl instead
     *
     */
    @Deprecated /* use apiBaseUrl instead */
    @Export(name="ucBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ucBaseUrl;

    /**
     * @return Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
     *
     */
    public Output<Optional<String>> ucBaseUrl() {
        return Codegen.optional(this.ucBaseUrl);
    }
    /**
     * Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
     *
     */
    @Export(name="unifiedConsentApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> unifiedConsentApiKey;

    /**
     * @return Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
     *
     */
    public Output<Optional<String>> unifiedConsentApiKey() {
        return Codegen.optional(this.unifiedConsentApiKey);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Provider(java.lang.String name) {
        this(name, ProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Provider(java.lang.String name, @Nullable ProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Provider(java.lang.String name, @Nullable ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private static ProviderArgs makeArgs(@Nullable ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProviderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/jflavan/pulumi-osano")
            .additionalSecretOutputs(List.of(
                "osanoApiKey",
                "ucApiKey",
                "unifiedConsentApiKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

}
