//go:build e2e && pipeline

package pipeline

import (
	"context"
	"encoding/json"
	"slices"
	"strings"
	"testing"

	"github.com/pulumi/pulumi/sdk/v3/go/common/apitype"
)

// dashboardOnlyKeys are configuration keys that Osano reports for a configuration edited in its
// dashboard, but that its spec does not define, so its PATCH rejects them.
func dashboardOnlyKeys() map[string]any {
	return map[string]any{
		"iabEnabled":           false,
		"analyticsOnByDefault": false,
		"palette":              map[string]any{"widgetColor": "#222222", "borderless": false},
	}
}

// testDashboardOnlyKeys covers keys that Osano's GET reports and its PATCH rejects. An imported
// configuration must stay writable, and a program that declares such keys, as one generated by an
// import with provider 0.3.1 or earlier does, must deploy and be able to stop declaring them without
// editing the state.
func testDashboardOnlyKeys(ctx context.Context, t *testing.T, h *harness) {
	mock := newMockOsano(t)
	mock.AddDashboardOnlyKeys(dashboardOnlyKeys())
	configID := mock.SeedConfig("dashboard-made", []string{"dash.example.com"}, map[string]any{
		"storagePolicyHref": "https://dash.example.com/privacy",
	})

	p := h.newProject(ctx, t, mock, "dashboard-keys.Pulumi.yaml", versionV2)
	template := p.template
	// render writes the program with the consent configuration declaring properties, or without it.
	render := func(properties map[string]any) {
		t.Helper()
		resource := ""
		if properties != nil {
			encoded, err := json.Marshal(properties)
			if err != nil {
				t.Fatal(err)
			}
			resource = "  consentConfig:\n    type: " + typeConfig + "\n    properties: " + string(encoded) +
				"\n    options:\n      provider: ${osanoProvider}\n"
		}
		p.template = strings.ReplaceAll(template, "# {{CONSENT_CONFIG}}", resource)
		p.writeProgram(t, versionV2)
	}
	render(nil)
	p.setConfig(ctx, t, map[string]configValue{
		"osanoBaseUrl": {Value: mock.URL()},
		"osanoKey":     {Value: mockAPIKey, Secret: true},
	})
	p.up(ctx, t, "dashboard up #1 (provider only)").requireOps(t, typeProvider, apitype.OpCreate)

	providerURN := resourceOfType(t, p.resources(ctx, t), typeProvider).URN
	mark := mock.Mark()
	if _, err := h.run(ctx, p.dir, "import", typeConfig, "consentConfig", configID,
		"--provider", "osanoProvider="+string(providerURN), "--yes", "--skip-preview",
		"--generate-code=false", "--protect=false", "--stack", stackName, "--color", "never"); err != nil {
		t.Fatalf("import: %v", err)
	}
	if n := countRequests(mock.RequestsSince(mark), isWrite); n != 0 {
		t.Errorf("import must only read, got %d writes:\n%s", n, describeRequests(mock.RequestsSince(mark)))
	}
	imported := resourceOfType(t, p.resources(ctx, t), typeConfig)
	importedConfiguration, _ := imported.Inputs["configuration"].(map[string]any)
	outputConfiguration, _ := imported.Outputs["configuration"].(map[string]any)
	requireNoDashboardOnlyKeys(t, "imported inputs", importedConfiguration)
	requireNoDashboardOnlyKeys(t, "imported outputs", outputConfiguration)
	if importedConfiguration["storagePolicyHref"] != "https://dash.example.com/privacy" {
		t.Fatalf("expected the import to adopt the spec keys, got %v", importedConfiguration)
	}

	// The program an import generates declares what was adopted.
	properties := map[string]any{}
	for key, value := range imported.Inputs {
		if !strings.HasPrefix(key, "__") {
			properties[key] = value
		}
	}
	render(properties)
	p.preview(ctx, t, "dashboard preview #2 (program matches the import)").requireNoChanges(t)

	// The first change to an imported configuration used to fail with 400.
	properties["configuration"] = withValue(importedConfiguration, "showWidget", false)
	render(properties)
	res := p.up(ctx, t, "dashboard up #3 (change the imported configuration)")
	res.requireOps(t, typeConfig, apitype.OpUpdate)
	res.requireCount(t, "config PATCH", isConfigPatch, 1)
	if snapshot, _ := mock.Config(configID); snapshot.Configuration["showWidget"] != false {
		t.Errorf("expected Osano to store showWidget=false, got %v", snapshot.Configuration)
	}

	// A program generated by an older import also declares the dashboard-only keys. Declaring them
	// changes only the state, and a refresh, which projects onto the declared keys, converges.
	legacy := mergeDefaults(properties["configuration"].(map[string]any), dashboardOnlyKeys())
	properties["configuration"] = legacy
	render(properties)
	res = p.up(ctx, t, "dashboard up #4 (declare dashboard-only keys)")
	res.requireOps(t, typeConfig, apitype.OpUpdate)
	res.requireCount(t, "write", isWrite, 0)
	requireDiagnostic(t, res, "configuration.iabEnabled is not in Osano's published Customer REST API spec")
	requireDiagnostic(t, res, "configuration.palette.widgetColor is not in Osano's published Customer REST API spec")
	p.up(ctx, t, "dashboard up #5 (refresh)", "--refresh").requireNoChanges(t)

	// Changing a spec key while still declaring them sends only the spec keys.
	properties["configuration"] = withValue(legacy, "showWidget", true)
	render(properties)
	res = p.up(ctx, t, "dashboard up #6 (change beside dashboard-only keys)")
	res.requireOps(t, typeConfig, apitype.OpUpdate)
	res.requireCount(t, "config PATCH", isConfigPatch, 1)

	// Removing them from the program clears them from the state without a request.
	properties["configuration"] = withValue(importedConfiguration, "showWidget", true)
	render(properties)
	res = p.up(ctx, t, "dashboard up #7 (stop declaring dashboard-only keys)")
	res.requireOps(t, typeConfig, apitype.OpUpdate)
	res.requireCount(t, "write", isWrite, 0)
	final := resourceOfType(t, p.resources(ctx, t), typeConfig)
	finalInputs, _ := final.Inputs["configuration"].(map[string]any)
	finalOutputs, _ := final.Outputs["configuration"].(map[string]any)
	requireNoDashboardOnlyKeys(t, "final inputs", finalInputs)
	requireNoDashboardOnlyKeys(t, "final outputs", finalOutputs)
	p.up(ctx, t, "dashboard up #8 (refresh)", "--refresh").requireNoChanges(t)
}

func withValue(configuration map[string]any, key string, value any) map[string]any {
	copied := deepCopyMap(configuration)
	copied[key] = value
	return copied
}

func requireNoDashboardOnlyKeys(t *testing.T, what string, configuration map[string]any) {
	t.Helper()
	palette, _ := configuration["palette"].(map[string]any)
	for key, value := range dashboardOnlyKeys() {
		if nested, isNested := value.(map[string]any); isNested {
			for nestedKey := range nested {
				if _, present := palette[nestedKey]; present {
					t.Errorf("%s hold the dashboard-only key %s.%s: %v", what, key, nestedKey, configuration)
				}
			}
		} else if _, present := configuration[key]; present {
			t.Errorf("%s hold the dashboard-only key %s: %v", what, key, configuration)
		}
	}
}

func requireDiagnostic(t *testing.T, r *opResult, want string) {
	t.Helper()
	if !slices.ContainsFunc(r.Diagnostics, func(d string) bool { return strings.Contains(d, want) }) {
		t.Errorf("%s: expected a diagnostic containing %q, got:\n  %s", r.Label, want,
			strings.Join(r.Diagnostics, "\n  "))
	}
}
