// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("osano");

/**
 * Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
 */
export declare const apiBaseUrl: string | undefined;
Object.defineProperty(exports, "apiBaseUrl", {
    get() {
        return __config.get("apiBaseUrl");
    },
    enumerable: true,
});

/**
 * Osano API key used for subject profile routes (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
 */
export declare const osanoApiKey: string | undefined;
Object.defineProperty(exports, "osanoApiKey", {
    get() {
        return __config.get("osanoApiKey");
    },
    enumerable: true,
});

/**
 * HTTP request timeout in seconds for Osano API calls (default 60).
 */
export declare const requestTimeoutSeconds: number | undefined;
Object.defineProperty(exports, "requestTimeoutSeconds", {
    get() {
        return __config.getObject<number>("requestTimeoutSeconds");
    },
    enumerable: true,
});

/**
 * Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
 */
export declare const unifiedConsentApiKey: string | undefined;
Object.defineProperty(exports, "unifiedConsentApiKey", {
    get() {
        return __config.get("unifiedConsentApiKey");
    },
    enumerable: true,
});

