// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class CheckConsent
    {
        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Task<CheckConsentResult> InvokeAsync(CheckConsentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentArgs(), options.WithDefaults());

        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Output<CheckConsentResult> Invoke(CheckConsentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Output<CheckConsentResult> Invoke(CheckConsentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentInvokeArgs(), options.WithDefaults());
    }


    public sealed class CheckConsentArgs : global::Pulumi.InvokeArgs
    {
        [Input("subjectId", required: true)]
        public string SubjectId { get; set; } = null!;

        public CheckConsentArgs()
        {
        }
        public static new CheckConsentArgs Empty => new CheckConsentArgs();
    }

    public sealed class CheckConsentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("subjectId", required: true)]
        public Input<string> SubjectId { get; set; } = null!;

        public CheckConsentInvokeArgs()
        {
        }
        public static new CheckConsentInvokeArgs Empty => new CheckConsentInvokeArgs();
    }


    [OutputType]
    public sealed class CheckConsentResult
    {
        public readonly bool Exists;
        public readonly string SubjectId;

        [OutputConstructor]
        private CheckConsentResult(
            bool exists,

            string subjectId)
        {
            Exists = exists;
            SubjectId = subjectId;
        }
    }
}
