// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    /// <summary>
    /// Submits a Unified Consent decision for a subject. Consents are immutable in Osano: changing any input submits a new consent (replacement), and destroying the resource only removes it from Pulumi state. Set origin to gpc and omit actions to submit a Global Privacy Control consent, whose actions Osano derives and returns in gpcActions.
    /// </summary>
    [OsanoResourceType("osano:index:Consent")]
    public partial class Consent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
        /// </summary>
        [Output("actions")]
        public Output<ImmutableArray<Outputs.ConsentAction>> Actions { get; private set; } = null!;

        /// <summary>
        /// Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
        /// </summary>
        [Output("attributes")]
        public Output<ImmutableDictionary<string, string>?> Attributes { get; private set; } = null!;

        /// <summary>
        /// Optional compliance metadata such as the privacy policy version and GPC signal.
        /// </summary>
        [Output("compliance")]
        public Output<Outputs.ConsentCompliance?> Compliance { get; private set; } = null!;

        /// <summary>
        /// Synthetic identifier used by Pulumi to track consent submissions.
        /// </summary>
        [Output("consentId")]
        public Output<string> ConsentId { get; private set; } = null!;

        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
        /// </summary>
        [Output("countryCodeOverride")]
        public Output<string?> CountryCodeOverride { get; private set; } = null!;

        /// <summary>
        /// The actions Osano derived for a GPC consent submitted without actions.
        /// </summary>
        [Output("gpcActions")]
        public Output<ImmutableArray<Outputs.ConsentAction>> GpcActions { get; private set; } = null!;

        /// <summary>
        /// Optional jurisdiction, which must be one of the configuration's jurisdictions (see getCollections).
        /// </summary>
        [Output("jurisdiction")]
        public Output<string?> Jurisdiction { get; private set; } = null!;

        /// <summary>
        /// Timestamp of the last refresh from the Osano API (RFC3339).
        /// </summary>
        [Output("lastSynced")]
        public Output<string> LastSynced { get; private set; } = null!;

        /// <summary>
        /// Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano's GPC endpoint, which derives the actions.
        /// </summary>
        [Output("origin")]
        public Output<string?> Origin { get; private set; } = null!;

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Output("regionCodeOverride")]
        public Output<string?> RegionCodeOverride { get; private set; } = null!;

        /// <summary>
        /// Optional session token returned when the subject's profile was created.
        /// </summary>
        [Output("sessionToken")]
        public Output<string?> SessionToken { get; private set; } = null!;

        /// <summary>
        /// Subject identifiers used for the consent (verifiedId or anonymousId).
        /// </summary>
        [Output("subject")]
        public Output<Outputs.ConsentSubject> Subject { get; private set; } = null!;

        /// <summary>
        /// Custom tags that Osano associates with the consent record.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a Consent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Consent(string name, ConsentArgs args, CustomResourceOptions? options = null)
            : base("osano:index:Consent", name, args ?? new ConsentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Consent(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("osano:index:Consent", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jflavan/pulumi-osano",
                AdditionalSecretOutputs =
                {
                    "sessionToken",
                },
                ReplaceOnChanges =
                {
                    "actions[*]",
                    "attributes.*",
                    "compliance",
                    "countryCodeOverride",
                    "jurisdiction",
                    "origin",
                    "regionCodeOverride",
                    "sessionToken",
                    "subject",
                    "tags[*]",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Consent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Consent Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Consent(name, id, options);
        }
    }

    public sealed class ConsentArgs : global::Pulumi.ResourceArgs
    {
        [Input("actions")]
        private InputList<Inputs.ConsentActionArgs>? _actions;

        /// <summary>
        /// Consent actions referencing privacy protocols (target) within a configuration (vendor). Required unless origin is gpc.
        /// </summary>
        public InputList<Inputs.ConsentActionArgs> Actions
        {
            get => _actions ?? (_actions = new InputList<Inputs.ConsentActionArgs>());
            set => _actions = value;
        }

        [Input("attributes")]
        private InputMap<string>? _attributes;

        /// <summary>
        /// Optional key/value attributes stored with the consent record. Osano fills ipAddress and userAgent itself and overwrites values sent for those keys.
        /// </summary>
        public InputMap<string> Attributes
        {
            get => _attributes ?? (_attributes = new InputMap<string>());
            set => _attributes = value;
        }

        /// <summary>
        /// Optional compliance metadata such as the privacy policy version and GPC signal.
        /// </summary>
        [Input("compliance")]
        public Input<Inputs.ConsentComplianceArgs>? Compliance { get; set; }

        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address. Set it when submitting from a pipeline, whose IP address says nothing about the subject.
        /// </summary>
        [Input("countryCodeOverride")]
        public Input<string>? CountryCodeOverride { get; set; }

        /// <summary>
        /// Optional jurisdiction, which must be one of the configuration's jurisdictions (see getCollections).
        /// </summary>
        [Input("jurisdiction")]
        public Input<string>? Jurisdiction { get; set; }

        /// <summary>
        /// Origin of the consent: api (default) or gpc. With gpc and no actions, the consent is submitted to Osano's GPC endpoint, which derives the actions.
        /// </summary>
        [Input("origin")]
        public Input<string>? Origin { get; set; }

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Input("regionCodeOverride")]
        public Input<string>? RegionCodeOverride { get; set; }

        [Input("sessionToken")]
        private Input<string>? _sessionToken;

        /// <summary>
        /// Optional session token returned when the subject's profile was created.
        /// </summary>
        public Input<string>? SessionToken
        {
            get => _sessionToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sessionToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Subject identifiers used for the consent (verifiedId or anonymousId).
        /// </summary>
        [Input("subject", required: true)]
        public Input<Inputs.ConsentSubjectArgs> Subject { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Custom tags that Osano associates with the consent record.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ConsentArgs()
        {
        }
        public static new ConsentArgs Empty => new ConsentArgs();
    }
}
