// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetConfig
    {
        /// <summary>
        /// Retrieves the Unified Consent configuration referenced by the API key.
        /// </summary>
        public static Task<GetConfigResult> InvokeAsync(GetConfigArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetConfigResult>("osano:index:getConfig", args ?? new GetConfigArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves the Unified Consent configuration referenced by the API key.
        /// </summary>
        public static Output<GetConfigResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetConfigResult>("osano:index:getConfig", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Retrieves the Unified Consent configuration referenced by the API key.
        /// </summary>
        public static Output<GetConfigResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetConfigResult>("osano:index:getConfig", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetConfigArgs : global::Pulumi.InvokeArgs
    {
        public GetConfigArgs()
        {
        }
        public static new GetConfigArgs Empty => new GetConfigArgs();
    }


    [OutputType]
    public sealed class GetConfigResult
    {
        public readonly ImmutableDictionary<string, object> Config;

        [OutputConstructor]
        private GetConfigResult(ImmutableDictionary<string, object> config)
        {
            Config = config;
        }
    }
}
