// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetCollection
    {
        /// <summary>
        /// Retrieves a specific privacy protocol collection by ID.
        /// </summary>
        public static Task<GetCollectionResult> InvokeAsync(GetCollectionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCollectionResult>("osano:index:getCollection", args ?? new GetCollectionArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific privacy protocol collection by ID.
        /// </summary>
        public static Output<GetCollectionResult> Invoke(GetCollectionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionResult>("osano:index:getCollection", args ?? new GetCollectionInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific privacy protocol collection by ID.
        /// </summary>
        public static Output<GetCollectionResult> Invoke(GetCollectionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionResult>("osano:index:getCollection", args ?? new GetCollectionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCollectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("collectionId", required: true)]
        public string CollectionId { get; set; } = null!;

        public GetCollectionArgs()
        {
        }
        public static new GetCollectionArgs Empty => new GetCollectionArgs();
    }

    public sealed class GetCollectionInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("collectionId", required: true)]
        public Input<string> CollectionId { get; set; } = null!;

        public GetCollectionInvokeArgs()
        {
        }
        public static new GetCollectionInvokeArgs Empty => new GetCollectionInvokeArgs();
    }


    [OutputType]
    public sealed class GetCollectionResult
    {
        public readonly ImmutableDictionary<string, object> Collection;
        public readonly string CollectionId;
        public readonly bool Exists;

        [OutputConstructor]
        private GetCollectionResult(
            ImmutableDictionary<string, object> collection,

            string collectionId,

            bool exists)
        {
            Collection = collection;
            CollectionId = collectionId;
            Exists = exists;
        }
    }
}
