// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetConsentProfile
    {
        /// <summary>
        /// Retrieves a consent profile for a hashed subject identifier and config ID.
        /// </summary>
        public static Task<GetConsentProfileResult> InvokeAsync(GetConsentProfileArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetConsentProfileResult>("osano:index:getConsentProfile", args ?? new GetConsentProfileArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a consent profile for a hashed subject identifier and config ID.
        /// </summary>
        public static Output<GetConsentProfileResult> Invoke(GetConsentProfileInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetConsentProfileResult>("osano:index:getConsentProfile", args ?? new GetConsentProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a consent profile for a hashed subject identifier and config ID.
        /// </summary>
        public static Output<GetConsentProfileResult> Invoke(GetConsentProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetConsentProfileResult>("osano:index:getConsentProfile", args ?? new GetConsentProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetConsentProfileArgs : global::Pulumi.InvokeArgs
    {
        [Input("configId", required: true)]
        public string ConfigId { get; set; } = null!;

        [Input("hashedSubjectId", required: true)]
        public string HashedSubjectId { get; set; } = null!;

        public GetConsentProfileArgs()
        {
        }
        public static new GetConsentProfileArgs Empty => new GetConsentProfileArgs();
    }

    public sealed class GetConsentProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("configId", required: true)]
        public Input<string> ConfigId { get; set; } = null!;

        [Input("hashedSubjectId", required: true)]
        public Input<string> HashedSubjectId { get; set; } = null!;

        public GetConsentProfileInvokeArgs()
        {
        }
        public static new GetConsentProfileInvokeArgs Empty => new GetConsentProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetConsentProfileResult
    {
        public readonly string ConfigId;
        public readonly bool Exists;
        public readonly string HashedSubjectId;
        public readonly ImmutableDictionary<string, object> Profile;

        [OutputConstructor]
        private GetConsentProfileResult(
            string configId,

            bool exists,

            string hashedSubjectId,

            ImmutableDictionary<string, object> profile)
        {
            ConfigId = configId;
            Exists = exists;
            HashedSubjectId = hashedSubjectId;
            Profile = profile;
        }
    }
}
