// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetCookieConsentConfigs
    {
        /// <summary>
        /// Lists Cookie Consent configurations, optionally filtered by name, domains, organization, mode, or publish status, and returns each one's install script. Follows pagination until maxResults or the last page.
        /// </summary>
        public static Task<GetCookieConsentConfigsResult> InvokeAsync(GetCookieConsentConfigsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCookieConsentConfigsResult>("osano:index:getCookieConsentConfigs", args ?? new GetCookieConsentConfigsArgs(), options.WithDefaults());

        /// <summary>
        /// Lists Cookie Consent configurations, optionally filtered by name, domains, organization, mode, or publish status, and returns each one's install script. Follows pagination until maxResults or the last page.
        /// </summary>
        public static Output<GetCookieConsentConfigsResult> Invoke(GetCookieConsentConfigsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCookieConsentConfigsResult>("osano:index:getCookieConsentConfigs", args ?? new GetCookieConsentConfigsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Lists Cookie Consent configurations, optionally filtered by name, domains, organization, mode, or publish status, and returns each one's install script. Follows pagination until maxResults or the last page.
        /// </summary>
        public static Output<GetCookieConsentConfigsResult> Invoke(GetCookieConsentConfigsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCookieConsentConfigsResult>("osano:index:getCookieConsentConfigs", args ?? new GetCookieConsentConfigsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCookieConsentConfigsArgs : global::Pulumi.InvokeArgs
    {
        [Input("domains")]
        private List<string>? _domains;

        /// <summary>
        /// Filter by domains. Use Punycode for non-ASCII domains.
        /// </summary>
        public List<string> Domains
        {
            get => _domains ?? (_domains = new List<string>());
            set => _domains = value;
        }

        /// <summary>
        /// How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
        /// </summary>
        [Input("domainsMatch")]
        public string? DomainsMatch { get; set; }

        /// <summary>
        /// Stop after this many configurations. Unset or 0 returns every matching configuration.
        /// </summary>
        [Input("maxResults")]
        public int? MaxResults { get; set; }

        /// <summary>
        /// Filter by compliance mode: debug, permissive, or production.
        /// </summary>
        [Input("mode")]
        public string? Mode { get; set; }

        /// <summary>
        /// Filter by configuration name (case insensitive, partial matches allowed).
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        [Input("orgIds")]
        private List<string>? _orgIds;

        /// <summary>
        /// Filter by organization IDs (UUIDs).
        /// </summary>
        public List<string> OrgIds
        {
            get => _orgIds ?? (_orgIds = new List<string>());
            set => _orgIds = value;
        }

        /// <summary>
        /// How orgIds filters: any (default), all, or not, as for domainsMatch.
        /// </summary>
        [Input("orgIdsMatch")]
        public string? OrgIdsMatch { get; set; }

        /// <summary>
        /// Filter by publish status: unpublished, in-progress, published, outdated, or error.
        /// </summary>
        [Input("publishStatus")]
        public string? PublishStatus { get; set; }

        /// <summary>
        /// Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
        /// </summary>
        [Input("sortBy")]
        public string? SortBy { get; set; }

        /// <summary>
        /// Filter by whether discovery recording is stopped.
        /// </summary>
        [Input("tattleRecordStopped")]
        public bool? TattleRecordStopped { get; set; }

        public GetCookieConsentConfigsArgs()
        {
        }
        public static new GetCookieConsentConfigsArgs Empty => new GetCookieConsentConfigsArgs();
    }

    public sealed class GetCookieConsentConfigsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Filter by domains. Use Punycode for non-ASCII domains.
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
        /// </summary>
        [Input("domainsMatch")]
        public Input<string>? DomainsMatch { get; set; }

        /// <summary>
        /// Stop after this many configurations. Unset or 0 returns every matching configuration.
        /// </summary>
        [Input("maxResults")]
        public Input<int>? MaxResults { get; set; }

        /// <summary>
        /// Filter by compliance mode: debug, permissive, or production.
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// Filter by configuration name (case insensitive, partial matches allowed).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("orgIds")]
        private InputList<string>? _orgIds;

        /// <summary>
        /// Filter by organization IDs (UUIDs).
        /// </summary>
        public InputList<string> OrgIds
        {
            get => _orgIds ?? (_orgIds = new InputList<string>());
            set => _orgIds = value;
        }

        /// <summary>
        /// How orgIds filters: any (default), all, or not, as for domainsMatch.
        /// </summary>
        [Input("orgIdsMatch")]
        public Input<string>? OrgIdsMatch { get; set; }

        /// <summary>
        /// Filter by publish status: unpublished, in-progress, published, outdated, or error.
        /// </summary>
        [Input("publishStatus")]
        public Input<string>? PublishStatus { get; set; }

        /// <summary>
        /// Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
        /// </summary>
        [Input("sortBy")]
        public Input<string>? SortBy { get; set; }

        /// <summary>
        /// Filter by whether discovery recording is stopped.
        /// </summary>
        [Input("tattleRecordStopped")]
        public Input<bool>? TattleRecordStopped { get; set; }

        public GetCookieConsentConfigsInvokeArgs()
        {
        }
        public static new GetCookieConsentConfigsInvokeArgs Empty => new GetCookieConsentConfigsInvokeArgs();
    }


    [OutputType]
    public sealed class GetCookieConsentConfigsResult
    {
        /// <summary>
        /// The matching configurations, each with its install script.
        /// </summary>
        public readonly ImmutableArray<Outputs.CookieConsentConfigDetails> Configs;

        [OutputConstructor]
        private GetCookieConsentConfigsResult(ImmutableArray<Outputs.CookieConsentConfigDetails> configs)
        {
            Configs = configs;
        }
    }
}
