// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetCollections
    {
        /// <summary>
        /// Retrieves the aggregated privacy protocol collections for an optional jurisdiction and version (published/draft).
        /// </summary>
        public static Task<GetCollectionsResult> InvokeAsync(GetCollectionsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCollectionsResult>("osano:index:getCollections", args ?? new GetCollectionsArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves the aggregated privacy protocol collections for an optional jurisdiction and version (published/draft).
        /// </summary>
        public static Output<GetCollectionsResult> Invoke(GetCollectionsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionsResult>("osano:index:getCollections", args ?? new GetCollectionsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves the aggregated privacy protocol collections for an optional jurisdiction and version (published/draft).
        /// </summary>
        public static Output<GetCollectionsResult> Invoke(GetCollectionsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionsResult>("osano:index:getCollections", args ?? new GetCollectionsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCollectionsArgs : global::Pulumi.InvokeArgs
    {
        [Input("jurisdiction")]
        public string? Jurisdiction { get; set; }

        [Input("type")]
        public string? Type { get; set; }

        public GetCollectionsArgs()
        {
        }
        public static new GetCollectionsArgs Empty => new GetCollectionsArgs();
    }

    public sealed class GetCollectionsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("jurisdiction")]
        public Input<string>? Jurisdiction { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetCollectionsInvokeArgs()
        {
        }
        public static new GetCollectionsInvokeArgs Empty => new GetCollectionsInvokeArgs();
    }


    [OutputType]
    public sealed class GetCollectionsResult
    {
        public readonly ImmutableDictionary<string, object> Collection;
        public readonly ImmutableArray<string> Jurisdictions;

        [OutputConstructor]
        private GetCollectionsResult(
            ImmutableDictionary<string, object> collection,

            ImmutableArray<string> jurisdictions)
        {
            Collection = collection;
            Jurisdictions = jurisdictions;
        }
    }
}
