// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetCookieConsentConfig
    {
        /// <summary>
        /// Reads a Cookie Consent configuration, including its publish status and the CMP script to install, without managing it. Use it to fetch the script for a configuration another stack or the Osano dashboard owns. The script serves the most recently published revision, so check publishStatus and lastPublished before relying on a new change.
        /// </summary>
        public static Task<GetCookieConsentConfigResult> InvokeAsync(GetCookieConsentConfigArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCookieConsentConfigResult>("osano:index:getCookieConsentConfig", args ?? new GetCookieConsentConfigArgs(), options.WithDefaults());

        /// <summary>
        /// Reads a Cookie Consent configuration, including its publish status and the CMP script to install, without managing it. Use it to fetch the script for a configuration another stack or the Osano dashboard owns. The script serves the most recently published revision, so check publishStatus and lastPublished before relying on a new change.
        /// </summary>
        public static Output<GetCookieConsentConfigResult> Invoke(GetCookieConsentConfigInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCookieConsentConfigResult>("osano:index:getCookieConsentConfig", args ?? new GetCookieConsentConfigInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Reads a Cookie Consent configuration, including its publish status and the CMP script to install, without managing it. Use it to fetch the script for a configuration another stack or the Osano dashboard owns. The script serves the most recently published revision, so check publishStatus and lastPublished before relying on a new change.
        /// </summary>
        public static Output<GetCookieConsentConfigResult> Invoke(GetCookieConsentConfigInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCookieConsentConfigResult>("osano:index:getCookieConsentConfig", args ?? new GetCookieConsentConfigInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCookieConsentConfigArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Osano Cookie Consent config ID (UUID) to read.
        /// </summary>
        [Input("configId", required: true)]
        public string ConfigId { get; set; } = null!;

        public GetCookieConsentConfigArgs()
        {
        }
        public static new GetCookieConsentConfigArgs Empty => new GetCookieConsentConfigArgs();
    }

    public sealed class GetCookieConsentConfigInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Osano Cookie Consent config ID (UUID) to read.
        /// </summary>
        [Input("configId", required: true)]
        public Input<string> ConfigId { get; set; } = null!;

        public GetCookieConsentConfigInvokeArgs()
        {
        }
        public static new GetCookieConsentConfigInvokeArgs Empty => new GetCookieConsentConfigInvokeArgs();
    }


    [OutputType]
    public sealed class GetCookieConsentConfigResult
    {
        /// <summary>
        /// The config ID that was looked up.
        /// </summary>
        public readonly string ConfigId;
        /// <summary>
        /// The CMP configuration object as Osano reports it, including server defaults.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Configuration;
        /// <summary>
        /// Unix timestamp when Osano created the configuration.
        /// </summary>
        public readonly int Created;
        /// <summary>
        /// The Osano customer ID that owns the configuration.
        /// </summary>
        public readonly string CustomerId;
        /// <summary>
        /// Domains permitted to host the configuration.
        /// </summary>
        public readonly ImmutableArray<string> Domains;
        /// <summary>
        /// Whether Osano returned the configuration. The other outputs are empty when false.
        /// </summary>
        public readonly bool Exists;
        /// <summary>
        /// Unix timestamp when Osano last published the configuration (0 if never).
        /// </summary>
        public readonly int LastPublished;
        /// <summary>
        /// Compliance mode: debug, permissive, or production.
        /// </summary>
        public readonly string Mode;
        /// <summary>
        /// The configuration name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Organization IDs associated with the configuration.
        /// </summary>
        public readonly ImmutableArray<string> OrgIds;
        /// <summary>
        /// Osano publication status: unpublished, in-progress, published, outdated (changed since the last publish), or error.
        /// </summary>
        public readonly string PublishStatus;
        /// <summary>
        /// Revision number most recently published by Osano.
        /// </summary>
        public readonly int PublishedRevision;
        /// <summary>
        /// The public hosted CMP JavaScript URL, https://cmp.osano.com/{customerId}/{configId}/osano.js. It serves the most recently published revision.
        /// </summary>
        public readonly string ScriptSrc;
        /// <summary>
        /// The complete public CMP script tag to place first in the site head, without async or defer attributes.
        /// </summary>
        public readonly string ScriptTag;
        /// <summary>
        /// Whether Osano stopped recording discoveries (tattles) for the configuration.
        /// </summary>
        public readonly bool TattleRecordStopped;
        /// <summary>
        /// Unix timestamp when Osano last updated the configuration.
        /// </summary>
        public readonly int Updated;

        [OutputConstructor]
        private GetCookieConsentConfigResult(
            string configId,

            ImmutableDictionary<string, object> configuration,

            int created,

            string customerId,

            ImmutableArray<string> domains,

            bool exists,

            int lastPublished,

            string mode,

            string name,

            ImmutableArray<string> orgIds,

            string publishStatus,

            int publishedRevision,

            string scriptSrc,

            string scriptTag,

            bool tattleRecordStopped,

            int updated)
        {
            ConfigId = configId;
            Configuration = configuration;
            Created = created;
            CustomerId = customerId;
            Domains = domains;
            Exists = exists;
            LastPublished = lastPublished;
            Mode = mode;
            Name = name;
            OrgIds = orgIds;
            PublishStatus = publishStatus;
            PublishedRevision = publishedRevision;
            ScriptSrc = scriptSrc;
            ScriptTag = scriptTag;
            TattleRecordStopped = tattleRecordStopped;
            Updated = updated;
        }
    }
}
