// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetSubjectProfile
    {
        /// <summary>
        /// Reads a subject's profile (email and subject ID) using the Unified Consent API key. The outputs are secrets because they hold personal data.
        /// </summary>
        public static Task<GetSubjectProfileResult> InvokeAsync(GetSubjectProfileArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSubjectProfileResult>("osano:index:getSubjectProfile", args ?? new GetSubjectProfileArgs(), options.WithDefaults());

        /// <summary>
        /// Reads a subject's profile (email and subject ID) using the Unified Consent API key. The outputs are secrets because they hold personal data.
        /// </summary>
        public static Output<GetSubjectProfileResult> Invoke(GetSubjectProfileInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubjectProfileResult>("osano:index:getSubjectProfile", args ?? new GetSubjectProfileInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Reads a subject's profile (email and subject ID) using the Unified Consent API key. The outputs are secrets because they hold personal data.
        /// </summary>
        public static Output<GetSubjectProfileResult> Invoke(GetSubjectProfileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubjectProfileResult>("osano:index:getSubjectProfile", args ?? new GetSubjectProfileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSubjectProfileArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The subject ID whose profile is returned.
        /// </summary>
        [Input("subjectId", required: true)]
        public string SubjectId { get; set; } = null!;

        public GetSubjectProfileArgs()
        {
        }
        public static new GetSubjectProfileArgs Empty => new GetSubjectProfileArgs();
    }

    public sealed class GetSubjectProfileInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The subject ID whose profile is returned.
        /// </summary>
        [Input("subjectId", required: true)]
        public Input<string> SubjectId { get; set; } = null!;

        public GetSubjectProfileInvokeArgs()
        {
        }
        public static new GetSubjectProfileInvokeArgs Empty => new GetSubjectProfileInvokeArgs();
    }


    [OutputType]
    public sealed class GetSubjectProfileResult
    {
        /// <summary>
        /// The subject's email address. Secret, because it is personal data.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// Whether Osano returned a profile for the subject.
        /// </summary>
        public readonly bool Exists;
        /// <summary>
        /// The complete profile Osano returned. Secret, because it is personal data.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Profile;
        /// <summary>
        /// The subject ID that was looked up.
        /// </summary>
        public readonly string SubjectId;

        [OutputConstructor]
        private GetSubjectProfileResult(
            string email,

            bool exists,

            ImmutableDictionary<string, object> profile,

            string subjectId)
        {
            Email = email;
            Exists = exists;
            Profile = profile;
            SubjectId = subjectId;
        }
    }
}
