// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetUnifiedConsent
    {
        /// <summary>
        /// Fetches the unified consent state for a subject reference using the Unified Consent API key.
        /// </summary>
        public static Task<GetUnifiedConsentResult> InvokeAsync(GetUnifiedConsentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUnifiedConsentResult>("osano:index:getUnifiedConsent", args ?? new GetUnifiedConsentArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches the unified consent state for a subject reference using the Unified Consent API key.
        /// </summary>
        public static Output<GetUnifiedConsentResult> Invoke(GetUnifiedConsentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUnifiedConsentResult>("osano:index:getUnifiedConsent", args ?? new GetUnifiedConsentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches the unified consent state for a subject reference using the Unified Consent API key.
        /// </summary>
        public static Output<GetUnifiedConsentResult> Invoke(GetUnifiedConsentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetUnifiedConsentResult>("osano:index:getUnifiedConsent", args ?? new GetUnifiedConsentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUnifiedConsentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address, which in a pipeline is the CI runner's.
        /// </summary>
        [Input("countryCodeOverride")]
        public string? CountryCodeOverride { get; set; }

        /// <summary>
        /// Reference type: subject (default) for a subject's verified or anonymous ID, or session for a session ID. anonymous is accepted as a deprecated alias of subject.
        /// </summary>
        [Input("referenceType")]
        public string? ReferenceType { get; set; }

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Input("regionCodeOverride")]
        public string? RegionCodeOverride { get; set; }

        /// <summary>
        /// The subject reference to look up: an anonymous ID, verified ID, or session ID.
        /// </summary>
        [Input("subjectRef", required: true)]
        public string SubjectRef { get; set; } = null!;

        public GetUnifiedConsentArgs()
        {
        }
        public static new GetUnifiedConsentArgs Empty => new GetUnifiedConsentArgs();
    }

    public sealed class GetUnifiedConsentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address, which in a pipeline is the CI runner's.
        /// </summary>
        [Input("countryCodeOverride")]
        public Input<string>? CountryCodeOverride { get; set; }

        /// <summary>
        /// Reference type: subject (default) for a subject's verified or anonymous ID, or session for a session ID. anonymous is accepted as a deprecated alias of subject.
        /// </summary>
        [Input("referenceType")]
        public Input<string>? ReferenceType { get; set; }

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Input("regionCodeOverride")]
        public Input<string>? RegionCodeOverride { get; set; }

        /// <summary>
        /// The subject reference to look up: an anonymous ID, verified ID, or session ID.
        /// </summary>
        [Input("subjectRef", required: true)]
        public Input<string> SubjectRef { get; set; } = null!;

        public GetUnifiedConsentInvokeArgs()
        {
        }
        public static new GetUnifiedConsentInvokeArgs Empty => new GetUnifiedConsentInvokeArgs();
    }


    [OutputType]
    public sealed class GetUnifiedConsentResult
    {
        /// <summary>
        /// Conflicting consents Osano resolved, with the resolution and the actions in conflict.
        /// </summary>
        public readonly ImmutableArray<ImmutableDictionary<string, object>> Conflicts;
        /// <summary>
        /// Whether Osano has any consent for the subject.
        /// </summary>
        public readonly bool Exists;
        /// <summary>
        /// The subject reference that was looked up.
        /// </summary>
        public readonly string SubjectRef;
        /// <summary>
        /// The merged consent: subjectId, brandId, channelIds, jurisdiction, lastUpdateDate, lastConflictDate, actions, attributes, compliance, and tags.
        /// </summary>
        public readonly ImmutableDictionary<string, object> UnifiedConsent;

        [OutputConstructor]
        private GetUnifiedConsentResult(
            ImmutableArray<ImmutableDictionary<string, object>> conflicts,

            bool exists,

            string subjectRef,

            ImmutableDictionary<string, object> unifiedConsent)
        {
            Conflicts = conflicts;
            Exists = exists;
            SubjectRef = subjectRef;
            UnifiedConsent = unifiedConsent;
        }
    }
}
