// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class VerifySubjectCode
    {
        /// <summary>
        /// Verifies a subject profile using the code sent via email or SMS. Pulumi runs invokes on every preview, update, and refresh, and one-time codes cannot be reused, so call this from automation rather than from long-lived stack code.
        /// </summary>
        public static Task<VerifySubjectCodeResult> InvokeAsync(VerifySubjectCodeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<VerifySubjectCodeResult>("osano:index:verifySubjectCode", args ?? new VerifySubjectCodeArgs(), options.WithDefaults());

        /// <summary>
        /// Verifies a subject profile using the code sent via email or SMS. Pulumi runs invokes on every preview, update, and refresh, and one-time codes cannot be reused, so call this from automation rather than from long-lived stack code.
        /// </summary>
        public static Output<VerifySubjectCodeResult> Invoke(VerifySubjectCodeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<VerifySubjectCodeResult>("osano:index:verifySubjectCode", args ?? new VerifySubjectCodeInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Verifies a subject profile using the code sent via email or SMS. Pulumi runs invokes on every preview, update, and refresh, and one-time codes cannot be reused, so call this from automation rather than from long-lived stack code.
        /// </summary>
        public static Output<VerifySubjectCodeResult> Invoke(VerifySubjectCodeInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<VerifySubjectCodeResult>("osano:index:verifySubjectCode", args ?? new VerifySubjectCodeInvokeArgs(), options.WithDefaults());
    }


    public sealed class VerifySubjectCodeArgs : global::Pulumi.InvokeArgs
    {
        [Input("code", required: true)]
        private string? _code;

        /// <summary>
        /// The one-time verification code the subject received.
        /// </summary>
        public string? Code
        {
            get => _code;
            set => _code = value;
        }

        /// <summary>
        /// Email address the code was sent to. Set exactly one of email or phone.
        /// </summary>
        [Input("email")]
        public string? Email { get; set; }

        /// <summary>
        /// The hashed subject identifier being verified.
        /// </summary>
        [Input("hashedSubjectId", required: true)]
        public string HashedSubjectId { get; set; } = null!;

        /// <summary>
        /// Phone number the code was sent to. Set exactly one of email or phone.
        /// </summary>
        [Input("phone")]
        public string? Phone { get; set; }

        public VerifySubjectCodeArgs()
        {
        }
        public static new VerifySubjectCodeArgs Empty => new VerifySubjectCodeArgs();
    }

    public sealed class VerifySubjectCodeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("code", required: true)]
        private Input<string>? _code;

        /// <summary>
        /// The one-time verification code the subject received.
        /// </summary>
        public Input<string>? Code
        {
            get => _code;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _code = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Email address the code was sent to. Set exactly one of email or phone.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// The hashed subject identifier being verified.
        /// </summary>
        [Input("hashedSubjectId", required: true)]
        public Input<string> HashedSubjectId { get; set; } = null!;

        /// <summary>
        /// Phone number the code was sent to. Set exactly one of email or phone.
        /// </summary>
        [Input("phone")]
        public Input<string>? Phone { get; set; }

        public VerifySubjectCodeInvokeArgs()
        {
        }
        public static new VerifySubjectCodeInvokeArgs Empty => new VerifySubjectCodeInvokeArgs();
    }


    [OutputType]
    public sealed class VerifySubjectCodeResult
    {
        public readonly string Channel;
        public readonly string Destination;
        public readonly string HashedSubjectId;
        public readonly ImmutableDictionary<string, object> Profile;
        public readonly bool Verified;

        [OutputConstructor]
        private VerifySubjectCodeResult(
            string channel,

            string destination,

            string hashedSubjectId,

            ImmutableDictionary<string, object> profile,

            bool verified)
        {
            Channel = channel;
            Destination = destination;
            HashedSubjectId = hashedSubjectId;
            Profile = profile;
            Verified = verified;
        }
    }
}
