// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConsentSubject {
    /**
     * @return The subject&#39;s anonymous ID. Must not contain #, %, or spaces.
     *
     */
    private @Nullable String anonymousId;
    /**
     * @return The subject&#39;s verified ID. Must not contain #, %, or spaces.
     *
     */
    private @Nullable String verifiedId;

    private ConsentSubject() {}
    /**
     * @return The subject&#39;s anonymous ID. Must not contain #, %, or spaces.
     *
     */
    public Optional<String> anonymousId() {
        return Optional.ofNullable(this.anonymousId);
    }
    /**
     * @return The subject&#39;s verified ID. Must not contain #, %, or spaces.
     *
     */
    public Optional<String> verifiedId() {
        return Optional.ofNullable(this.verifiedId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConsentSubject defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String anonymousId;
        private @Nullable String verifiedId;
        public Builder() {}
        public Builder(ConsentSubject defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.anonymousId = defaults.anonymousId;
    	      this.verifiedId = defaults.verifiedId;
        }

        @CustomType.Setter
        public Builder anonymousId(@Nullable String anonymousId) {

            this.anonymousId = anonymousId;
            return this;
        }
        @CustomType.Setter
        public Builder verifiedId(@Nullable String verifiedId) {

            this.verifiedId = verifiedId;
            return this;
        }
        public ConsentSubject build() {
            final var _resultValue = new ConsentSubject();
            _resultValue.anonymousId = anonymousId;
            _resultValue.verifiedId = verifiedId;
            return _resultValue;
        }
    }
}
