// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jflavan.pulumi.osano.outputs.CookieConsentAuditResource;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CookieConsentAuditEvent {
    /**
     * @return The email of the user who performed the action, when known.
     *
     */
    private @Nullable String actor;
    /**
     * @return The machine-readable event type, such as cmp.configPublished.
     *
     */
    private String eventType;
    /**
     * @return The audit event ID.
     *
     */
    private String id;
    /**
     * @return Event-specific details, such as changed fields and before/after values.
     *
     */
    private @Nullable Map<String,Object> metadata;
    /**
     * @return The Osano module, currently always CMP.
     *
     */
    private String module;
    /**
     * @return The resources the event acted on.
     *
     */
    private List<CookieConsentAuditResource> resources;
    /**
     * @return When the event occurred (UTC ISO 8601).
     *
     */
    private String timestamp;

    private CookieConsentAuditEvent() {}
    /**
     * @return The email of the user who performed the action, when known.
     *
     */
    public Optional<String> actor() {
        return Optional.ofNullable(this.actor);
    }
    /**
     * @return The machine-readable event type, such as cmp.configPublished.
     *
     */
    public String eventType() {
        return this.eventType;
    }
    /**
     * @return The audit event ID.
     *
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Event-specific details, such as changed fields and before/after values.
     *
     */
    public Map<String,Object> metadata() {
        return this.metadata == null ? Map.of() : this.metadata;
    }
    /**
     * @return The Osano module, currently always CMP.
     *
     */
    public String module() {
        return this.module;
    }
    /**
     * @return The resources the event acted on.
     *
     */
    public List<CookieConsentAuditResource> resources() {
        return this.resources;
    }
    /**
     * @return When the event occurred (UTC ISO 8601).
     *
     */
    public String timestamp() {
        return this.timestamp;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CookieConsentAuditEvent defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String actor;
        private String eventType;
        private String id;
        private @Nullable Map<String,Object> metadata;
        private String module;
        private List<CookieConsentAuditResource> resources;
        private String timestamp;
        public Builder() {}
        public Builder(CookieConsentAuditEvent defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actor = defaults.actor;
    	      this.eventType = defaults.eventType;
    	      this.id = defaults.id;
    	      this.metadata = defaults.metadata;
    	      this.module = defaults.module;
    	      this.resources = defaults.resources;
    	      this.timestamp = defaults.timestamp;
        }

        @CustomType.Setter
        public Builder actor(@Nullable String actor) {

            this.actor = actor;
            return this;
        }
        @CustomType.Setter
        public Builder eventType(String eventType) {
            if (eventType == null) {
              throw new MissingRequiredPropertyException("CookieConsentAuditEvent", "eventType");
            }
            this.eventType = eventType;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("CookieConsentAuditEvent", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(@Nullable Map<String,Object> metadata) {

            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder module(String module) {
            if (module == null) {
              throw new MissingRequiredPropertyException("CookieConsentAuditEvent", "module");
            }
            this.module = module;
            return this;
        }
        @CustomType.Setter
        public Builder resources(List<CookieConsentAuditResource> resources) {
            if (resources == null) {
              throw new MissingRequiredPropertyException("CookieConsentAuditEvent", "resources");
            }
            this.resources = resources;
            return this;
        }
        public Builder resources(CookieConsentAuditResource... resources) {
            return resources(List.of(resources));
        }
        @CustomType.Setter
        public Builder timestamp(String timestamp) {
            if (timestamp == null) {
              throw new MissingRequiredPropertyException("CookieConsentAuditEvent", "timestamp");
            }
            this.timestamp = timestamp;
            return this;
        }
        public CookieConsentAuditEvent build() {
            final var _resultValue = new CookieConsentAuditEvent();
            _resultValue.actor = actor;
            _resultValue.eventType = eventType;
            _resultValue.id = id;
            _resultValue.metadata = metadata;
            _resultValue.module = module;
            _resultValue.resources = resources;
            _resultValue.timestamp = timestamp;
            return _resultValue;
        }
    }
}
