// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CookieConsentRuleDetails {
    /**
     * @return The rule classification.
     *
     */
    private String classification;
    /**
     * @return The configuration the rule belongs to.
     *
     */
    private String configId;
    /**
     * @return When the rule was created (ISO 8601).
     *
     */
    private String created;
    /**
     * @return The cookie description, if set (cookies only).
     *
     */
    private @Nullable String description;
    /**
     * @return Whether the rule is disclosed.
     *
     */
    private Boolean disclosure;
    /**
     * @return The cookie expiry description, if set (cookies only).
     *
     */
    private @Nullable String expiry;
    /**
     * @return The rule pattern.
     *
     */
    private String rule;
    /**
     * @return The server-assigned integer rule ID. Import a rule with &lt;configId&gt;/&lt;ruleId&gt;.
     *
     */
    private Integer ruleId;
    /**
     * @return The matching mode, if set.
     *
     */
    private @Nullable String ruleType;
    /**
     * @return The storage type: cookies, scripts, iframes, or localStorage. Osano&#39;s raw type is passed through when it is not one of these.
     *
     */
    private String storeType;
    /**
     * @return The disclosure title, if set.
     *
     */
    private @Nullable String title;
    /**
     * @return When the rule was last updated (ISO 8601).
     *
     */
    private String updated;
    /**
     * @return The Osano vendor ID, if set.
     *
     */
    private @Nullable String vendorId;
    /**
     * @return The vendor name, if set.
     *
     */
    private @Nullable String vendorName;

    private CookieConsentRuleDetails() {}
    /**
     * @return The rule classification.
     *
     */
    public String classification() {
        return this.classification;
    }
    /**
     * @return The configuration the rule belongs to.
     *
     */
    public String configId() {
        return this.configId;
    }
    /**
     * @return When the rule was created (ISO 8601).
     *
     */
    public String created() {
        return this.created;
    }
    /**
     * @return The cookie description, if set (cookies only).
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return Whether the rule is disclosed.
     *
     */
    public Boolean disclosure() {
        return this.disclosure;
    }
    /**
     * @return The cookie expiry description, if set (cookies only).
     *
     */
    public Optional<String> expiry() {
        return Optional.ofNullable(this.expiry);
    }
    /**
     * @return The rule pattern.
     *
     */
    public String rule() {
        return this.rule;
    }
    /**
     * @return The server-assigned integer rule ID. Import a rule with &lt;configId&gt;/&lt;ruleId&gt;.
     *
     */
    public Integer ruleId() {
        return this.ruleId;
    }
    /**
     * @return The matching mode, if set.
     *
     */
    public Optional<String> ruleType() {
        return Optional.ofNullable(this.ruleType);
    }
    /**
     * @return The storage type: cookies, scripts, iframes, or localStorage. Osano&#39;s raw type is passed through when it is not one of these.
     *
     */
    public String storeType() {
        return this.storeType;
    }
    /**
     * @return The disclosure title, if set.
     *
     */
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }
    /**
     * @return When the rule was last updated (ISO 8601).
     *
     */
    public String updated() {
        return this.updated;
    }
    /**
     * @return The Osano vendor ID, if set.
     *
     */
    public Optional<String> vendorId() {
        return Optional.ofNullable(this.vendorId);
    }
    /**
     * @return The vendor name, if set.
     *
     */
    public Optional<String> vendorName() {
        return Optional.ofNullable(this.vendorName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CookieConsentRuleDetails defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String classification;
        private String configId;
        private String created;
        private @Nullable String description;
        private Boolean disclosure;
        private @Nullable String expiry;
        private String rule;
        private Integer ruleId;
        private @Nullable String ruleType;
        private String storeType;
        private @Nullable String title;
        private String updated;
        private @Nullable String vendorId;
        private @Nullable String vendorName;
        public Builder() {}
        public Builder(CookieConsentRuleDetails defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.classification = defaults.classification;
    	      this.configId = defaults.configId;
    	      this.created = defaults.created;
    	      this.description = defaults.description;
    	      this.disclosure = defaults.disclosure;
    	      this.expiry = defaults.expiry;
    	      this.rule = defaults.rule;
    	      this.ruleId = defaults.ruleId;
    	      this.ruleType = defaults.ruleType;
    	      this.storeType = defaults.storeType;
    	      this.title = defaults.title;
    	      this.updated = defaults.updated;
    	      this.vendorId = defaults.vendorId;
    	      this.vendorName = defaults.vendorName;
        }

        @CustomType.Setter
        public Builder classification(String classification) {
            if (classification == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "classification");
            }
            this.classification = classification;
            return this;
        }
        @CustomType.Setter
        public Builder configId(String configId) {
            if (configId == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "configId");
            }
            this.configId = configId;
            return this;
        }
        @CustomType.Setter
        public Builder created(String created) {
            if (created == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "created");
            }
            this.created = created;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder disclosure(Boolean disclosure) {
            if (disclosure == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "disclosure");
            }
            this.disclosure = disclosure;
            return this;
        }
        @CustomType.Setter
        public Builder expiry(@Nullable String expiry) {

            this.expiry = expiry;
            return this;
        }
        @CustomType.Setter
        public Builder rule(String rule) {
            if (rule == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "rule");
            }
            this.rule = rule;
            return this;
        }
        @CustomType.Setter
        public Builder ruleId(Integer ruleId) {
            if (ruleId == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "ruleId");
            }
            this.ruleId = ruleId;
            return this;
        }
        @CustomType.Setter
        public Builder ruleType(@Nullable String ruleType) {

            this.ruleType = ruleType;
            return this;
        }
        @CustomType.Setter
        public Builder storeType(String storeType) {
            if (storeType == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "storeType");
            }
            this.storeType = storeType;
            return this;
        }
        @CustomType.Setter
        public Builder title(@Nullable String title) {

            this.title = title;
            return this;
        }
        @CustomType.Setter
        public Builder updated(String updated) {
            if (updated == null) {
              throw new MissingRequiredPropertyException("CookieConsentRuleDetails", "updated");
            }
            this.updated = updated;
            return this;
        }
        @CustomType.Setter
        public Builder vendorId(@Nullable String vendorId) {

            this.vendorId = vendorId;
            return this;
        }
        @CustomType.Setter
        public Builder vendorName(@Nullable String vendorName) {

            this.vendorName = vendorName;
            return this;
        }
        public CookieConsentRuleDetails build() {
            final var _resultValue = new CookieConsentRuleDetails();
            _resultValue.classification = classification;
            _resultValue.configId = configId;
            _resultValue.created = created;
            _resultValue.description = description;
            _resultValue.disclosure = disclosure;
            _resultValue.expiry = expiry;
            _resultValue.rule = rule;
            _resultValue.ruleId = ruleId;
            _resultValue.ruleType = ruleType;
            _resultValue.storeType = storeType;
            _resultValue.title = title;
            _resultValue.updated = updated;
            _resultValue.vendorId = vendorId;
            _resultValue.vendorName = vendorName;
            return _resultValue;
        }
    }
}
