// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CookieConsentDiscovery {
    /**
     * @return Osano&#39;s AI classification confidence (Unknown, Low, Medium, or High). Only reported for cookies.
     *
     */
    private @Nullable String confidence;
    /**
     * @return When the discovery was first seen (ISO 8601).
     *
     */
    private String created;
    /**
     * @return The page URL where the item was first seen.
     *
     */
    private String firstPageSeen;
    /**
     * @return &#34;URL Scan&#34; or &#34;osano.js&#34;; unset when Osano does not know the origin.
     *
     */
    private @Nullable String scanOrigin;
    /**
     * @return The discovered cookie name, script or iframe URL, or localStorage key.
     *
     */
    private String storeKey;
    /**
     * @return The discovery&#39;s storage type as Osano reports it.
     *
     */
    private String storeType;
    /**
     * @return When the discovery was last updated (ISO 8601).
     *
     */
    private String updated;

    private CookieConsentDiscovery() {}
    /**
     * @return Osano&#39;s AI classification confidence (Unknown, Low, Medium, or High). Only reported for cookies.
     *
     */
    public Optional<String> confidence() {
        return Optional.ofNullable(this.confidence);
    }
    /**
     * @return When the discovery was first seen (ISO 8601).
     *
     */
    public String created() {
        return this.created;
    }
    /**
     * @return The page URL where the item was first seen.
     *
     */
    public String firstPageSeen() {
        return this.firstPageSeen;
    }
    /**
     * @return &#34;URL Scan&#34; or &#34;osano.js&#34;; unset when Osano does not know the origin.
     *
     */
    public Optional<String> scanOrigin() {
        return Optional.ofNullable(this.scanOrigin);
    }
    /**
     * @return The discovered cookie name, script or iframe URL, or localStorage key.
     *
     */
    public String storeKey() {
        return this.storeKey;
    }
    /**
     * @return The discovery&#39;s storage type as Osano reports it.
     *
     */
    public String storeType() {
        return this.storeType;
    }
    /**
     * @return When the discovery was last updated (ISO 8601).
     *
     */
    public String updated() {
        return this.updated;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CookieConsentDiscovery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String confidence;
        private String created;
        private String firstPageSeen;
        private @Nullable String scanOrigin;
        private String storeKey;
        private String storeType;
        private String updated;
        public Builder() {}
        public Builder(CookieConsentDiscovery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.confidence = defaults.confidence;
    	      this.created = defaults.created;
    	      this.firstPageSeen = defaults.firstPageSeen;
    	      this.scanOrigin = defaults.scanOrigin;
    	      this.storeKey = defaults.storeKey;
    	      this.storeType = defaults.storeType;
    	      this.updated = defaults.updated;
        }

        @CustomType.Setter
        public Builder confidence(@Nullable String confidence) {

            this.confidence = confidence;
            return this;
        }
        @CustomType.Setter
        public Builder created(String created) {
            if (created == null) {
              throw new MissingRequiredPropertyException("CookieConsentDiscovery", "created");
            }
            this.created = created;
            return this;
        }
        @CustomType.Setter
        public Builder firstPageSeen(String firstPageSeen) {
            if (firstPageSeen == null) {
              throw new MissingRequiredPropertyException("CookieConsentDiscovery", "firstPageSeen");
            }
            this.firstPageSeen = firstPageSeen;
            return this;
        }
        @CustomType.Setter
        public Builder scanOrigin(@Nullable String scanOrigin) {

            this.scanOrigin = scanOrigin;
            return this;
        }
        @CustomType.Setter
        public Builder storeKey(String storeKey) {
            if (storeKey == null) {
              throw new MissingRequiredPropertyException("CookieConsentDiscovery", "storeKey");
            }
            this.storeKey = storeKey;
            return this;
        }
        @CustomType.Setter
        public Builder storeType(String storeType) {
            if (storeType == null) {
              throw new MissingRequiredPropertyException("CookieConsentDiscovery", "storeType");
            }
            this.storeType = storeType;
            return this;
        }
        @CustomType.Setter
        public Builder updated(String updated) {
            if (updated == null) {
              throw new MissingRequiredPropertyException("CookieConsentDiscovery", "updated");
            }
            this.updated = updated;
            return this;
        }
        public CookieConsentDiscovery build() {
            final var _resultValue = new CookieConsentDiscovery();
            _resultValue.confidence = confidence;
            _resultValue.created = created;
            _resultValue.firstPageSeen = firstPageSeen;
            _resultValue.scanOrigin = scanOrigin;
            _resultValue.storeKey = storeKey;
            _resultValue.storeType = storeType;
            _resultValue.updated = updated;
            return _resultValue;
        }
    }
}
