// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetConsentProfileResult {
    private String configId;
    private Boolean exists;
    private String hashedSubjectId;
    private Map<String,Object> profile;

    private GetConsentProfileResult() {}
    public String configId() {
        return this.configId;
    }
    public Boolean exists() {
        return this.exists;
    }
    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }
    public Map<String,Object> profile() {
        return this.profile;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetConsentProfileResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String configId;
        private Boolean exists;
        private String hashedSubjectId;
        private Map<String,Object> profile;
        public Builder() {}
        public Builder(GetConsentProfileResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.configId = defaults.configId;
    	      this.exists = defaults.exists;
    	      this.hashedSubjectId = defaults.hashedSubjectId;
    	      this.profile = defaults.profile;
        }

        @CustomType.Setter
        public Builder configId(String configId) {
            if (configId == null) {
              throw new MissingRequiredPropertyException("GetConsentProfileResult", "configId");
            }
            this.configId = configId;
            return this;
        }
        @CustomType.Setter
        public Builder exists(Boolean exists) {
            if (exists == null) {
              throw new MissingRequiredPropertyException("GetConsentProfileResult", "exists");
            }
            this.exists = exists;
            return this;
        }
        @CustomType.Setter
        public Builder hashedSubjectId(String hashedSubjectId) {
            if (hashedSubjectId == null) {
              throw new MissingRequiredPropertyException("GetConsentProfileResult", "hashedSubjectId");
            }
            this.hashedSubjectId = hashedSubjectId;
            return this;
        }
        @CustomType.Setter
        public Builder profile(Map<String,Object> profile) {
            if (profile == null) {
              throw new MissingRequiredPropertyException("GetConsentProfileResult", "profile");
            }
            this.profile = profile;
            return this;
        }
        public GetConsentProfileResult build() {
            final var _resultValue = new GetConsentProfileResult();
            _resultValue.configId = configId;
            _resultValue.exists = exists;
            _resultValue.hashedSubjectId = hashedSubjectId;
            _resultValue.profile = profile;
            return _resultValue;
        }
    }
}
