// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetSubjectProfileResult {
    /**
     * @return The subject&#39;s email address. Secret, because it is personal data.
     *
     */
    private String email;
    /**
     * @return Whether Osano returned a profile for the subject.
     *
     */
    private Boolean exists;
    /**
     * @return The complete profile Osano returned. Secret, because it is personal data.
     *
     */
    private Map<String,Object> profile;
    /**
     * @return The subject ID that was looked up.
     *
     */
    private String subjectId;

    private GetSubjectProfileResult() {}
    /**
     * @return The subject&#39;s email address. Secret, because it is personal data.
     *
     */
    public String email() {
        return this.email;
    }
    /**
     * @return Whether Osano returned a profile for the subject.
     *
     */
    public Boolean exists() {
        return this.exists;
    }
    /**
     * @return The complete profile Osano returned. Secret, because it is personal data.
     *
     */
    public Map<String,Object> profile() {
        return this.profile;
    }
    /**
     * @return The subject ID that was looked up.
     *
     */
    public String subjectId() {
        return this.subjectId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubjectProfileResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private Boolean exists;
        private Map<String,Object> profile;
        private String subjectId;
        public Builder() {}
        public Builder(GetSubjectProfileResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.exists = defaults.exists;
    	      this.profile = defaults.profile;
    	      this.subjectId = defaults.subjectId;
        }

        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetSubjectProfileResult", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder exists(Boolean exists) {
            if (exists == null) {
              throw new MissingRequiredPropertyException("GetSubjectProfileResult", "exists");
            }
            this.exists = exists;
            return this;
        }
        @CustomType.Setter
        public Builder profile(Map<String,Object> profile) {
            if (profile == null) {
              throw new MissingRequiredPropertyException("GetSubjectProfileResult", "profile");
            }
            this.profile = profile;
            return this;
        }
        @CustomType.Setter
        public Builder subjectId(String subjectId) {
            if (subjectId == null) {
              throw new MissingRequiredPropertyException("GetSubjectProfileResult", "subjectId");
            }
            this.subjectId = subjectId;
            return this;
        }
        public GetSubjectProfileResult build() {
            final var _resultValue = new GetSubjectProfileResult();
            _resultValue.email = email;
            _resultValue.exists = exists;
            _resultValue.profile = profile;
            _resultValue.subjectId = subjectId;
            return _resultValue;
        }
    }
}
