// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSubjectResult {
    private String anonymousId;
    private Boolean exists;
    private String subjectId;
    private String subjectRef;
    private String verifiedId;

    private GetSubjectResult() {}
    public String anonymousId() {
        return this.anonymousId;
    }
    public Boolean exists() {
        return this.exists;
    }
    public String subjectId() {
        return this.subjectId;
    }
    public String subjectRef() {
        return this.subjectRef;
    }
    public String verifiedId() {
        return this.verifiedId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubjectResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String anonymousId;
        private Boolean exists;
        private String subjectId;
        private String subjectRef;
        private String verifiedId;
        public Builder() {}
        public Builder(GetSubjectResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.anonymousId = defaults.anonymousId;
    	      this.exists = defaults.exists;
    	      this.subjectId = defaults.subjectId;
    	      this.subjectRef = defaults.subjectRef;
    	      this.verifiedId = defaults.verifiedId;
        }

        @CustomType.Setter
        public Builder anonymousId(String anonymousId) {
            if (anonymousId == null) {
              throw new MissingRequiredPropertyException("GetSubjectResult", "anonymousId");
            }
            this.anonymousId = anonymousId;
            return this;
        }
        @CustomType.Setter
        public Builder exists(Boolean exists) {
            if (exists == null) {
              throw new MissingRequiredPropertyException("GetSubjectResult", "exists");
            }
            this.exists = exists;
            return this;
        }
        @CustomType.Setter
        public Builder subjectId(String subjectId) {
            if (subjectId == null) {
              throw new MissingRequiredPropertyException("GetSubjectResult", "subjectId");
            }
            this.subjectId = subjectId;
            return this;
        }
        @CustomType.Setter
        public Builder subjectRef(String subjectRef) {
            if (subjectRef == null) {
              throw new MissingRequiredPropertyException("GetSubjectResult", "subjectRef");
            }
            this.subjectRef = subjectRef;
            return this;
        }
        @CustomType.Setter
        public Builder verifiedId(String verifiedId) {
            if (verifiedId == null) {
              throw new MissingRequiredPropertyException("GetSubjectResult", "verifiedId");
            }
            this.verifiedId = verifiedId;
            return this;
        }
        public GetSubjectResult build() {
            final var _resultValue = new GetSubjectResult();
            _resultValue.anonymousId = anonymousId;
            _resultValue.exists = exists;
            _resultValue.subjectId = subjectId;
            _resultValue.subjectRef = subjectRef;
            _resultValue.verifiedId = verifiedId;
            return _resultValue;
        }
    }
}
