// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetUnifiedConsentResult {
    private List<Map<String,Object>> conflicts;
    private Boolean exists;
    private String subjectRef;
    private Map<String,Object> unifiedConsent;

    private GetUnifiedConsentResult() {}
    public List<Map<String,Object>> conflicts() {
        return this.conflicts;
    }
    public Boolean exists() {
        return this.exists;
    }
    public String subjectRef() {
        return this.subjectRef;
    }
    public Map<String,Object> unifiedConsent() {
        return this.unifiedConsent;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUnifiedConsentResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<Map<String,Object>> conflicts;
        private Boolean exists;
        private String subjectRef;
        private Map<String,Object> unifiedConsent;
        public Builder() {}
        public Builder(GetUnifiedConsentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conflicts = defaults.conflicts;
    	      this.exists = defaults.exists;
    	      this.subjectRef = defaults.subjectRef;
    	      this.unifiedConsent = defaults.unifiedConsent;
        }

        @CustomType.Setter
        public Builder conflicts(List<Map<String,Object>> conflicts) {
            if (conflicts == null) {
              throw new MissingRequiredPropertyException("GetUnifiedConsentResult", "conflicts");
            }
            this.conflicts = conflicts;
            return this;
        }
        @CustomType.Setter
        public Builder exists(Boolean exists) {
            if (exists == null) {
              throw new MissingRequiredPropertyException("GetUnifiedConsentResult", "exists");
            }
            this.exists = exists;
            return this;
        }
        @CustomType.Setter
        public Builder subjectRef(String subjectRef) {
            if (subjectRef == null) {
              throw new MissingRequiredPropertyException("GetUnifiedConsentResult", "subjectRef");
            }
            this.subjectRef = subjectRef;
            return this;
        }
        @CustomType.Setter
        public Builder unifiedConsent(Map<String,Object> unifiedConsent) {
            if (unifiedConsent == null) {
              throw new MissingRequiredPropertyException("GetUnifiedConsentResult", "unifiedConsent");
            }
            this.unifiedConsent = unifiedConsent;
            return this;
        }
        public GetUnifiedConsentResult build() {
            final var _resultValue = new GetUnifiedConsentResult();
            _resultValue.conflicts = conflicts;
            _resultValue.exists = exists;
            _resultValue.subjectRef = subjectRef;
            _resultValue.unifiedConsent = unifiedConsent;
            return _resultValue;
        }
    }
}
