// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SendSubjectCodeResult {
    private String channel;
    private String destination;
    private String hashedSubjectId;

    private SendSubjectCodeResult() {}
    public String channel() {
        return this.channel;
    }
    public String destination() {
        return this.destination;
    }
    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SendSubjectCodeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String channel;
        private String destination;
        private String hashedSubjectId;
        public Builder() {}
        public Builder(SendSubjectCodeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channel = defaults.channel;
    	      this.destination = defaults.destination;
    	      this.hashedSubjectId = defaults.hashedSubjectId;
        }

        @CustomType.Setter
        public Builder channel(String channel) {
            if (channel == null) {
              throw new MissingRequiredPropertyException("SendSubjectCodeResult", "channel");
            }
            this.channel = channel;
            return this;
        }
        @CustomType.Setter
        public Builder destination(String destination) {
            if (destination == null) {
              throw new MissingRequiredPropertyException("SendSubjectCodeResult", "destination");
            }
            this.destination = destination;
            return this;
        }
        @CustomType.Setter
        public Builder hashedSubjectId(String hashedSubjectId) {
            if (hashedSubjectId == null) {
              throw new MissingRequiredPropertyException("SendSubjectCodeResult", "hashedSubjectId");
            }
            this.hashedSubjectId = hashedSubjectId;
            return this;
        }
        public SendSubjectCodeResult build() {
            final var _resultValue = new SendSubjectCodeResult();
            _resultValue.channel = channel;
            _resultValue.destination = destination;
            _resultValue.hashedSubjectId = hashedSubjectId;
            return _resultValue;
        }
    }
}
