// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class VerifySubjectCodeResult {
    private String channel;
    private String destination;
    private String hashedSubjectId;
    private Map<String,Object> profile;
    private Boolean verified;

    private VerifySubjectCodeResult() {}
    public String channel() {
        return this.channel;
    }
    public String destination() {
        return this.destination;
    }
    public String hashedSubjectId() {
        return this.hashedSubjectId;
    }
    public Map<String,Object> profile() {
        return this.profile;
    }
    public Boolean verified() {
        return this.verified;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(VerifySubjectCodeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String channel;
        private String destination;
        private String hashedSubjectId;
        private Map<String,Object> profile;
        private Boolean verified;
        public Builder() {}
        public Builder(VerifySubjectCodeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channel = defaults.channel;
    	      this.destination = defaults.destination;
    	      this.hashedSubjectId = defaults.hashedSubjectId;
    	      this.profile = defaults.profile;
    	      this.verified = defaults.verified;
        }

        @CustomType.Setter
        public Builder channel(String channel) {
            if (channel == null) {
              throw new MissingRequiredPropertyException("VerifySubjectCodeResult", "channel");
            }
            this.channel = channel;
            return this;
        }
        @CustomType.Setter
        public Builder destination(String destination) {
            if (destination == null) {
              throw new MissingRequiredPropertyException("VerifySubjectCodeResult", "destination");
            }
            this.destination = destination;
            return this;
        }
        @CustomType.Setter
        public Builder hashedSubjectId(String hashedSubjectId) {
            if (hashedSubjectId == null) {
              throw new MissingRequiredPropertyException("VerifySubjectCodeResult", "hashedSubjectId");
            }
            this.hashedSubjectId = hashedSubjectId;
            return this;
        }
        @CustomType.Setter
        public Builder profile(Map<String,Object> profile) {
            if (profile == null) {
              throw new MissingRequiredPropertyException("VerifySubjectCodeResult", "profile");
            }
            this.profile = profile;
            return this;
        }
        @CustomType.Setter
        public Builder verified(Boolean verified) {
            if (verified == null) {
              throw new MissingRequiredPropertyException("VerifySubjectCodeResult", "verified");
            }
            this.verified = verified;
            return this;
        }
        public VerifySubjectCodeResult build() {
            final var _resultValue = new VerifySubjectCodeResult();
            _resultValue.channel = channel;
            _resultValue.destination = destination;
            _resultValue.hashedSubjectId = hashedSubjectId;
            _resultValue.profile = profile;
            _resultValue.verified = verified;
            return _resultValue;
        }
    }
}
