# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

apiBaseUrl: Optional[str]
"""
Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
"""

customerBaseUrl: Optional[str]
"""
Override base URL for the Customer REST API (default: https://api.osano.com).
"""

osanoApiKey: Optional[str]
"""
Osano API key used for subject profile routes and Customer REST API/CMP operations (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
"""

requestTimeoutSeconds: Optional[int]
"""
HTTP request timeout in seconds for Customer REST API and Unified Consent calls (default 60).
"""

ucApiKey: Optional[str]
"""
Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
"""

ucBaseUrl: Optional[str]
"""
Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
"""

unifiedConsentApiKey: Optional[str]
"""
Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
"""
