# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('osano')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_base_url(self) -> Optional[str]:
        """
        Base URL for the Osano Unified Consent API. Override only when targeting a custom domain (default https://uc.api.osano.com).
        """
        return __config__.get('apiBaseUrl')

    @_builtins.property
    def customer_base_url(self) -> Optional[str]:
        """
        Override base URL for the Customer REST API (default: https://api.osano.com).
        """
        return __config__.get('customerBaseUrl')

    @_builtins.property
    def osano_api_key(self) -> Optional[str]:
        """
        Osano API key used for subject profile routes (set via pulumi config set osano:osanoApiKey --secret or OSANO_API_KEY).
        """
        return __config__.get('osanoApiKey')

    @_builtins.property
    def request_timeout_seconds(self) -> Optional[int]:
        """
        HTTP request timeout in seconds for Osano API calls (default 60).
        """
        return __config__.get_int('requestTimeoutSeconds')

    @_builtins.property
    def uc_api_key(self) -> Optional[str]:
        """
        Unified Consent API key for the Unified Consent Core API (x-uc-api-key).
        """
        return __config__.get('ucApiKey')

    @_builtins.property
    def uc_base_url(self) -> Optional[str]:
        """
        Override base URL for the Unified Consent Core API (default: https://uc.api.osano.com).
        """
        return __config__.get('ucBaseUrl')

    @_builtins.property
    def unified_consent_api_key(self) -> Optional[str]:
        """
        Unified Consent API key used for consent collection routes (set via pulumi config set osano:unifiedConsentApiKey --secret or OSANO_UC_API_KEY).
        """
        return __config__.get('unifiedConsentApiKey')

