// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ConsentActionArgs {
    action: pulumi.Input<string>;
    jurisdiction?: pulumi.Input<string>;
    target: pulumi.Input<string>;
    vendor: pulumi.Input<string>;
}

export interface ConsentComplianceArgs {
    gpc?: pulumi.Input<number>;
    privacyPolicy?: pulumi.Input<inputs.ConsentPrivacyPolicyArgs>;
}

export interface ConsentPrivacyPolicyArgs {
    url: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}

export interface ConsentSubjectArgs {
    anonymousId?: pulumi.Input<string>;
    verifiedId?: pulumi.Input<string>;
}
