// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"errors"
	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates unified consent decisions within Osano for a given subject.
type Consent struct {
	pulumi.CustomResourceState

	// Consent actions referencing privacy protocols (target) within a configuration (vendor).
	Actions ConsentActionArrayOutput `pulumi:"actions"`
	// Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
	Attributes pulumi.StringMapOutput     `pulumi:"attributes"`
	Compliance ConsentCompliancePtrOutput `pulumi:"compliance"`
	// Synthetic identifier used by Pulumi to track consent submissions.
	ConsentId pulumi.StringOutput `pulumi:"consentId"`
	// Optional jurisdiction override matching one of the configuration's jurisdictions.
	Jurisdiction pulumi.StringPtrOutput `pulumi:"jurisdiction"`
	// Timestamp of the last refresh from the Osano API (RFC3339).
	LastSynced pulumi.StringOutput `pulumi:"lastSynced"`
	// Origin metadata for the consent, typically 'api' or 'gpc'.
	Origin pulumi.StringPtrOutput `pulumi:"origin"`
	// Latest raw response payload returned by Osano.
	Response pulumi.MapOutput `pulumi:"response"`
	// Subject identifiers used for the consent (verifiedId or anonymousId).
	Subject ConsentSubjectOutput `pulumi:"subject"`
	// Custom tags that Osano associates with the consent record.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
}

// NewConsent registers a new resource with the given unique name, arguments, and options.
func NewConsent(ctx *pulumi.Context,
	name string, args *ConsentArgs, opts ...pulumi.ResourceOption) (*Consent, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Actions == nil {
		return nil, errors.New("invalid value for required argument 'Actions'")
	}
	if args.Subject == nil {
		return nil, errors.New("invalid value for required argument 'Subject'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Consent
	err := ctx.RegisterResource("osano:index:Consent", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConsent gets an existing Consent resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConsent(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConsentState, opts ...pulumi.ResourceOption) (*Consent, error) {
	var resource Consent
	err := ctx.ReadResource("osano:index:Consent", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Consent resources.
type consentState struct {
}

type ConsentState struct {
}

func (ConsentState) ElementType() reflect.Type {
	return reflect.TypeOf((*consentState)(nil)).Elem()
}

type consentArgs struct {
	// Consent actions referencing privacy protocols (target) within a configuration (vendor).
	Actions []ConsentAction `pulumi:"actions"`
	// Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
	Attributes map[string]string  `pulumi:"attributes"`
	Compliance *ConsentCompliance `pulumi:"compliance"`
	// Optional jurisdiction override matching one of the configuration's jurisdictions.
	Jurisdiction *string `pulumi:"jurisdiction"`
	// Origin metadata for the consent, typically 'api' or 'gpc'.
	Origin *string `pulumi:"origin"`
	// Subject identifiers used for the consent (verifiedId or anonymousId).
	Subject ConsentSubject `pulumi:"subject"`
	// Custom tags that Osano associates with the consent record.
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a Consent resource.
type ConsentArgs struct {
	// Consent actions referencing privacy protocols (target) within a configuration (vendor).
	Actions ConsentActionArrayInput
	// Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
	Attributes pulumi.StringMapInput
	Compliance ConsentCompliancePtrInput
	// Optional jurisdiction override matching one of the configuration's jurisdictions.
	Jurisdiction pulumi.StringPtrInput
	// Origin metadata for the consent, typically 'api' or 'gpc'.
	Origin pulumi.StringPtrInput
	// Subject identifiers used for the consent (verifiedId or anonymousId).
	Subject ConsentSubjectInput
	// Custom tags that Osano associates with the consent record.
	Tags pulumi.StringArrayInput
}

func (ConsentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*consentArgs)(nil)).Elem()
}

type ConsentInput interface {
	pulumi.Input

	ToConsentOutput() ConsentOutput
	ToConsentOutputWithContext(ctx context.Context) ConsentOutput
}

func (*Consent) ElementType() reflect.Type {
	return reflect.TypeOf((**Consent)(nil)).Elem()
}

func (i *Consent) ToConsentOutput() ConsentOutput {
	return i.ToConsentOutputWithContext(context.Background())
}

func (i *Consent) ToConsentOutputWithContext(ctx context.Context) ConsentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConsentOutput)
}

type ConsentOutput struct{ *pulumi.OutputState }

func (ConsentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Consent)(nil)).Elem()
}

func (o ConsentOutput) ToConsentOutput() ConsentOutput {
	return o
}

func (o ConsentOutput) ToConsentOutputWithContext(ctx context.Context) ConsentOutput {
	return o
}

// Consent actions referencing privacy protocols (target) within a configuration (vendor).
func (o ConsentOutput) Actions() ConsentActionArrayOutput {
	return o.ApplyT(func(v *Consent) ConsentActionArrayOutput { return v.Actions }).(ConsentActionArrayOutput)
}

// Optional key/value attributes stored with the consent record (e.g., ipAddress overrides).
func (o ConsentOutput) Attributes() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringMapOutput { return v.Attributes }).(pulumi.StringMapOutput)
}

func (o ConsentOutput) Compliance() ConsentCompliancePtrOutput {
	return o.ApplyT(func(v *Consent) ConsentCompliancePtrOutput { return v.Compliance }).(ConsentCompliancePtrOutput)
}

// Synthetic identifier used by Pulumi to track consent submissions.
func (o ConsentOutput) ConsentId() pulumi.StringOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringOutput { return v.ConsentId }).(pulumi.StringOutput)
}

// Optional jurisdiction override matching one of the configuration's jurisdictions.
func (o ConsentOutput) Jurisdiction() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringPtrOutput { return v.Jurisdiction }).(pulumi.StringPtrOutput)
}

// Timestamp of the last refresh from the Osano API (RFC3339).
func (o ConsentOutput) LastSynced() pulumi.StringOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringOutput { return v.LastSynced }).(pulumi.StringOutput)
}

// Origin metadata for the consent, typically 'api' or 'gpc'.
func (o ConsentOutput) Origin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringPtrOutput { return v.Origin }).(pulumi.StringPtrOutput)
}

// Latest raw response payload returned by Osano.
func (o ConsentOutput) Response() pulumi.MapOutput {
	return o.ApplyT(func(v *Consent) pulumi.MapOutput { return v.Response }).(pulumi.MapOutput)
}

// Subject identifiers used for the consent (verifiedId or anonymousId).
func (o ConsentOutput) Subject() ConsentSubjectOutput {
	return o.ApplyT(func(v *Consent) ConsentSubjectOutput { return v.Subject }).(ConsentSubjectOutput)
}

// Custom tags that Osano associates with the consent record.
func (o ConsentOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Consent) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConsentInput)(nil)).Elem(), &Consent{})
	pulumi.RegisterOutputType(ConsentOutput{})
}
