// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a consent profile for a hashed subject identifier and config ID.
func GetConsentProfile(ctx *pulumi.Context, args *GetConsentProfileArgs, opts ...pulumi.InvokeOption) (*GetConsentProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConsentProfileResult
	err := ctx.Invoke("osano:index:getConsentProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// Arguments for getConsentProfile
type GetConsentProfileArgs struct {
	ConfigId        string `pulumi:"configId"`
	HashedSubjectId string `pulumi:"hashedSubjectId"`
}

type GetConsentProfileResult struct {
	ConfigId        string                 `pulumi:"configId"`
	Exists          bool                   `pulumi:"exists"`
	HashedSubjectId string                 `pulumi:"hashedSubjectId"`
	Profile         map[string]interface{} `pulumi:"profile"`
}

func GetConsentProfileOutput(ctx *pulumi.Context, args GetConsentProfileOutputArgs, opts ...pulumi.InvokeOption) GetConsentProfileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConsentProfileResultOutput, error) {
			args := v.(GetConsentProfileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("osano:index:getConsentProfile", args, GetConsentProfileResultOutput{}, options).(GetConsentProfileResultOutput), nil
		}).(GetConsentProfileResultOutput)
}

// Arguments for getConsentProfile
type GetConsentProfileOutputArgs struct {
	ConfigId        pulumi.StringInput `pulumi:"configId"`
	HashedSubjectId pulumi.StringInput `pulumi:"hashedSubjectId"`
}

func (GetConsentProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConsentProfileArgs)(nil)).Elem()
}

type GetConsentProfileResultOutput struct{ *pulumi.OutputState }

func (GetConsentProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConsentProfileResult)(nil)).Elem()
}

func (o GetConsentProfileResultOutput) ToGetConsentProfileResultOutput() GetConsentProfileResultOutput {
	return o
}

func (o GetConsentProfileResultOutput) ToGetConsentProfileResultOutputWithContext(ctx context.Context) GetConsentProfileResultOutput {
	return o
}

func (o GetConsentProfileResultOutput) ConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v GetConsentProfileResult) string { return v.ConfigId }).(pulumi.StringOutput)
}

func (o GetConsentProfileResultOutput) Exists() pulumi.BoolOutput {
	return o.ApplyT(func(v GetConsentProfileResult) bool { return v.Exists }).(pulumi.BoolOutput)
}

func (o GetConsentProfileResultOutput) HashedSubjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetConsentProfileResult) string { return v.HashedSubjectId }).(pulumi.StringOutput)
}

func (o GetConsentProfileResultOutput) Profile() pulumi.MapOutput {
	return o.ApplyT(func(v GetConsentProfileResult) map[string]interface{} { return v.Profile }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConsentProfileResultOutput{})
}
