// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves the aggregated privacy protocol collections, optionally filtered by jurisdiction and type.
func GetCollections(ctx *pulumi.Context, args *GetCollectionsArgs, opts ...pulumi.InvokeOption) (*GetCollectionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCollectionsResult
	err := ctx.Invoke("osano:index:getCollections", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCollectionsArgs struct {
	// Optional jurisdiction filter. When unset, Osano resolves the jurisdiction from the caller's IP address.
	Jurisdiction *string `pulumi:"jurisdiction"`
	// Optional collection type: published (default) or draft.
	Type *string `pulumi:"type"`
}

type GetCollectionsResult struct {
	// The collection of privacy protocols that applies to the jurisdiction.
	Collection map[string]interface{} `pulumi:"collection"`
	// Every jurisdiction the configuration defines.
	Jurisdictions []string `pulumi:"jurisdictions"`
}

func GetCollectionsOutput(ctx *pulumi.Context, args GetCollectionsOutputArgs, opts ...pulumi.InvokeOption) GetCollectionsResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("osano:index:getCollections", args, GetCollectionsResultOutput{}, options).(GetCollectionsResultOutput)
}

type GetCollectionsOutputArgs struct {
	// Optional jurisdiction filter. When unset, Osano resolves the jurisdiction from the caller's IP address.
	Jurisdiction pulumi.StringPtrInput `pulumi:"jurisdiction"`
	// Optional collection type: published (default) or draft.
	Type pulumi.StringPtrInput `pulumi:"type"`
}

func (GetCollectionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCollectionsArgs)(nil)).Elem()
}

type GetCollectionsResultOutput struct{ *pulumi.OutputState }

func (GetCollectionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCollectionsResult)(nil)).Elem()
}

func (o GetCollectionsResultOutput) ToGetCollectionsResultOutput() GetCollectionsResultOutput {
	return o
}

func (o GetCollectionsResultOutput) ToGetCollectionsResultOutputWithContext(ctx context.Context) GetCollectionsResultOutput {
	return o
}

// The collection of privacy protocols that applies to the jurisdiction.
func (o GetCollectionsResultOutput) Collection() pulumi.MapOutput {
	return o.ApplyT(func(v GetCollectionsResult) map[string]interface{} { return v.Collection }).(pulumi.MapOutput)
}

// Every jurisdiction the configuration defines.
func (o GetCollectionsResultOutput) Jurisdictions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCollectionsResult) []string { return v.Jurisdictions }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCollectionsResultOutput{})
}
