// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves the Unified Consent configuration referenced by the API key.
func GetConfig(ctx *pulumi.Context, args *GetConfigArgs, opts ...pulumi.InvokeOption) (*GetConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConfigResult
	err := ctx.Invoke("osano:index:getConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetConfigArgs struct {
}

type GetConfigResult struct {
	Config map[string]interface{} `pulumi:"config"`
}

func GetConfigOutput(ctx *pulumi.Context, args GetConfigOutputArgs, opts ...pulumi.InvokeOption) GetConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConfigResultOutput, error) {
			args := v.(GetConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("osano:index:getConfig", args, GetConfigResultOutput{}, options).(GetConfigResultOutput), nil
		}).(GetConfigResultOutput)
}

type GetConfigOutputArgs struct {
}

func (GetConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigArgs)(nil)).Elem()
}

type GetConfigResultOutput struct{ *pulumi.OutputState }

func (GetConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigResult)(nil)).Elem()
}

func (o GetConfigResultOutput) ToGetConfigResultOutput() GetConfigResultOutput {
	return o
}

func (o GetConfigResultOutput) ToGetConfigResultOutputWithContext(ctx context.Context) GetConfigResultOutput {
	return o
}

func (o GetConfigResultOutput) Config() pulumi.MapOutput {
	return o.ApplyT(func(v GetConfigResult) map[string]interface{} { return v.Config }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConfigResultOutput{})
}
