// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Lists Cookie Consent configurations, optionally filtered by name, domains, organization, mode, or publish status, and returns each one's install script. Follows pagination until maxResults or the last page.
func GetCookieConsentConfigs(ctx *pulumi.Context, args *GetCookieConsentConfigsArgs, opts ...pulumi.InvokeOption) (*GetCookieConsentConfigsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCookieConsentConfigsResult
	err := ctx.Invoke("osano:index:getCookieConsentConfigs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCookieConsentConfigsArgs struct {
	// Filter by domains. Use Punycode for non-ASCII domains.
	Domains []string `pulumi:"domains"`
	// How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
	DomainsMatch *string `pulumi:"domainsMatch"`
	// Stop after this many configurations. Unset or 0 returns every matching configuration.
	MaxResults *int `pulumi:"maxResults"`
	// Filter by compliance mode: debug, permissive, or production.
	Mode *string `pulumi:"mode"`
	// Filter by configuration name (case insensitive, partial matches allowed).
	Name *string `pulumi:"name"`
	// Filter by organization IDs (UUIDs).
	OrgIds []string `pulumi:"orgIds"`
	// How orgIds filters: any (default), all, or not, as for domainsMatch.
	OrgIdsMatch *string `pulumi:"orgIdsMatch"`
	// Filter by publish status: unpublished, in-progress, published, outdated, or error.
	PublishStatus *string `pulumi:"publishStatus"`
	// Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
	SortBy *string `pulumi:"sortBy"`
	// Filter by whether discovery recording is stopped.
	TattleRecordStopped *bool `pulumi:"tattleRecordStopped"`
}

type GetCookieConsentConfigsResult struct {
	// The matching configurations, each with its install script.
	Configs []CookieConsentConfigDetails `pulumi:"configs"`
}

func GetCookieConsentConfigsOutput(ctx *pulumi.Context, args GetCookieConsentConfigsOutputArgs, opts ...pulumi.InvokeOption) GetCookieConsentConfigsResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("osano:index:getCookieConsentConfigs", args, GetCookieConsentConfigsResultOutput{}, options).(GetCookieConsentConfigsResultOutput)
}

type GetCookieConsentConfigsOutputArgs struct {
	// Filter by domains. Use Punycode for non-ASCII domains.
	Domains pulumi.StringArrayInput `pulumi:"domains"`
	// How domains filters: any (default) matches configs with any listed domain, all requires every listed domain, and not excludes configs with any listed domain.
	DomainsMatch pulumi.StringPtrInput `pulumi:"domainsMatch"`
	// Stop after this many configurations. Unset or 0 returns every matching configuration.
	MaxResults pulumi.IntPtrInput `pulumi:"maxResults"`
	// Filter by compliance mode: debug, permissive, or production.
	Mode pulumi.StringPtrInput `pulumi:"mode"`
	// Filter by configuration name (case insensitive, partial matches allowed).
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Filter by organization IDs (UUIDs).
	OrgIds pulumi.StringArrayInput `pulumi:"orgIds"`
	// How orgIds filters: any (default), all, or not, as for domainsMatch.
	OrgIdsMatch pulumi.StringPtrInput `pulumi:"orgIdsMatch"`
	// Filter by publish status: unpublished, in-progress, published, outdated, or error.
	PublishStatus pulumi.StringPtrInput `pulumi:"publishStatus"`
	// Sort field: name, created (default), updated, or lastPublished. Results are in descending order.
	SortBy pulumi.StringPtrInput `pulumi:"sortBy"`
	// Filter by whether discovery recording is stopped.
	TattleRecordStopped pulumi.BoolPtrInput `pulumi:"tattleRecordStopped"`
}

func (GetCookieConsentConfigsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCookieConsentConfigsArgs)(nil)).Elem()
}

type GetCookieConsentConfigsResultOutput struct{ *pulumi.OutputState }

func (GetCookieConsentConfigsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCookieConsentConfigsResult)(nil)).Elem()
}

func (o GetCookieConsentConfigsResultOutput) ToGetCookieConsentConfigsResultOutput() GetCookieConsentConfigsResultOutput {
	return o
}

func (o GetCookieConsentConfigsResultOutput) ToGetCookieConsentConfigsResultOutputWithContext(ctx context.Context) GetCookieConsentConfigsResultOutput {
	return o
}

// The matching configurations, each with its install script.
func (o GetCookieConsentConfigsResultOutput) Configs() CookieConsentConfigDetailsArrayOutput {
	return o.ApplyT(func(v GetCookieConsentConfigsResult) []CookieConsentConfigDetails { return v.Configs }).(CookieConsentConfigDetailsArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCookieConsentConfigsResultOutput{})
}
