// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a specific privacy protocol collection by ID.
func GetCollection(ctx *pulumi.Context, args *GetCollectionArgs, opts ...pulumi.InvokeOption) (*GetCollectionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCollectionResult
	err := ctx.Invoke("osano:index:getCollection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCollectionArgs struct {
	// The privacy protocol collection ID to fetch.
	CollectionId string `pulumi:"collectionId"`
}

type GetCollectionResult struct {
	// The collection: collectionId, name, frameworks, configIds, jurisdiction, type, consents, and preferences.
	Collection map[string]interface{} `pulumi:"collection"`
	// The collection ID that was looked up.
	CollectionId string `pulumi:"collectionId"`
	// Whether Osano returned the collection.
	Exists bool `pulumi:"exists"`
}

func GetCollectionOutput(ctx *pulumi.Context, args GetCollectionOutputArgs, opts ...pulumi.InvokeOption) GetCollectionResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("osano:index:getCollection", args, GetCollectionResultOutput{}, options).(GetCollectionResultOutput)
}

type GetCollectionOutputArgs struct {
	// The privacy protocol collection ID to fetch.
	CollectionId pulumi.StringInput `pulumi:"collectionId"`
}

func (GetCollectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCollectionArgs)(nil)).Elem()
}

type GetCollectionResultOutput struct{ *pulumi.OutputState }

func (GetCollectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCollectionResult)(nil)).Elem()
}

func (o GetCollectionResultOutput) ToGetCollectionResultOutput() GetCollectionResultOutput {
	return o
}

func (o GetCollectionResultOutput) ToGetCollectionResultOutputWithContext(ctx context.Context) GetCollectionResultOutput {
	return o
}

// The collection: collectionId, name, frameworks, configIds, jurisdiction, type, consents, and preferences.
func (o GetCollectionResultOutput) Collection() pulumi.MapOutput {
	return o.ApplyT(func(v GetCollectionResult) map[string]interface{} { return v.Collection }).(pulumi.MapOutput)
}

// The collection ID that was looked up.
func (o GetCollectionResultOutput) CollectionId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCollectionResult) string { return v.CollectionId }).(pulumi.StringOutput)
}

// Whether Osano returned the collection.
func (o GetCollectionResultOutput) Exists() pulumi.BoolOutput {
	return o.ApplyT(func(v GetCollectionResult) bool { return v.Exists }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCollectionResultOutput{})
}
