// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
func GetSubject(ctx *pulumi.Context, args *GetSubjectArgs, opts ...pulumi.InvokeOption) (*GetSubjectResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSubjectResult
	err := ctx.Invoke("osano:index:getSubject", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetSubjectArgs struct {
	ReferenceType *string `pulumi:"referenceType"`
	SubjectRef    string  `pulumi:"subjectRef"`
}

type GetSubjectResult struct {
	AnonymousId string `pulumi:"anonymousId"`
	Exists      bool   `pulumi:"exists"`
	SubjectId   string `pulumi:"subjectId"`
	SubjectRef  string `pulumi:"subjectRef"`
	VerifiedId  string `pulumi:"verifiedId"`
}

func GetSubjectOutput(ctx *pulumi.Context, args GetSubjectOutputArgs, opts ...pulumi.InvokeOption) GetSubjectResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSubjectResultOutput, error) {
			args := v.(GetSubjectArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("osano:index:getSubject", args, GetSubjectResultOutput{}, options).(GetSubjectResultOutput), nil
		}).(GetSubjectResultOutput)
}

type GetSubjectOutputArgs struct {
	ReferenceType pulumi.StringPtrInput `pulumi:"referenceType"`
	SubjectRef    pulumi.StringInput    `pulumi:"subjectRef"`
}

func (GetSubjectOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSubjectArgs)(nil)).Elem()
}

type GetSubjectResultOutput struct{ *pulumi.OutputState }

func (GetSubjectResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSubjectResult)(nil)).Elem()
}

func (o GetSubjectResultOutput) ToGetSubjectResultOutput() GetSubjectResultOutput {
	return o
}

func (o GetSubjectResultOutput) ToGetSubjectResultOutputWithContext(ctx context.Context) GetSubjectResultOutput {
	return o
}

func (o GetSubjectResultOutput) AnonymousId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubjectResult) string { return v.AnonymousId }).(pulumi.StringOutput)
}

func (o GetSubjectResultOutput) Exists() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSubjectResult) bool { return v.Exists }).(pulumi.BoolOutput)
}

func (o GetSubjectResultOutput) SubjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubjectResult) string { return v.SubjectId }).(pulumi.StringOutput)
}

func (o GetSubjectResultOutput) SubjectRef() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubjectResult) string { return v.SubjectRef }).(pulumi.StringOutput)
}

func (o GetSubjectResultOutput) VerifiedId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSubjectResult) string { return v.VerifiedId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSubjectResultOutput{})
}
