// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Verifies a subject profile using the code sent via email or SMS. Pulumi runs invokes on every preview, update, and refresh, and one-time codes cannot be reused, so call this from automation rather than from long-lived stack code.
func VerifySubjectCode(ctx *pulumi.Context, args *VerifySubjectCodeArgs, opts ...pulumi.InvokeOption) (*VerifySubjectCodeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv VerifySubjectCodeResult
	err := ctx.Invoke("osano:index:verifySubjectCode", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type VerifySubjectCodeArgs struct {
	// The one-time verification code the subject received.
	Code string `pulumi:"code"`
	// Email address the code was sent to. Set exactly one of email or phone.
	Email *string `pulumi:"email"`
	// The hashed subject identifier being verified.
	HashedSubjectId string `pulumi:"hashedSubjectId"`
	// Phone number the code was sent to. Set exactly one of email or phone.
	Phone *string `pulumi:"phone"`
}

type VerifySubjectCodeResult struct {
	Channel         string                 `pulumi:"channel"`
	Destination     string                 `pulumi:"destination"`
	HashedSubjectId string                 `pulumi:"hashedSubjectId"`
	Profile         map[string]interface{} `pulumi:"profile"`
	Verified        bool                   `pulumi:"verified"`
}

func VerifySubjectCodeOutput(ctx *pulumi.Context, args VerifySubjectCodeOutputArgs, opts ...pulumi.InvokeOption) VerifySubjectCodeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (VerifySubjectCodeResultOutput, error) {
			args := v.(VerifySubjectCodeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("osano:index:verifySubjectCode", args, VerifySubjectCodeResultOutput{}, options).(VerifySubjectCodeResultOutput), nil
		}).(VerifySubjectCodeResultOutput)
}

type VerifySubjectCodeOutputArgs struct {
	// The one-time verification code the subject received.
	Code pulumi.StringInput `pulumi:"code"`
	// Email address the code was sent to. Set exactly one of email or phone.
	Email pulumi.StringPtrInput `pulumi:"email"`
	// The hashed subject identifier being verified.
	HashedSubjectId pulumi.StringInput `pulumi:"hashedSubjectId"`
	// Phone number the code was sent to. Set exactly one of email or phone.
	Phone pulumi.StringPtrInput `pulumi:"phone"`
}

func (VerifySubjectCodeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VerifySubjectCodeArgs)(nil)).Elem()
}

type VerifySubjectCodeResultOutput struct{ *pulumi.OutputState }

func (VerifySubjectCodeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VerifySubjectCodeResult)(nil)).Elem()
}

func (o VerifySubjectCodeResultOutput) ToVerifySubjectCodeResultOutput() VerifySubjectCodeResultOutput {
	return o
}

func (o VerifySubjectCodeResultOutput) ToVerifySubjectCodeResultOutputWithContext(ctx context.Context) VerifySubjectCodeResultOutput {
	return o
}

func (o VerifySubjectCodeResultOutput) Channel() pulumi.StringOutput {
	return o.ApplyT(func(v VerifySubjectCodeResult) string { return v.Channel }).(pulumi.StringOutput)
}

func (o VerifySubjectCodeResultOutput) Destination() pulumi.StringOutput {
	return o.ApplyT(func(v VerifySubjectCodeResult) string { return v.Destination }).(pulumi.StringOutput)
}

func (o VerifySubjectCodeResultOutput) HashedSubjectId() pulumi.StringOutput {
	return o.ApplyT(func(v VerifySubjectCodeResult) string { return v.HashedSubjectId }).(pulumi.StringOutput)
}

func (o VerifySubjectCodeResultOutput) Profile() pulumi.MapOutput {
	return o.ApplyT(func(v VerifySubjectCodeResult) map[string]interface{} { return v.Profile }).(pulumi.MapOutput)
}

func (o VerifySubjectCodeResultOutput) Verified() pulumi.BoolOutput {
	return o.ApplyT(func(v VerifySubjectCodeResult) bool { return v.Verified }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(VerifySubjectCodeResultOutput{})
}
