name: command-dispatch

on:
  issue_comment:
    types:
      - created

jobs:
  command-dispatch-for-testing:
    name: command-dispatch-for-testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: peter-evans/slash-command-dispatch@9bdcd7914ec1b75590b790b844aa3b8eee7c683a # v5
        with:
          commands: |
            run-acceptance-tests
          issue-type: pull-request
          permission: write
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
