// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Checks whether a unified consent record exists for a given subject ID.
 */
export function checkConsent(args: CheckConsentArgs, opts?: pulumi.InvokeOptions): Promise<CheckConsentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:checkConsent", {
        "subjectId": args.subjectId,
    }, opts);
}

/**
 * Arguments for checkConsent
 */
export interface CheckConsentArgs {
    subjectId: string;
}

export interface CheckConsentResult {
    readonly exists: boolean;
    readonly subjectId: string;
}
/**
 * Checks whether a unified consent record exists for a given subject ID.
 */
export function checkConsentOutput(args: CheckConsentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<CheckConsentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:checkConsent", {
        "subjectId": args.subjectId,
    }, opts);
}

/**
 * Arguments for checkConsent
 */
export interface CheckConsentOutputArgs {
    subjectId: pulumi.Input<string>;
}
