// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Publishes an Osano Cookie Consent configuration, waits for completion, and returns its hosted CMP script. Import with the Osano config ID; deleting this resource only removes Pulumi state and does not unpublish the config.
 */
export class CookieConsentPublication extends pulumi.CustomResource {
    /**
     * Get an existing CookieConsentPublication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CookieConsentPublication {
        return new CookieConsentPublication(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'osano:index:CookieConsentPublication';

    /**
     * Returns true if the given object is an instance of CookieConsentPublication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CookieConsentPublication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CookieConsentPublication.__pulumiType;
    }

    /**
     * A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
     */
    declare public readonly changeToken: pulumi.Output<string>;
    /**
     * The Osano Cookie Consent config ID to publish. This is also the import ID.
     */
    declare public readonly configId: pulumi.Output<string>;
    /**
     * The Osano customer ID that owns the published configuration.
     */
    declare public /*out*/ readonly customerId: pulumi.Output<string>;
    /**
     * Optional description sent with the publication request.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
     */
    declare public readonly keepUnclassifiedTattles: pulumi.Output<boolean | undefined>;
    /**
     * Unix timestamp of the completed Osano publication.
     */
    declare public /*out*/ readonly lastPublished: pulumi.Output<number>;
    /**
     * The publication status returned by Osano after completion.
     */
    declare public /*out*/ readonly publishStatus: pulumi.Output<string>;
    /**
     * The configuration revision most recently published by Osano.
     */
    declare public /*out*/ readonly publishedRevision: pulumi.Output<number>;
    /**
     * The public hosted Osano CMP JavaScript URL for this customer and config.
     */
    declare public /*out*/ readonly scriptSrc: pulumi.Output<string>;
    /**
     * The complete public CMP script tag to place first in the site head, without async or defer attributes.
     */
    declare public /*out*/ readonly scriptTag: pulumi.Output<string>;
    /**
     * Optional absolute HTTP or HTTPS URL notified by Osano after publication.
     */
    declare public readonly webhookUrl: pulumi.Output<string | undefined>;

    /**
     * Create a CookieConsentPublication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CookieConsentPublicationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.changeToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'changeToken'");
            }
            if (args?.configId === undefined && !opts.urn) {
                throw new Error("Missing required property 'configId'");
            }
            resourceInputs["changeToken"] = args?.changeToken;
            resourceInputs["configId"] = args?.configId;
            resourceInputs["description"] = args?.description;
            resourceInputs["keepUnclassifiedTattles"] = (args?.keepUnclassifiedTattles) ?? true;
            resourceInputs["webhookUrl"] = args?.webhookUrl;
            resourceInputs["customerId"] = undefined /*out*/;
            resourceInputs["lastPublished"] = undefined /*out*/;
            resourceInputs["publishStatus"] = undefined /*out*/;
            resourceInputs["publishedRevision"] = undefined /*out*/;
            resourceInputs["scriptSrc"] = undefined /*out*/;
            resourceInputs["scriptTag"] = undefined /*out*/;
        } else {
            resourceInputs["changeToken"] = undefined /*out*/;
            resourceInputs["configId"] = undefined /*out*/;
            resourceInputs["customerId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["keepUnclassifiedTattles"] = undefined /*out*/;
            resourceInputs["lastPublished"] = undefined /*out*/;
            resourceInputs["publishStatus"] = undefined /*out*/;
            resourceInputs["publishedRevision"] = undefined /*out*/;
            resourceInputs["scriptSrc"] = undefined /*out*/;
            resourceInputs["scriptTag"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CookieConsentPublication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CookieConsentPublication resource.
 */
export interface CookieConsentPublicationArgs {
    /**
     * A caller-managed desired-state token. Changing it queues a new publication; an unchanged token is a no-op.
     */
    changeToken: pulumi.Input<string>;
    /**
     * The Osano Cookie Consent config ID to publish. This is also the import ID.
     */
    configId: pulumi.Input<string>;
    /**
     * Optional description sent with the publication request.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether publication preserves unclassified discoveries. Defaults to true to avoid unexpected deletion.
     */
    keepUnclassifiedTattles?: pulumi.Input<boolean>;
    /**
     * Optional absolute HTTP or HTTPS URL notified by Osano after publication.
     */
    webhookUrl?: pulumi.Input<string>;
}
