// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves the aggregated privacy protocol collections, optionally filtered by jurisdiction and type.
 */
export function getCollections(args?: GetCollectionsArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getCollections", {
        "jurisdiction": args.jurisdiction,
        "type": args.type,
    }, opts);
}

export interface GetCollectionsArgs {
    /**
     * Optional jurisdiction filter, sent as the jurisdiction query parameter.
     */
    jurisdiction?: string;
    /**
     * Optional collection type filter, sent as the type query parameter.
     */
    type?: string;
}

export interface GetCollectionsResult {
    readonly collection: {[key: string]: any};
    readonly jurisdictions: string[];
}
/**
 * Retrieves the aggregated privacy protocol collections, optionally filtered by jurisdiction and type.
 */
export function getCollectionsOutput(args?: GetCollectionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCollectionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getCollections", {
        "jurisdiction": args.jurisdiction,
        "type": args.type,
    }, opts);
}

export interface GetCollectionsOutputArgs {
    /**
     * Optional jurisdiction filter, sent as the jurisdiction query parameter.
     */
    jurisdiction?: pulumi.Input<string>;
    /**
     * Optional collection type filter, sent as the type query parameter.
     */
    type?: pulumi.Input<string>;
}
