// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves a specific privacy protocol collection by ID.
 */
export function getCollection(args: GetCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getCollection", {
        "collectionId": args.collectionId,
    }, opts);
}

/**
 * Arguments for getCollection
 */
export interface GetCollectionArgs {
    collectionId: string;
}

export interface GetCollectionResult {
    readonly collection: {[key: string]: any};
    readonly collectionId: string;
    readonly exists: boolean;
}
/**
 * Retrieves a specific privacy protocol collection by ID.
 */
export function getCollectionOutput(args: GetCollectionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getCollection", {
        "collectionId": args.collectionId,
    }, opts);
}

/**
 * Arguments for getCollection
 */
export interface GetCollectionOutputArgs {
    collectionId: pulumi.Input<string>;
}
