// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves a specific privacy protocol collection by ID.
 */
export function getCollection(args: GetCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getCollection", {
        "collectionId": args.collectionId,
    }, opts);
}

export interface GetCollectionArgs {
    /**
     * The privacy protocol collection ID to fetch.
     */
    collectionId: string;
}

export interface GetCollectionResult {
    /**
     * The collection: collectionId, name, frameworks, configIds, jurisdiction, type, consents, and preferences.
     */
    readonly collection: {[key: string]: any};
    /**
     * The collection ID that was looked up.
     */
    readonly collectionId: string;
    /**
     * Whether Osano returned the collection.
     */
    readonly exists: boolean;
}
/**
 * Retrieves a specific privacy protocol collection by ID.
 */
export function getCollectionOutput(args: GetCollectionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getCollection", {
        "collectionId": args.collectionId,
    }, opts);
}

export interface GetCollectionOutputArgs {
    /**
     * The privacy protocol collection ID to fetch.
     */
    collectionId: pulumi.Input<string>;
}
