// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
 */
export function getSubject(args: GetSubjectArgs, opts?: pulumi.InvokeOptions): Promise<GetSubjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getSubject", {
        "referenceType": args.referenceType,
        "subjectRef": args.subjectRef,
    }, opts);
}

export interface GetSubjectArgs {
    referenceType?: string;
    subjectRef: string;
}

export interface GetSubjectResult {
    readonly anonymousId: string;
    readonly exists: boolean;
    readonly subjectId: string;
    readonly subjectRef: string;
    readonly verifiedId: string;
}
/**
 * Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
 */
export function getSubjectOutput(args: GetSubjectOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSubjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getSubject", {
        "referenceType": args.referenceType,
        "subjectRef": args.subjectRef,
    }, opts);
}

export interface GetSubjectOutputArgs {
    referenceType?: pulumi.Input<string>;
    subjectRef: pulumi.Input<string>;
}
