// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Reads a subject's profile (email and subject ID) using the Unified Consent API key. The outputs are secrets because they hold personal data.
 */
export function getSubjectProfile(args: GetSubjectProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetSubjectProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getSubjectProfile", {
        "subjectId": args.subjectId,
    }, opts);
}

export interface GetSubjectProfileArgs {
    /**
     * The subject ID whose profile is returned.
     */
    subjectId: string;
}

export interface GetSubjectProfileResult {
    /**
     * The subject's email address. Secret, because it is personal data.
     */
    readonly email: string;
    /**
     * Whether Osano returned a profile for the subject.
     */
    readonly exists: boolean;
    /**
     * The complete profile Osano returned. Secret, because it is personal data.
     */
    readonly profile: {[key: string]: any};
    /**
     * The subject ID that was looked up.
     */
    readonly subjectId: string;
}
/**
 * Reads a subject's profile (email and subject ID) using the Unified Consent API key. The outputs are secrets because they hold personal data.
 */
export function getSubjectProfileOutput(args: GetSubjectProfileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSubjectProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getSubjectProfile", {
        "subjectId": args.subjectId,
    }, opts);
}

export interface GetSubjectProfileOutputArgs {
    /**
     * The subject ID whose profile is returned.
     */
    subjectId: pulumi.Input<string>;
}
