// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Sends a verification code to a subject's email or phone using the Osano API key (or the Unified Consent API key when no Osano API key is set). Pulumi runs invokes on every preview, update, and refresh, so declaring this in a stack sends a new code each time; call it from automation rather than from long-lived stack code.
 */
export function sendSubjectCode(args?: SendSubjectCodeArgs, opts?: pulumi.InvokeOptions): Promise<SendSubjectCodeResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:sendSubjectCode", {
        "email": args.email,
        "hashedSubjectId": args.hashedSubjectId,
        "phone": args.phone,
    }, opts);
}

export interface SendSubjectCodeArgs {
    /**
     * Email address to send the code to. Set exactly one of email or phone.
     */
    email?: string;
    /**
     * Optional hashed subject identifier, sent only when set. Osano's current API identifies the subject by email or phone.
     */
    hashedSubjectId?: string;
    /**
     * Phone number to send the code to by SMS. Set exactly one of email or phone.
     */
    phone?: string;
}

export interface SendSubjectCodeResult {
    /**
     * The delivery channel: email or sms.
     */
    readonly channel: string;
    /**
     * The email address or phone number the code was sent to. Secret, because it is personal data.
     */
    readonly destination: string;
    /**
     * The hashed subject identifier sent with the request, if any.
     */
    readonly hashedSubjectId: string;
    /**
     * The SMS challenge session, when Osano returns one; pass it to verifySubjectCode. Empty for email.
     */
    readonly session: string;
}
/**
 * Sends a verification code to a subject's email or phone using the Osano API key (or the Unified Consent API key when no Osano API key is set). Pulumi runs invokes on every preview, update, and refresh, so declaring this in a stack sends a new code each time; call it from automation rather than from long-lived stack code.
 */
export function sendSubjectCodeOutput(args?: SendSubjectCodeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SendSubjectCodeResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:sendSubjectCode", {
        "email": args.email,
        "hashedSubjectId": args.hashedSubjectId,
        "phone": args.phone,
    }, opts);
}

export interface SendSubjectCodeOutputArgs {
    /**
     * Email address to send the code to. Set exactly one of email or phone.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Optional hashed subject identifier, sent only when set. Osano's current API identifies the subject by email or phone.
     */
    hashedSubjectId?: pulumi.Input<string | undefined>;
    /**
     * Phone number to send the code to by SMS. Set exactly one of email or phone.
     */
    phone?: pulumi.Input<string | undefined>;
}
